# Imports

In [1]:
from pathlib import Path
import pandas as pd
from diive.core.io.files import save_parquet, load_parquet
import matplotlib.pyplot as plt

# Load main data

In [2]:
SOURCEDIR = r"../40_FLUX_PROCESSING_CHAIN"
FILENAME = r"46.1_FLUXES_L3.2_NEE_LE_H_FN2O_FCH4.parquet"
FILEPATH = Path(SOURCEDIR) / FILENAME
maindf = load_parquet(filepath=FILEPATH)
maindf

Loaded .parquet file ..\40_FLUX_PROCESSING_CHAIN\46.1_FLUXES_L3.2_NEE_LE_H_FN2O_FCH4.parquet (0.511 seconds).
    --> Detected time resolution of <30 * Minutes> / 30min

                      AIR_CP  AIR_DENSITY    AIR_MV  AIR_RHO_CP  AOA_METHOD  AXES_ROTATION_METHOD  BADM_HEIGHTC  BADM_INSTPAIR_EASTWARD_SEP_GA_CH4  BADM_INSTPAIR_EASTWARD_SEP_GA_CO2  BADM_INSTPAIR_EASTWARD_SEP_GA_H2O  BADM_INSTPAIR_EASTWARD_SEP_GA_N2O  BADM_INSTPAIR_HEIGHT_SEP_GA_CH4  BADM_INSTPAIR_HEIGHT_SEP_GA_CO2  BADM_INSTPAIR_HEIGHT_SEP_GA_H2O  BADM_INSTPAIR_HEIGHT_SEP_GA_N2O  ...  FLAG_SCH4_SINGLE_gfRMED_L3.1_ISFILLED  FCH4_L3.1  FCH4_L3.1_QCF  FCH4_L3.1_QCF0  FLAG_L3.2_FCH4_L3.1_QCF_OUTLIER_ABSLIM_TEST  FLAG_L3.2_FCH4_L3.1_QCF_OUTLIER_HQROLL  FLAG_L3.2_FCH4_L3.1_QCF_OUTLIER_HQROLL_TEST  FLAG_L3.2_FCH4_L3.1_QCF_OUTLIER_HAMPEL_TEST  FLAG_L3.2_FCH4_L3.1_QCF_OUTLIER_ZSCOREROLLING_TEST  SUM_L3.2_FCH4_L3.1_HARDFLAGS  SUM_L3.2_FCH4_L3.1_SOFTFLAGS  SUM_L3.2_FCH4_L3.1_FLAGS  FLAG_L3.2_FCH4_L3.1_QCF  FCH4_L3.1_L3.2_QCF  FCH4_L3.1_L3.2_QCF0
TIMESTAMP_MIDDLE                                                                                                                                                                                                                                                                                                                                                                                 ...
2023-11-07 15:45:00  1009.65      1.18057  0.024459     1191.96         0.0                   1.0           0.5                               -4.5                                NaN                                NaN                               -4.5                             -3.0                              NaN                              NaN                             -3.0  ...                                    1.0 -18.790539            NaN             NaN                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            2.0                           0.0                       2.0                      2.0                 NaN                  NaN
2023-11-07 16:15:00  1009.74      1.18107  0.024448     1192.57         0.0                   1.0           0.5                               -4.5                                NaN                                NaN                               -4.5                             -3.0                              NaN                              NaN                             -3.0  ...                                    0.0  -4.360399      -4.360399             NaN                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            0.0                           1.0                       1.0                      1.0           -4.360399                  NaN
2023-11-07 16:45:00  1009.93      1.18176  0.024430     1193.50         0.0                   1.0           0.5                               -4.5                                NaN                                NaN                               -4.5                             -3.0                              NaN                              NaN                             -3.0  ...                                    0.0   6.843150            NaN             NaN                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            2.0                           0.0                       2.0                      2.0                 NaN                  NaN
2023-11-07 17:15:00  1009.97      1.18428  0.024377     1196.09         0.0                   1.0           0.5                               -4.5                                NaN                                NaN                               -4.5                             -3.0                              NaN                              NaN                             -3.0  ...                                    0.0   2.488800       2.488800        2.488800                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            0.0                           0.0                       0.0                      0.0            2.488800             2.488800
2023-11-07 17:45:00  1010.06      1.18448  0.024372     1196.40         0.0                   1.0           0.5                               -4.5                                NaN                                NaN                               -4.5                             -3.0                              NaN                              NaN                             -3.0  ...                                    0.0  -9.177059      -9.177059       -9.177059                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            0.0                           0.0                       0.0                      0.0           -9.177059            -9.177059
...                      ...          ...       ...         ...         ...                   ...           ...                                ...                                ...                                ...                                ...                              ...                              ...                              ...                              ...  ...                                    ...        ...            ...             ...                                          ...                                     ...                                          ...                                          ...                                                ...                            ...                           ...                       ...                      ...                 ...                  ...
2025-06-04 22:45:00  1014.01      1.14117  0.025232     1157.16         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                                    0.0   2.160966       2.160966        2.160966                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            0.0                           0.0                       0.0                      0.0            2.160966             2.160966
2025-06-04 23:15:00  1014.04      1.14156  0.025222     1157.59         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                                    0.0  -1.904577      -1.904577             NaN                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            0.0                           1.0                       1.0                      1.0           -1.904577                  NaN
2025-06-04 23:45:00  1013.47      1.14369  0.025185     1159.10         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                                    0.0  -1.679224            NaN             NaN                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            2.0                           0.0                       2.0                      2.0                 NaN                  NaN
2025-06-05 00:15:00  1013.36      1.14191  0.025226     1157.17         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                                    0.0   4.656026       4.656026             NaN                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            0.0                           2.0                       2.0                      1.0            4.656026                  NaN
2025-06-05 00:45:00  1013.39      1.14237  0.025216     1157.67         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                                    0.0   1.726895            NaN             NaN                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            2.0                           1.0                       3.0                      2.0                 NaN                  NaN

[27619 rows x 569 columns]

# Load REddyProc output

In [3]:
SOURCEDIR = r"../50_REDDYPROC"
FILENAME = r"51.1_UstarThresholds_MDS-gapfilled_NEE-partitioned.csv"
FILEPATH = Path(SOURCEDIR) / FILENAME
reddy = pd.read_csv(FILEPATH)

# Convert timestamp to datetime and change from end to middle
reddy['TIMESTAMP_MIDDLE'] = pd.to_datetime(reddy['TIMESTAMP_END'], format='%Y-%m-%dT%H:%M:%SZ', errors='coerce') - pd.Timedelta(minutes=15)
# Drop the timestamp end
reddy.drop(columns='TIMESTAMP_END', inplace=True)
# Set the timestamp as index
reddy.set_index('TIMESTAMP_MIDDLE', inplace=True)

# Add a string to identify the reddyproc columns later
reddy.columns = [f'{c}_reddyproc' for c in reddy.columns]

reddy

                     Ustar_U16_Thres_reddyproc  Ustar_U50_Thres_reddyproc  Ustar_U84_Thres_reddyproc  NEE_U16_f_reddyproc  NEE_U50_f_reddyproc  NEE_U84_f_reddyproc  GPP_U16_f_reddyproc  GPP_U50_f_reddyproc  GPP_U84_f_reddyproc  Reco_U16_reddyproc  Reco_U50_reddyproc  Reco_U84_reddyproc  LE_f_reddyproc  H_f_reddyproc
TIMESTAMP_MIDDLE
2023-11-07 15:45:00                   0.084600                   0.106112                   0.135006             1.328996             1.406032             1.406032             0.739229             0.608764             0.672669            2.068225            2.014795            2.078701       28.859389     -11.217375
2023-11-07 16:15:00                   0.084600                   0.106112                   0.135006             1.629891             1.626907             1.630082             0.429134             0.379030             0.439855            2.059025            2.005937            2.069938       27.488270     -13.000232
2023-11-07 16:45:00                   0.084600                   0.106112                   0.135006             2.210941             2.239952             2.275597            -0.170260            -0.251680            -0.223140            2.040680            1.988271            2.052457       17.406233      -1.975767
2023-11-07 17:15:00                   0.084600                   0.106112                   0.135006             2.185616             2.205842             2.292686            -0.222090            -0.291887            -0.313837            1.963526            1.913955            1.978848       13.825620     -11.683789
2023-11-07 17:45:00                   0.084600                   0.106112                   0.135006             2.185616             2.205842             2.292686            -0.217588            -0.287550            -0.309538            1.968028            1.918292            1.983148       13.825620     -10.829124
...                                        ...                        ...                        ...                  ...                  ...                  ...                  ...                  ...                  ...                 ...                 ...                 ...             ...            ...
2025-06-04 21:45:00                   0.072883                   0.093717                   0.131747            10.578562            10.578562            10.578562            -2.093970            -1.558117            -1.515354            8.484592            9.020445            9.063208        2.365148     -37.795644
2025-06-04 22:15:00                   0.072883                   0.093717                   0.131747             9.416519             9.416519             9.416519            -1.006727            -0.474679            -0.429044            8.409792            8.941840            8.987474        3.145603     -33.579604
2025-06-04 22:45:00                   0.072883                   0.093717                   0.131747            10.095010            10.095010            10.095010            -1.624549            -1.089414            -1.046107            8.470461            9.005596            9.048903        3.778325     -38.997547
2025-06-04 23:15:00                   0.072883                   0.093717                   0.131747             8.641342             8.641342             8.641342            -0.192062             0.341996             0.386118            8.449280            8.983338            9.027459       -0.947239     -39.849475
2025-06-04 23:45:00                   0.072883                   0.093717                   0.131747             8.664543             8.664543             8.664543            -0.332127             0.195977             0.244553            8.332416            8.860520            8.909096        2.365148     -53.513862

[27617 rows x 14 columns]

# Merge

In [4]:
newcols = [c for c in reddy.columns if c not in maindf]
print("NEW VARIABLES FROM REDDYPROC:")
[print(f"+ {c}") for c in newcols]
maindf = pd.concat([maindf, reddy[newcols]], axis=1)
maindf

NEW VARIABLES FROM REDDYPROC:
+ Ustar_U16_Thres_reddyproc
+ Ustar_U50_Thres_reddyproc
+ Ustar_U84_Thres_reddyproc
+ NEE_U16_f_reddyproc
+ NEE_U50_f_reddyproc
+ NEE_U84_f_reddyproc
+ GPP_U16_f_reddyproc
+ GPP_U50_f_reddyproc
+ GPP_U84_f_reddyproc
+ Reco_U16_reddyproc
+ Reco_U50_reddyproc
+ Reco_U84_reddyproc
+ LE_f_reddyproc
+ H_f_reddyproc

                      AIR_CP  AIR_DENSITY    AIR_MV  AIR_RHO_CP  AOA_METHOD  AXES_ROTATION_METHOD  BADM_HEIGHTC  BADM_INSTPAIR_EASTWARD_SEP_GA_CH4  BADM_INSTPAIR_EASTWARD_SEP_GA_CO2  BADM_INSTPAIR_EASTWARD_SEP_GA_H2O  BADM_INSTPAIR_EASTWARD_SEP_GA_N2O  BADM_INSTPAIR_HEIGHT_SEP_GA_CH4  BADM_INSTPAIR_HEIGHT_SEP_GA_CO2  BADM_INSTPAIR_HEIGHT_SEP_GA_H2O  BADM_INSTPAIR_HEIGHT_SEP_GA_N2O  ...  FCH4_L3.1_L3.2_QCF0  Ustar_U16_Thres_reddyproc  Ustar_U50_Thres_reddyproc  Ustar_U84_Thres_reddyproc  NEE_U16_f_reddyproc  NEE_U50_f_reddyproc  NEE_U84_f_reddyproc  GPP_U16_f_reddyproc  GPP_U50_f_reddyproc  GPP_U84_f_reddyproc  Reco_U16_reddyproc  Reco_U50_reddyproc  Reco_U84_reddyproc  LE_f_reddyproc  H_f_reddyproc
TIMESTAMP_MIDDLE                                                                                                                                                                                                                                                                                                                                                                                 ...
2023-11-07 15:45:00  1009.65      1.18057  0.024459     1191.96         0.0                   1.0           0.5                               -4.5                                NaN                                NaN                               -4.5                             -3.0                              NaN                              NaN                             -3.0  ...                  NaN                   0.084600                   0.106112                   0.135006             1.328996             1.406032             1.406032             0.739229             0.608764             0.672669            2.068225            2.014795            2.078701       28.859389     -11.217375
2023-11-07 16:15:00  1009.74      1.18107  0.024448     1192.57         0.0                   1.0           0.5                               -4.5                                NaN                                NaN                               -4.5                             -3.0                              NaN                              NaN                             -3.0  ...                  NaN                   0.084600                   0.106112                   0.135006             1.629891             1.626907             1.630082             0.429134             0.379030             0.439855            2.059025            2.005937            2.069938       27.488270     -13.000232
2023-11-07 16:45:00  1009.93      1.18176  0.024430     1193.50         0.0                   1.0           0.5                               -4.5                                NaN                                NaN                               -4.5                             -3.0                              NaN                              NaN                             -3.0  ...                  NaN                   0.084600                   0.106112                   0.135006             2.210941             2.239952             2.275597            -0.170260            -0.251680            -0.223140            2.040680            1.988271            2.052457       17.406233      -1.975767
2023-11-07 17:15:00  1009.97      1.18428  0.024377     1196.09         0.0                   1.0           0.5                               -4.5                                NaN                                NaN                               -4.5                             -3.0                              NaN                              NaN                             -3.0  ...             2.488800                   0.084600                   0.106112                   0.135006             2.185616             2.205842             2.292686            -0.222090            -0.291887            -0.313837            1.963526            1.913955            1.978848       13.825620     -11.683789
2023-11-07 17:45:00  1010.06      1.18448  0.024372     1196.40         0.0                   1.0           0.5                               -4.5                                NaN                                NaN                               -4.5                             -3.0                              NaN                              NaN                             -3.0  ...            -9.177059                   0.084600                   0.106112                   0.135006             2.185616             2.205842             2.292686            -0.217588            -0.287550            -0.309538            1.968028            1.918292            1.983148       13.825620     -10.829124
...                      ...          ...       ...         ...         ...                   ...           ...                                ...                                ...                                ...                                ...                              ...                              ...                              ...                              ...  ...                  ...                        ...                        ...                        ...                  ...                  ...                  ...                  ...                  ...                  ...                 ...                 ...                 ...             ...            ...
2025-06-04 22:45:00  1014.01      1.14117  0.025232     1157.16         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...             2.160966                   0.072883                   0.093717                   0.131747            10.095010            10.095010            10.095010            -1.624549            -1.089414            -1.046107            8.470461            9.005596            9.048903        3.778325     -38.997547
2025-06-04 23:15:00  1014.04      1.14156  0.025222     1157.59         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                  NaN                   0.072883                   0.093717                   0.131747             8.641342             8.641342             8.641342            -0.192062             0.341996             0.386118            8.449280            8.983338            9.027459       -0.947239     -39.849475
2025-06-04 23:45:00  1013.47      1.14369  0.025185     1159.10         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                  NaN                   0.072883                   0.093717                   0.131747             8.664543             8.664543             8.664543            -0.332127             0.195977             0.244553            8.332416            8.860520            8.909096        2.365148     -53.513862
2025-06-05 00:15:00  1013.36      1.14191  0.025226     1157.17         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                  NaN                        NaN                        NaN                        NaN                  NaN                  NaN                  NaN                  NaN                  NaN                  NaN                 NaN                 NaN                 NaN             NaN            NaN
2025-06-05 00:45:00  1013.39      1.14237  0.025216     1157.67         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                  NaN                        NaN                        NaN                        NaN                  NaN                  NaN                  NaN                  NaN                  NaN                  NaN                 NaN                 NaN                 NaN             NaN            NaN

[27619 rows x 583 columns]

# Export

In [5]:
filename = "61.1_FLUXES_L3.2_NEE_LE_H_FN2O_FCH4_REDDYPROC"
maindf.to_csv(f"{filename}.csv", index=True)
save_parquet(data=maindf, filename=filename)

Saved file 61.1_FLUXES_L3.2_NEE_LE_H_FN2O_FCH4_REDDYPROC.parquet (3.926 seconds).

'61.1_FLUXES_L3.2_NEE_LE_H_FN2O_FCH4_REDDYPROC.parquet'