# Imports

In [11]:
import importlib.metadata
import warnings
from datetime import datetime

import pandas as pd
from diive.core.io.filereader import search_files, MultiDataFileReader
from diive.core.io.files import save_parquet

# pd.options.display.width = None
# pd.options.display.max_columns = None
pd.set_option('display.max_rows', 3000)
pd.set_option('display.max_columns', 3000)
warnings.filterwarnings(action='ignore', category=FutureWarning)
warnings.filterwarnings(action='ignore', category=UserWarning)
dt_string = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
version_diive = importlib.metadata.version("diive")
print(f"diive version: v{version_diive}")

diive version: v0.89.0

# Merge L1 results to parquet

In [12]:
# Search original files and store filepaths in list
SOURCEDIR = r"..\..\data\FLUXES\IRGA"
sourcefiles = search_files(searchdirs=SOURCEDIR, pattern='*')
sourcefiles

[WindowsPath('../../data/FLUXES/IRGA/eddypro_CH-TAN_FR-20250819-170250_fluxnet_2025-08-20T235943_adv.csv')]

In [13]:
# Read data from files to dataframe
d = MultiDataFileReader(filepaths=sourcefiles,
                        filetype='EDDYPRO-FLUXNET-CSV-30MIN',
                        output_middle_timestamp=True)
df = d.data_df
df

Reading file eddypro_CH-TAN_FR-20250819-170250_fluxnet_2025-08-20T235943_adv.csv ...

,AIR_MV,AIR_DENSITY,AIR_RHO_CP,AIR_CP,AOA_METHOD,AXES_ROTATION_METHOD,BOWEN,BURBA_METHOD,BADM_LOCATION_LAT,BADM_LOCATION_LONG,BADM_LOCATION_ELEV,BADM_HEIGHTC,BADM_INST_SAMPLING_INT,BADM_INST_AVERAGING_INT,BADM_INST_MODEL_SA,BADM_INST_HEIGHT_SA,BADM_INST_SA_WIND_FORMAT,BADM_INST_SA_GILL_ALIGN,BADM_SA_OFFSET_NORTH,BADM_INST_MODEL_GA_CO2,BADM_INSTPAIR_NORTHWARD_SEP_GA_CO2,BADM_INSTPAIR_EASTWARD_SEP_GA_CO2,BADM_INSTPAIR_HEIGHT_SEP_GA_CO2,BADM_INST_GA_CP_TUBE_LENGTH_GA_CO2,BADM_INST_GA_CP_TUBE_IN_DIAM_GA_CO2,BADM_INST_GA_CP_TUBE_FLOW_RATE_GA_CO2,BADM_INST_MODEL_GA_H2O,BADM_INSTPAIR_NORTHWARD_SEP_GA_H2O,BADM_INSTPAIR_EASTWARD_SEP_GA_H2O,BADM_INSTPAIR_HEIGHT_SEP_GA_H2O,BADM_INST_GA_CP_TUBE_LENGTH_GA_H2O,BADM_INST_GA_CP_TUBE_IN_DIAM_GA_H2O,BADM_INST_GA_CP_TUBE_FLOW_RATE_GA_H2O,BADM_INST_MODEL_GA_CH4,BADM_INSTPAIR_NORTHWARD_SEP_GA_CH4,BADM_INSTPAIR_EASTWARD_SEP_GA_CH4,BADM_INSTPAIR_HEIGHT_SEP_GA_CH4,BADM_INST_GA_CP_TUBE_LENGTH_GA_CH4,BADM_INST_GA_CP_TUBE_IN_DIAM_GA_CH4,BADM_INST_GA_CP_TUBE_FLOW_RATE_GA_CH4,BADM_INST_MODEL_GA_NONE,BADM_INSTPAIR_NORTHWARD_SEP_GA_NONE,BADM_INSTPAIR_EASTWARD_SEP_GA_NONE,BADM_INSTPAIR_HEIGHT_SEP_GA_NONE,BADM_INST_GA_CP_TUBE_LENGTH_GA_NONE,BADM_INST_GA_CP_TUBE_IN_DIAM_GA_NONE,BADM_INST_GA_CP_TUBE_FLOW_RATE_GA_NONE,CUSTOM_FILTER_NR,CO2_NR,CH4_NR,CO2_MEAS_TYPE,CO2_MOLAR_DENSITY,CO2_MIXING_RATIO,CO2,CH4_MEAS_TYPE,CH4_MOLAR_DENSITY,CH4_MIXING_RATIO,CH4,CO2_TLAG_ACTUAL,CO2_TLAG_USED,CO2_TLAG_NOMINAL,CO2_TLAG_MIN,CO2_TLAG_MAX,CH4_TLAG_ACTUAL,CH4_TLAG_USED,CH4_TLAG_NOMINAL,CH4_TLAG_MIN,CH4_TLAG_MAX,CO2_MEAS_MEDIAN,CH4_MEAS_MEDIAN,CO2_MEAS_P25,CH4_MEAS_P25,CO2_MEAS_P75,CH4_MEAS_P75,CO2_MEAS_SIGMA,CH4_MEAS_SIGMA,CO2_MEAS_SKW,CH4_MEAS_SKW,CO2_MEAS_KUR,CH4_MEAS_KUR,CO2_MEAS_H2O_MEAS_COV,CO2_MEAS_CH4_MEAS_COV,CO2_MEAS_NONE_MEAS_COV,CH4_MEAS_NONE_MEAS_COV,CO2_NUM_SPIKES,CH4_NUM_SPIKES,CUSTOM_FILTER_NREX,CO2_DIAG_NREX,CH4_DIAG_NREX,CO2_SPIKE_NREX,CH4_SPIKE_NREX,CO2_ABSLIM_NREX,CH4_ABSLIM_NREX,CO2_VM97_TEST,CH4_VM97_TEST,CO2_LGD,CH4_LGD,CO2_KID,CH4_KID,CO2_ZCD,CH4_ZCD,CUSTOM_DATA_SIZE_IRGA72_MEAN,CUSTOM_STATUS_CODE_IRGA72_MEAN,CUSTOM_GA_DIAG_CODE_IRGA72_MEAN,CUSTOM_SIGNAL_STRENGTH_IRGA72_MEAN,CUSTOM_H2O_MEAN,CUSTOM_CO2_MEAN,CUSTOM_AIR_P_MEAN,CUSTOM_COOLER_V_MEAN,CUSTOM_FLOWRATE_MEAN,DOY_START,DOY_END,DRYAIR_PARTIAL_PRESSURE,DRYAIR_DENSITY,DRYAIR_MV,DETRENDING_METHOD,DENTRENDING_TIME_CONSTANT,DISPLACEMENT_HEIGHT,EXPECT_NR,ET,ET_RANDUNC_HF,ET_UNCORR,ET_STAGE1,ET_STAGE2,ET_SCF,ET_CORRDIFF,ET_SSITC_TEST,FILENAME_HF,FILE_NR,FC_NR,FCH4_NR,FNONE_NR,FC,FH2O,FCH4,FNONE,FC_RANDUNC_HF,FH2O_RANDUNC_HF,FCH4_RANDUNC_HF,FNONE_RANDUNC_HF,FC_VADV,FH2O_VADV,FCH4_VADV,FNONE_VADV,FETCH_MAX,FETCH_OFFSET,FETCH_10,FETCH_30,FETCH_50,FETCH_70,FETCH_80,FETCH_90,FC_UNCORR,FH2O_UNCORR,FCH4_UNCORR,FNONE_UNCORR,FC_STAGE1,FH2O_STAGE1,FCH4_STAGE1,FNONE_STAGE1,FC_STAGE2,FH2O_STAGE2,FCH4_STAGE2,FNONE_STAGE2,FH2O_CELL_CO2,FH2O_CELL_CH4,FH2O_CELL_NONE,FC_SCF,FH2O_SCF,FCH4_SCF,FNONE_SCF,FC_CORRDIFF,FH2O_CORRDIFF,FCH4_CORRDIFF,FNONE_CORRDIFF,FC_NSR,FH2O_NSR,FCH4_NSR,FNONE_NSR,FC_SS,FH2O_SS,FCH4_SS,FNONE_SS,FC_SS_TEST,FH2O_SS_TEST,FCH4_SS_TEST,FNONE_SS_TEST,FC_SSITC_TEST,FH2O_SSITC_TEST,FCH4_SSITC_TEST,FNONE_SSITC_TEST,FOOTPRINT_MODEL,FILE_TIME_DURATION,H2O_NR,H_NR,H,H_RANDUNC_HF,H2O_MEAS_TYPE,H2O_MOLAR_DENSITY,H2O_MIXING_RATIO,H2O,H2O_TLAG_ACTUAL,H2O_TLAG_USED,H2O_TLAG_NOMINAL,H2O_TLAG_MIN,H2O_TLAG_MAX,H2O_MEAS_MEDIAN,H2O_MEAS_P25,H2O_MEAS_P75,H2O_MEAS_SIGMA,H2O_MEAS_SKW,H2O_MEAS_KUR,H2O_MEAS_CH4_MEAS_COV,H2O_MEAS_NONE_MEAS_COV,H_UNCORR,H_STAGE1,H_STAGE2,H_CELL_CO2,H_CELL_H2O,H_CELL_CH4,H_CELL_NONE,H_BU_BOT,H_BU_TOP,H_BU_SPAR,H_SCF,H2O_NUM_SPIKES,H2O_DIAG_NREX,H2O_SPIKE_NREX,H2O_ABSLIM_NREX,H2O_VM97_TEST,H2O_LGD,H2O_KID,H2O_ZCD,H_CORRDIFF,H_NSR,H_SS,H_SS_TEST,H_SSITC_TEST,HPATH_SA,HPATH_GA_CO2,HPATH_GA_H2O,HPATH_GA_CH4,HPATH_GA_NONE,INST_LI7200_HEAD_DETECT,INST_LI7200_T_OUT,INST_LI7200_T_IN,INST_LI7200_AUX_IN,INST_LI7200_DELTA_P,INST_LI7200_CHOPPER,INST_LI7200_DETECTOR,INST_LI7200_PLL,INST_LI7200_SYNC,INST_LI7500_CHOPPER,INST_LI7500_DETECTOR,INST_LI7500_PLL,INST_LI7500_SYNC,INST_LI7700_NOT_READY,INST_LI7700_NO_SIGNAL,INST_LI7700_RE_UNLOCKED,INST_LI7700_BAD_TEMP,INST_LI7700_LASER_T_UNREG,INST_LI7700_BLOCK_T_UNREG,INST_LI7700_MOTOR_SPINNING,INST_LI7700_PUMP_ON,INST_LI7700_TOP_HEATER_ON,INST_LI7700_BOTTOM_HEATER_ON,INST_LI7700_CALIBRATING,INST_LI7700_MOTOR_FAILURE,INST_LI7700_BAD_AUX_TC1,INST_LI7700_BAD_AUX_TC2,INST_LI7700_BAD_AUX_TC3,INST_LI7700_BOX_CONNECTED,INST_LI7200_AGC_OR_RSSI,INST_LI7500_AGC_OR_RSSI,INST_LI7700_RSSI,KRYPTON_HYDRO_KH2O_GA_H2O,KRYPTON_HYDRO_KO2_GA_H2O,LE_NR,LE,LE_RANDUNC_HF,LE_UNCORR,LE_STAGE1,LE_STAGE2,LE_SCF,LE_CORRDIFF,LE_SSITC_TEST,LOGGER_SWVER_MAJOR,LOGGER_SWVER_MINOR,LOGGER_SWVER_REVISION,LW_IN_1_1_1,MO_LENGTH,MO_LENGTH_UNCORR,MV_AIR_CELL_CO2,MV_AIR_CELL_H2O,MV_AIR_CELL_CH4,MV_AIR_CELL_NONE,MANUFACTURER_SA,MANUFACTURER_GA_CO2,MANUFACTURER_GA_H2O,MANUFACTURER_GA_CH4,MANUFACTURER_GA_NONE,NIGHT,NONE_NR,NONE_MEAS_TYPE,NONE_MOLAR_DENSITY,NONE_MIXING_RATIO,NONE,NONE_TLAG_ACTUAL,NONE_TLAG_USED,NONE_TLAG_NOMINAL,NONE_TLAG_MIN,NONE_TLAG_MAX,NONE_MEAS_MEDIAN,NONE_MEAS_P25,NONE_MEAS_P75,NONE_MEAS_SIGMA,NONE_MEAS_SKW,NONE_MEAS_KUR,NONE_NUM_SPIKES,NONE_DIAG_NREX,NONE_SPIKE_NREX,NONE_ABSLIM_NREX,NONE_VM97_TEST,NONE_LGD,NONE_KID,NONE_ZCD,NUM_CUSTOM_VARS,NUM_BIOMET_VARS,PA_EP,PA_CELL,PA_1_1_1,PPFD_IN_1_1_1,RH_EP,ROT_YAW,ROT_PITCH,ROT_ROLL,ROUGHNESS_LENGTH,RESPONSE_TIME_SA,RESPONSE_TIME_GA_CO2,RESPONSE_TIME_GA_H2O,RESPONSE_TIME_GA_CH4,RESPONSE_TIME_GA_NONE,RH_1_1_1,SW_IN_POT,SONIC_NR,SH_SINGLE,SLE_SINGLE,SET_SINGLE,SC_SINGLE,SH2O_SINGLE,SCH4_SINGLE,SNONE_SINGLE,SPECIFIC_HUMIDITY,SPECIFIC_HEAT_EVAP,SPEC_CORR_LI7700_A,SPEC_CORR_LI7700_B,SPEC_CORR_LI7700_C,SONIC_DIAG_NREX,SPECTRAL_CORRECTION_METHOD,SW_IN_1_1_1,TIMESTAMP_START,T_SONIC_NR,TAU_NR,TAU,TAU_RANDUNC_HF,TKE,TSTAR,T_SONIC,TA_EP,TDEW,T_SONIC_MEDIAN,T_SONIC_P25,T_SONIC_P75,T_SONIC_SIGMA,T_SONIC_SKW,T_SONIC_KUR,TAU_UNCORR,TAU_STAGE1,TAU_STAGE2,T_CELL,TAU_SCF,T_SONIC_NUM_SPIKES,T_SONIC_SPIKE_NREX,T_SONIC_ABSLIM_NREX,T_SONIC_VM97_TEST,T_SONIC_LGD,T_SONIC_KID,T_SONIC_ZCD,TAU_CORRDIFF,TAU_NSR,TAU_SS,T_SONIC_ITC,TAU_SS_TEST,T_SONIC_ITC_TEST,TAU_SSITC_TEST,TIMELAG_DETECTION_METHOD,TA_1_1_1,U_UNROT,U,USTAR,U_MEDIAN,U_P25,U_P75,U_SIGMA,U_SKW,U_KUR,USTAR_UNCORR,U_NUM_SPIKES,U_SPIKE_NREX,U_ABSLIM_NREX,U_VM97_TEST,U_LGD,U_KID,U_ZCD,U_ITC,U_ITC_TEST,V_UNROT,V,VAPOR_DENSITY,VAPOR_PARTIAL_PRESSURE,VAPOR_PARTIAL_PRESSURE_SAT,VPD_EP,VAPOR_DRYAIR_RATIO,V_MEDIAN,V_P25,V_P75,V_SIGMA,V_SKW,V_KUR,V_NUM_SPIKES,V_SPIKE_NREX,V_ABSLIM_NREX,V_VM97_TEST,VM97_TLAG_HF,VM97_TLAG_SF,VM97_AOA_HF,VM97_NSHW_HF,V_LGD,V_KID,V_ZCD,VPATH_SA,VPATH_GA_CO2,VPATH_GA_H2O,VPATH_GA_CH4,VPATH_GA_NONE,WD_FILTER_NR,W_UNROT,W,WS,WS_MAX,WD,WD_SIGMA,W_MEDIAN,W_P25,W_P75,W_SIGMA,W_SKW,W_KUR,W_U_COV,W_T_SONIC_COV,W_CO2_MEAS_COV,W_H2O_MEAS_COV,W_CH4_MEAS_COV,W_NONE_MEAS_COV,W_T_SONIC_COV_IBROM,W_T_SONIC_COV_IBROM_N1626,W_T_SONIC_COV_IBROM_N0614,W_T_SONIC_COV_IBROM_N0277,W_T_SONIC_COV_IBROM_N0133,W_T_SONIC_COV_IBROM_N0065,W_T_SONIC_COV_IBROM_N0032,W_T_SONIC_COV_IBROM_N0016,W_T_SONIC_COV_IBROM_N0008,W_T_SONIC_COV_IBROM_N0004,W_NUM_SPIKES,WD_FILTER_NREX,W_SPIKE_NREX,W_ABSLIM_NREX,W_VM97_TEST,W_LGD,W_KID,W_ZCD,W_ITC,W_ITC_TEST,WBOOST_APPLIED,WPL_APPLIED,ZL,ZL_UNCORR
TIMESTAMP_MIDDLE,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2023-11-07 15:45:00,0.024459,1.18057,1191.96,1009.65,0.0,1.0,NaN,0.0,47.4806,8.91186,547.0,0.5,20.0,30.0,NaN,2.03,NaN,NaN,113.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,0.0,NaN,0.0,NaN,0.0,NaN,801001100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,200.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,311.646,311.666,94.5797,1.17462,0.024659,0.0,0.0,0.34,36000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.4901,-3.41295,7.72011,19.2242,29.3181,41.1190,49.2089,61.6038,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,360.0,NaN,33907.0,-0.173415,0.405821,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.168951,-0.168951,-0.168951,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.02642,0.0,0.0,0.0,0.0,801001100.0,NaN,NaN,NaN,0.039091,3.728430,143.0,6.0,2.0,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9999.0,9999.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,271.667,5762.1200,5811.7200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,6.0,95.3500,95.3500,95.3500,134.556000,75.2000,46.1374,1.78762,NaN,0.08,0.02,NaN,NaN,NaN,NaN,75.2000,267.16400,33907.0,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,0.005040,2482680.0,NaN,NaN,NaN,0.0,4.0,65.666700,2.023111e+11,33907.0,33907.0,-0.061388,0.007171,0.600401,-0.000638,14.1285,7.36667,3.23349,14.12,14.09,14.16,0.063338,0.648345,4.81246,-0.060675,-0.061388,-0.061388,7.36667,1.01174,86.0,169.0,0.0,801000111.0,0.0,18.30680,15470.0,0.021502,0.376819,1.0,245.0,1.0,6.0,0.0,2.0,7.36667,1.645400,2.37570,0.228032,2.30049,1.84719,2.83140,0.765680,0.425654,3.02780,0.226705,8.0,12.0,0.0,800000000.0,0.0,7.76702,14.0,15.0,2.0,1.712060,2.566390e-14,0.005951,7.70346,10.24400,2.54050,0.005066,-0.003421,-0.515508,0.449916,0.735135,0.263470,3.28923,39.0,72.0,0.0,800000000.0,80000.0,80000.0,80.0,81.0,0.0,7.59743,131.0,12.5,NaN,NaN,NaN,NaN,33907.0,0.074109,3.509980e-15,2.37570,5.24356,247.240,19.3050,-0.005830,-0.159624,0.156614,0.272238,0.066080,4.66270,-0.046808,-0.000142,NaN,NaN,NaN,NaN,-0.000054,-0.000120,-0.000217,-0.000328,-0.000442,-0.000537,-0.000600,-0.000638,-0.000628,-0.000544,8.0,0.0,11.0,0.0,800000000.0,0.0,7.55335,14.0,19.0,2.0,0.0,0.0,0.000293,0.000291
2023-11-07 16:15:00,0.024448,1.18107,1192.57,1009.74,0.0,1.0,NaN,0.0,47.4806,8.91186,547.0,0.5,20.0,30.0,NaN,2.03,NaN,NaN,113.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,0.0,NaN,0.0,NaN,0.0,NaN,801001100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,200.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,311.666,311.687,94.5875,1.17499,0.024651,0.0,0.0,0.34,36000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,360.0,NaN,36000.0,-5.344500,0.514667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-5.203780,-5.203780,-5.203780,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.02704,0.0,0.0,0.0,0.0,801001100.0,NaN,NaN,NaN,0.016272,0.980613,4.0,1.0,0.0,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9999.0,9999.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,309.667,99.7293,100.5720,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,6.0,95.3733,95.3733,95.3733,54.595100,77.0667,49.4614,2.04700,NaN,0.08,0.02,NaN,NaN,NaN,NaN,77.0667,168.35800,36000.0,-0.089664,-1634.690000,-2.367600,NaN,-36.537000,NaN,NaN,0.005141,2482830.0,NaN,NaN,NaN,0.0,4.0,27.333300,2.023111e+11,36000.0,36000.0,-0.040387,0.005945,0.565629,-0.024235,14.0625,7.30000,3.51602,14.07,14.03,14.10,0.050827,-0.293210,2.87542,-0.039899,-0.040387,-0.040387,7.30000,1.01225,8.0,16.0,0.0,801000011.0,0.0,9.08786,17153.0,0.035920,1.232820,0.0,44.0,1.0,3.0,1.0,2.0,7.30000,1.310570,2.01768,0.184921,1.99414,1.41907,2.58162,0.788707,0.211800,2.51568,0.183799,5.0,9.0,0.0,800000000.0,0.0,12.23850,31.0,41.0,3.0,1.532390,-4.584680e-14,0.006072,7.85875,10.19730,2.33859,0.005168,-0.021533,-0.460614,0.466410,0.663861,0.120429,3.57962,19.0,31.0,0.0,800000000.0,80000.0,80000.0,80.0,80.0,0.0,8.10957,235.0,12.5,NaN,NaN,NaN,NaN,36000.0,0.072070,3.216510e-15,2.01768,5.17510,243.374,21.2881,0.007512,-0.142191,0.154485,0.261699,-0.258009,5.00192,-0.031525,-0.004364,NaN,NaN,NaN,NaN,-0.004330,-0.004202,-0.004004,-0.003727,-0.003373,-0.002928,-0.002393,-0.001825,-0.001300,-0.000878,2.0,0.0,4.0,0.0,800000101.0,0.0,8.81569,31.0,7.0,1.0,0.0,0.0,0.016946,0.016804
2023-11-07 16:45:00,0.024430,1.18176,1193.50,1009.93,0.0,1.0,NaN,0.0,47.4806,8.91186,547.0,0.5,20.0,30.0,NaN,2.03,NaN,NaN,113.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,0.0,NaN,0.0,NaN,0.0,NaN,801001100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,200.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,311.687,311.708,94.5768,1.17542,0.024642,0.0,0.0,0.34,36000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,360.0,NaN,36000.0,-1.796300,0.999846,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.753860,-1.753860,-1.753860,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.02420,0.0,0.0,0.0,0.0,801001100.0,NaN,NaN,NaN,0.049171,1.684960,43.0,3.0,1.0,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9999.0,9999.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,337.333,301.6870,303.8440,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,6.0,95.3967,95.3967,95.3967,11.485700,81.1333,32.9954,2.41931,NaN,0.08,0.02,NaN,NaN,NaN,NaN,81.1333,61.77900,36000.0,-0.179467,-3599.350000,-5.212440,NaN,-80.438900,NaN,NaN,0.005363,2483150.0,NaN,NaN,NaN,0.0,4.0,6.666670,2.023111e+11,36000.0,36000.0,-0.040854,0.007455,0.576129,-0.008095,13.9995,7.16667,4.11689,14.05,13.99,14.10,0.173610,-2.074720,6.40439,-0.040400,-0.040854,-0.040854,7.16667,1.01125,15.0,30.0,0.0,800000111.0,0.0,15.71570,17749.0,0.039154,1.977710,13.0,225.0,1.0,6.0,1.0,2.0,7.16667,1.299840,1.55119,0.185932,1.42476,0.99706,1.91482,0.780558,1.091680,4.33767,0.184895,1.0,2.0,0.0,800000000.0,0.0,12.02880,69.0,39.0,3.0,0.843979,-6.718370e-14,0.006337,8.19824,10.10470,1.90641,0.005391,-0.029499,-0.355619,0.290065,0.702736,0.088211,6.12003,3.0,4.0,0.0,800000100.0,80000.0,80000.0,80.0,81.0,0.0,12.47370,303.0,12.5,NaN,NaN,NaN,NaN,36000.0,0.065479,-5.944700e-15,1.55119,5.08381,262.811,22.5450,0.005028,-0.117357,0.121096,0.221694,-0.210290,6.81205,-0.031297,-0.001470,NaN,NaN,NaN,NaN,-0.002660,-0.002590,-0.002490,-0.002349,-0.002160,-0.001926,-0.001665,-0.001389,-0.001065,-0.000709,3.0,0.0,7.0,0.0,800000101.0,0.0,11.90360,69.0,21.0,2.0,0.0,0.0,0.005602,0.005562
2023-11-07 17:15:00,0.024377,1.18428,1196.09,1009.97,0.0,1.0,NaN,0.0,47.4806,8.91186,547.0,0.5,20.0,30.0,NaN,2.03,NaN,NaN,113.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,0.0,NaN,0.0,NaN,0.0,NaN,801001100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,200.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,311.708,311.729,94.5823,1.17787,0.024591,0.0,0.0,0.34,36000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.5076,-2.80860,6.35307,15.8200,24.1266,33.8379,40.4953,50.6953,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,360.0,NaN,36000.0,-10.919400,1.494270,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-10.600500,-10.600500,-10.600500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.03008,0.0,0.0,0.0,0.0,801001100.0,NaN,NaN,NaN,0.020398,1.837270,3.0,1.0,0.0,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9999.0,9999.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,334.333,102.5050,103.5110,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,6.0,95.4100,95.4100,95.4100,2.446580,85.1667,69.4138,2.33996,NaN,0.08,0.02,NaN,NaN,NaN,NaN,85.1667,3.38364,36000.0,-0.764389,-832.975000,-1.205630,NaN,-18.605400,NaN,NaN,0.005414,2484490.0,NaN,NaN,NaN,0.0,4.0,2.333330,2.023111e+11,36000.0,36000.0,-0.066396,0.008170,0.801651,-0.038556,13.2112,6.60000,4.25367,13.21,13.14,13.28,0.119839,0.244437,3.19968,-0.065522,-0.066396,-0.066396,6.60000,1.01334,8.0,13.0,0.0,800000011.0,0.0,17.66640,15215.0,0.054555,1.392790,0.0,18.0,1.0,2.0,0.0,2.0,6.60000,0.955768,2.72048,0.236779,2.61725,2.11501,3.23396,0.853786,0.592468,3.73113,0.235215,12.0,19.0,0.0,800000000.0,0.0,6.76029,6.0,24.0,2.0,2.544640,4.458560e-14,0.006411,8.27731,9.71895,1.44164,0.005443,-0.012888,-0.490790,0.534196,0.862834,-0.319424,4.19020,28.0,49.0,0.0,800000000.0,80000.0,80000.0,80.0,81.0,0.0,7.20865,96.0,12.5,NaN,NaN,NaN,NaN,36000.0,0.111073,-1.805990e-15,2.72048,7.10203,223.221,17.3483,0.018840,-0.202975,0.226264,0.360373,-0.425796,4.44633,-0.051714,-0.008863,NaN,NaN,NaN,NaN,-0.008348,-0.008106,-0.007725,-0.007200,-0.006509,-0.005634,-0.004639,-0.003703,-0.002888,-0.002163,8.0,0.0,18.0,0.0,800000000.0,0.0,8.91091,6.0,3.0,1.0,0.0,0.0,0.016487,0.016327

# Remove vars with zero records

In [14]:
stats = df.describe().T

In [15]:
# Find available variables that have more than 0 records, remove all others from data
available_vars = stats.loc[stats['count'] > 0].index
not_available_vars = stats.loc[stats['count'] == 0].index
print("No records for the following vars:")
print(stats.loc[not_available_vars])

No records for the following vars:
                                        count  mean  std  min  25%  50%  75%  max
BADM_INST_MODEL_SA                        0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
BADM_INST_SA_WIND_FORMAT                  0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
BADM_INST_SA_GILL_ALIGN                   0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
BADM_INST_MODEL_GA_CO2                    0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
BADM_INST_MODEL_GA_H2O                    0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
BADM_INST_MODEL_GA_CH4                    0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
BADM_INSTPAIR_NORTHWARD_SEP_GA_CH4        0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
BADM_INSTPAIR_EASTWARD_SEP_GA_CH4         0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
BADM_INSTPAIR_HEIGHT_SEP_GA_CH4           0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
BADM_INST_GA_CP_TUBE_LENGTH_GA_CH4        0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
BADM_INST_GA_CP_TUBE_IN_DIAM_GA_CH4       0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
BADM_INST_GA_CP_TUBE_FLOW_RATE_GA_CH4     0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
BADM_INST_MODEL_GA_NONE                   0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
BADM_INSTPAIR_NORTHWARD_SEP_GA_NONE       0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
BADM_INSTPAIR_EASTWARD_SEP_GA_NONE        0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
BADM_INSTPAIR_HEIGHT_SEP_GA_NONE          0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
BADM_INST_GA_CP_TUBE_LENGTH_GA_NONE       0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
BADM_INST_GA_CP_TUBE_IN_DIAM_GA_NONE      0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
BADM_INST_GA_CP_TUBE_FLOW_RATE_GA_NONE    0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CH4_NR                                    0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CH4_MEAS_TYPE                             0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CH4_MOLAR_DENSITY                         0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CH4_MIXING_RATIO                          0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CH4                                       0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CH4_TLAG_ACTUAL                           0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CH4_TLAG_USED                             0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CH4_TLAG_NOMINAL                          0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CH4_TLAG_MIN                              0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CH4_TLAG_MAX                              0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CH4_MEAS_MEDIAN                           0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CH4_MEAS_P25                              0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CH4_MEAS_P75                              0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CH4_MEAS_SIGMA                            0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CH4_MEAS_SKW                              0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CH4_MEAS_KUR                              0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CO2_MEAS_CH4_MEAS_COV                     0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CO2_MEAS_NONE_MEAS_COV                    0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CH4_MEAS_NONE_MEAS_COV                    0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CH4_NUM_SPIKES                            0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CH4_DIAG_NREX                             0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CH4_SPIKE_NREX                            0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CH4_ABSLIM_NREX                           0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CH4_VM97_TEST                             0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CH4_LGD                                   0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CH4_KID                                   0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CH4_ZCD                                   0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FILENAME_HF                               0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FCH4_NR                                   0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FNONE_NR                                  0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FCH4                                      0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FNONE                                     0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FCH4_RANDUNC_HF                           0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FNONE_RANDUNC_HF                          0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FCH4_VADV                                 0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FNONE_VADV                                0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FCH4_UNCORR                               0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FNONE_UNCORR                              0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FCH4_STAGE1                               0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FNONE_STAGE1                              0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FCH4_STAGE2                               0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FNONE_STAGE2                              0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FH2O_CELL_CO2                             0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FH2O_CELL_CH4                             0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FH2O_CELL_NONE                            0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FCH4_SCF                                  0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FNONE_SCF                                 0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FCH4_CORRDIFF                             0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FNONE_CORRDIFF                            0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FCH4_NSR                                  0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FNONE_NSR                                 0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FCH4_SS                                   0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FNONE_SS                                  0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FCH4_SS_TEST                              0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FNONE_SS_TEST                             0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FCH4_SSITC_TEST                           0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FNONE_SSITC_TEST                          0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
H2O_MEAS_CH4_MEAS_COV                     0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
H2O_MEAS_NONE_MEAS_COV                    0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
H_CELL_CO2                                0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
H_CELL_H2O                                0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
H_CELL_CH4                                0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
H_CELL_NONE                               0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
H_BU_BOT                                  0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
H_BU_TOP                                  0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
H_BU_SPAR                                 0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
HPATH_GA_CH4                              0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
HPATH_GA_NONE                             0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7200_HEAD_DETECT                   0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7200_T_OUT                         0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7200_T_IN                          0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7200_AUX_IN                        0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7200_DELTA_P                       0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7200_CHOPPER                       0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7200_DETECTOR                      0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7200_PLL                           0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7200_SYNC                          0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7500_CHOPPER                       0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7500_DETECTOR                      0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7500_PLL                           0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7500_SYNC                          0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7700_NOT_READY                     0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7700_NO_SIGNAL                     0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7700_RE_UNLOCKED                   0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7700_BAD_TEMP                      0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7700_LASER_T_UNREG                 0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7700_BLOCK_T_UNREG                 0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7700_MOTOR_SPINNING                0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7700_PUMP_ON                       0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7700_TOP_HEATER_ON                 0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7700_BOTTOM_HEATER_ON              0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7700_CALIBRATING                   0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7700_MOTOR_FAILURE                 0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7700_BAD_AUX_TC1                   0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7700_BAD_AUX_TC2                   0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7700_BAD_AUX_TC3                   0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7700_BOX_CONNECTED                 0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7700_RSSI                          0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
KRYPTON_HYDRO_KH2O_GA_H2O                 0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
KRYPTON_HYDRO_KO2_GA_H2O                  0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
LOGGER_SWVER_MAJOR                        0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
LOGGER_SWVER_MINOR                        0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
LOGGER_SWVER_REVISION                     0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
MV_AIR_CELL_CH4                           0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
MV_AIR_CELL_NONE                          0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
MANUFACTURER_SA                           0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
MANUFACTURER_GA_CO2                       0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
MANUFACTURER_GA_H2O                       0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
MANUFACTURER_GA_CH4                       0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
MANUFACTURER_GA_NONE                      0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
NONE_NR                                   0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
NONE_MEAS_TYPE                            0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
NONE_MOLAR_DENSITY                        0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
NONE_MIXING_RATIO                         0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
NONE                                      0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
NONE_TLAG_ACTUAL                          0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
NONE_TLAG_USED                            0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
NONE_TLAG_NOMINAL                         0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
NONE_TLAG_MIN                             0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
NONE_TLAG_MAX                             0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
NONE_MEAS_MEDIAN                          0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
NONE_MEAS_P25                             0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
NONE_MEAS_P75                             0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
NONE_MEAS_SIGMA                           0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
NONE_MEAS_SKW                             0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
NONE_MEAS_KUR                             0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
NONE_NUM_SPIKES                           0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
NONE_DIAG_NREX                            0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
NONE_SPIKE_NREX                           0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
NONE_ABSLIM_NREX                          0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
NONE_VM97_TEST                            0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
NONE_LGD                                  0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
NONE_KID                                  0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
NONE_ZCD                                  0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
ROT_ROLL                                  0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
RESPONSE_TIME_GA_CH4                      0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
RESPONSE_TIME_GA_NONE                     0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
SCH4_SINGLE                               0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
SNONE_SINGLE                              0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
SPEC_CORR_LI7700_A                        0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
SPEC_CORR_LI7700_B                        0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
SPEC_CORR_LI7700_C                        0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
VPATH_GA_CH4                              0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
VPATH_GA_NONE                             0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
W_CH4_MEAS_COV                            0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
W_NONE_MEAS_COV                           0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN

In [16]:
print("Removing variables with 0 records ...")
df_available = df[available_vars].copy()

print(f"Variables removed:")
df_not_available = df[not_available_vars].copy()
_list = df_not_available.columns.tolist()
for c in _list:
    print(c, end=" ")

Removing variables with 0 records ...
Variables removed:
BADM_INST_MODEL_SA BADM_INST_SA_WIND_FORMAT BADM_INST_SA_GILL_ALIGN BADM_INST_MODEL_GA_CO2 BADM_INST_MODEL_GA_H2O BADM_INST_MODEL_GA_CH4 BADM_INSTPAIR_NORTHWARD_SEP_GA_CH4 BADM_INSTPAIR_EASTWARD_SEP_GA_CH4 BADM_INSTPAIR_HEIGHT_SEP_GA_CH4 BADM_INST_GA_CP_TUBE_LENGTH_GA_CH4 BADM_INST_GA_CP_TUBE_IN_DIAM_GA_CH4 BADM_INST_GA_CP_TUBE_FLOW_RATE_GA_CH4 BADM_INST_MODEL_GA_NONE BADM_INSTPAIR_NORTHWARD_SEP_GA_NONE BADM_INSTPAIR_EASTWARD_SEP_GA_NONE BADM_INSTPAIR_HEIGHT_SEP_GA_NONE BADM_INST_GA_CP_TUBE_LENGTH_GA_NONE BADM_INST_GA_CP_TUBE_IN_DIAM_GA_NONE BADM_INST_GA_CP_TUBE_FLOW_RATE_GA_NONE CH4_NR CH4_MEAS_TYPE CH4_MOLAR_DENSITY CH4_MIXING_RATIO CH4 CH4_TLAG_ACTUAL CH4_TLAG_USED CH4_TLAG_NOMINAL CH4_TLAG_MIN CH4_TLAG_MAX CH4_MEAS_MEDIAN CH4_MEAS_P25 CH4_MEAS_P75 CH4_MEAS_SIGMA CH4_MEAS_SKW CH4_MEAS_KUR CO2_MEAS_CH4_MEAS_COV CO2_MEAS_NONE_MEAS_COV CH4_MEAS_NONE_MEAS_COV CH4_NUM_SPIKES CH4_DIAG_NREX CH4_SPIKE_NREX CH4_ABSLIM_NREX CH4_VM97_TEST CH4_LGD CH4_KID CH4_ZCD FILENAME_HF FCH4_NR FNONE_NR FCH4 FNONE FCH4_RANDUNC_HF FNONE_RANDUNC_HF FCH4_VADV FNONE_VADV FCH4_UNCORR FNONE_UNCORR FCH4_STAGE1 FNONE_STAGE1 FCH4_STAGE2 FNONE_STAGE2 FH2O_CELL_CO2 FH2O_CELL_CH4 FH2O_CELL_NONE FCH4_SCF FNONE_SCF FCH4_CORRDIFF FNONE_CORRDIFF FCH4_NSR FNONE_NSR FCH4_SS FNONE_SS FCH4_SS_TEST FNONE_SS_TEST FCH4_SSITC_TEST FNONE_SSITC_TEST H2O_MEAS_CH4_MEAS_COV H2O_MEAS_NONE_MEAS_COV H_CELL_CO2 H_CELL_H2O H_CELL_CH4 H_CELL_NONE H_BU_BOT H_BU_TOP H_BU_SPAR HPATH_GA_CH4 HPATH_GA_NONE INST_LI7200_HEAD_DETECT INST_LI7200_T_OUT INST_LI7200_T_IN INST_LI7200_AUX_IN INST_LI7200_DELTA_P INST_LI7200_CHOPPER INST_LI7200_DETECTOR INST_LI7200_PLL INST_LI7200_SYNC INST_LI7500_CHOPPER INST_LI7500_DETECTOR INST_LI7500_PLL INST_LI7500_SYNC INST_LI7700_NOT_READY INST_LI7700_NO_SIGNAL INST_LI7700_RE_UNLOCKED INST_LI7700_BAD_TEMP INST_LI7700_LASER_T_UNREG INST_LI7700_BLOCK_T_UNREG INST_LI7700_MOTOR_SPINNING INST_LI7700_PUMP_ON INST_LI7700_TOP_HEATER_ON INST_LI7700_BOTTOM_HEATER_ON INST_LI7700_CALIBRATING INST_LI7700_MOTOR_FAILURE INST_LI7700_BAD_AUX_TC1 INST_LI7700_BAD_AUX_TC2 INST_LI7700_BAD_AUX_TC3 INST_LI7700_BOX_CONNECTED INST_LI7700_RSSI KRYPTON_HYDRO_KH2O_GA_H2O KRYPTON_HYDRO_KO2_GA_H2O LOGGER_SWVER_MAJOR LOGGER_SWVER_MINOR LOGGER_SWVER_REVISION MV_AIR_CELL_CH4 MV_AIR_CELL_NONE MANUFACTURER_SA MANUFACTURER_GA_CO2 MANUFACTURER_GA_H2O MANUFACTURER_GA_CH4 MANUFACTURER_GA_NONE NONE_NR NONE_MEAS_TYPE NONE_MOLAR_DENSITY NONE_MIXING_RATIO NONE NONE_TLAG_ACTUAL NONE_TLAG_USED NONE_TLAG_NOMINAL NONE_TLAG_MIN NONE_TLAG_MAX NONE_MEAS_MEDIAN NONE_MEAS_P25 NONE_MEAS_P75 NONE_MEAS_SIGMA NONE_MEAS_SKW NONE_MEAS_KUR NONE_NUM_SPIKES NONE_DIAG_NREX NONE_SPIKE_NREX NONE_ABSLIM_NREX NONE_VM97_TEST NONE_LGD NONE_KID NONE_ZCD ROT_ROLL RESPONSE_TIME_GA_CH4 RESPONSE_TIME_GA_NONE SCH4_SINGLE SNONE_SINGLE SPEC_CORR_LI7700_A SPEC_CORR_LI7700_B SPEC_CORR_LI7700_C VPATH_GA_CH4 VPATH_GA_NONE W_CH4_MEAS_COV W_NONE_MEAS_COV

# Remove meteo variables from EC L1 output

In [17]:
removecols = [v for v in df_available.columns if str(v).endswith("_1_1_1")]
print("The following variables will be removed from EC results:")
print(removecols)

The following variables will be removed from EC results:
['LW_IN_1_1_1', 'PA_1_1_1', 'PPFD_IN_1_1_1', 'RH_1_1_1', 'SW_IN_1_1_1', 'TA_1_1_1']

In [18]:
# Remove meteo data from flux results because this meteo has gaps after flux processing
keepcols = []
[keepcols.append(c) for c in df_available.columns if "_1_1_1" not in c]
df_reduced = df_available[keepcols].copy()
df_reduced

,AIR_MV,AIR_DENSITY,AIR_RHO_CP,AIR_CP,AOA_METHOD,AXES_ROTATION_METHOD,BOWEN,BURBA_METHOD,BADM_LOCATION_LAT,BADM_LOCATION_LONG,BADM_LOCATION_ELEV,BADM_HEIGHTC,BADM_INST_SAMPLING_INT,BADM_INST_AVERAGING_INT,BADM_INST_HEIGHT_SA,BADM_SA_OFFSET_NORTH,BADM_INSTPAIR_NORTHWARD_SEP_GA_CO2,BADM_INSTPAIR_EASTWARD_SEP_GA_CO2,BADM_INSTPAIR_HEIGHT_SEP_GA_CO2,BADM_INST_GA_CP_TUBE_LENGTH_GA_CO2,BADM_INST_GA_CP_TUBE_IN_DIAM_GA_CO2,BADM_INST_GA_CP_TUBE_FLOW_RATE_GA_CO2,BADM_INSTPAIR_NORTHWARD_SEP_GA_H2O,BADM_INSTPAIR_EASTWARD_SEP_GA_H2O,BADM_INSTPAIR_HEIGHT_SEP_GA_H2O,BADM_INST_GA_CP_TUBE_LENGTH_GA_H2O,BADM_INST_GA_CP_TUBE_IN_DIAM_GA_H2O,BADM_INST_GA_CP_TUBE_FLOW_RATE_GA_H2O,CUSTOM_FILTER_NR,CO2_NR,CO2_MEAS_TYPE,CO2_MOLAR_DENSITY,CO2_MIXING_RATIO,CO2,CO2_TLAG_ACTUAL,CO2_TLAG_USED,CO2_TLAG_NOMINAL,CO2_TLAG_MIN,CO2_TLAG_MAX,CO2_MEAS_MEDIAN,CO2_MEAS_P25,CO2_MEAS_P75,CO2_MEAS_SIGMA,CO2_MEAS_SKW,CO2_MEAS_KUR,CO2_MEAS_H2O_MEAS_COV,CO2_NUM_SPIKES,CUSTOM_FILTER_NREX,CO2_DIAG_NREX,CO2_SPIKE_NREX,CO2_ABSLIM_NREX,CO2_VM97_TEST,CO2_LGD,CO2_KID,CO2_ZCD,CUSTOM_DATA_SIZE_IRGA72_MEAN,CUSTOM_STATUS_CODE_IRGA72_MEAN,CUSTOM_GA_DIAG_CODE_IRGA72_MEAN,CUSTOM_SIGNAL_STRENGTH_IRGA72_MEAN,CUSTOM_H2O_MEAN,CUSTOM_CO2_MEAN,CUSTOM_AIR_P_MEAN,CUSTOM_COOLER_V_MEAN,CUSTOM_FLOWRATE_MEAN,DOY_START,DOY_END,DRYAIR_PARTIAL_PRESSURE,DRYAIR_DENSITY,DRYAIR_MV,DETRENDING_METHOD,DENTRENDING_TIME_CONSTANT,DISPLACEMENT_HEIGHT,EXPECT_NR,ET,ET_RANDUNC_HF,ET_UNCORR,ET_STAGE1,ET_STAGE2,ET_SCF,ET_CORRDIFF,ET_SSITC_TEST,FILE_NR,FC_NR,FC,FH2O,FC_RANDUNC_HF,FH2O_RANDUNC_HF,FC_VADV,FH2O_VADV,FETCH_MAX,FETCH_OFFSET,FETCH_10,FETCH_30,FETCH_50,FETCH_70,FETCH_80,FETCH_90,FC_UNCORR,FH2O_UNCORR,FC_STAGE1,FH2O_STAGE1,FC_STAGE2,FH2O_STAGE2,FC_SCF,FH2O_SCF,FC_CORRDIFF,FH2O_CORRDIFF,FC_NSR,FH2O_NSR,FC_SS,FH2O_SS,FC_SS_TEST,FH2O_SS_TEST,FC_SSITC_TEST,FH2O_SSITC_TEST,FOOTPRINT_MODEL,FILE_TIME_DURATION,H2O_NR,H_NR,H,H_RANDUNC_HF,H2O_MEAS_TYPE,H2O_MOLAR_DENSITY,H2O_MIXING_RATIO,H2O,H2O_TLAG_ACTUAL,H2O_TLAG_USED,H2O_TLAG_NOMINAL,H2O_TLAG_MIN,H2O_TLAG_MAX,H2O_MEAS_MEDIAN,H2O_MEAS_P25,H2O_MEAS_P75,H2O_MEAS_SIGMA,H2O_MEAS_SKW,H2O_MEAS_KUR,H_UNCORR,H_STAGE1,H_STAGE2,H_SCF,H2O_NUM_SPIKES,H2O_DIAG_NREX,H2O_SPIKE_NREX,H2O_ABSLIM_NREX,H2O_VM97_TEST,H2O_LGD,H2O_KID,H2O_ZCD,H_CORRDIFF,H_NSR,H_SS,H_SS_TEST,H_SSITC_TEST,HPATH_SA,HPATH_GA_CO2,HPATH_GA_H2O,INST_LI7200_AGC_OR_RSSI,INST_LI7500_AGC_OR_RSSI,LE_NR,LE,LE_RANDUNC_HF,LE_UNCORR,LE_STAGE1,LE_STAGE2,LE_SCF,LE_CORRDIFF,LE_SSITC_TEST,MO_LENGTH,MO_LENGTH_UNCORR,MV_AIR_CELL_CO2,MV_AIR_CELL_H2O,NIGHT,NUM_CUSTOM_VARS,NUM_BIOMET_VARS,PA_EP,PA_CELL,RH_EP,ROT_YAW,ROT_PITCH,ROUGHNESS_LENGTH,RESPONSE_TIME_SA,RESPONSE_TIME_GA_CO2,RESPONSE_TIME_GA_H2O,SW_IN_POT,SONIC_NR,SH_SINGLE,SLE_SINGLE,SET_SINGLE,SC_SINGLE,SH2O_SINGLE,SPECIFIC_HUMIDITY,SPECIFIC_HEAT_EVAP,SONIC_DIAG_NREX,SPECTRAL_CORRECTION_METHOD,TIMESTAMP_START,T_SONIC_NR,TAU_NR,TAU,TAU_RANDUNC_HF,TKE,TSTAR,T_SONIC,TA_EP,TDEW,T_SONIC_MEDIAN,T_SONIC_P25,T_SONIC_P75,T_SONIC_SIGMA,T_SONIC_SKW,T_SONIC_KUR,TAU_UNCORR,TAU_STAGE1,TAU_STAGE2,T_CELL,TAU_SCF,T_SONIC_NUM_SPIKES,T_SONIC_SPIKE_NREX,T_SONIC_ABSLIM_NREX,T_SONIC_VM97_TEST,T_SONIC_LGD,T_SONIC_KID,T_SONIC_ZCD,TAU_CORRDIFF,TAU_NSR,TAU_SS,T_SONIC_ITC,TAU_SS_TEST,T_SONIC_ITC_TEST,TAU_SSITC_TEST,TIMELAG_DETECTION_METHOD,U_UNROT,U,USTAR,U_MEDIAN,U_P25,U_P75,U_SIGMA,U_SKW,U_KUR,USTAR_UNCORR,U_NUM_SPIKES,U_SPIKE_NREX,U_ABSLIM_NREX,U_VM97_TEST,U_LGD,U_KID,U_ZCD,U_ITC,U_ITC_TEST,V_UNROT,V,VAPOR_DENSITY,VAPOR_PARTIAL_PRESSURE,VAPOR_PARTIAL_PRESSURE_SAT,VPD_EP,VAPOR_DRYAIR_RATIO,V_MEDIAN,V_P25,V_P75,V_SIGMA,V_SKW,V_KUR,V_NUM_SPIKES,V_SPIKE_NREX,V_ABSLIM_NREX,V_VM97_TEST,VM97_TLAG_HF,VM97_TLAG_SF,VM97_AOA_HF,VM97_NSHW_HF,V_LGD,V_KID,V_ZCD,VPATH_SA,VPATH_GA_CO2,VPATH_GA_H2O,WD_FILTER_NR,W_UNROT,W,WS,WS_MAX,WD,WD_SIGMA,W_MEDIAN,W_P25,W_P75,W_SIGMA,W_SKW,W_KUR,W_U_COV,W_T_SONIC_COV,W_CO2_MEAS_COV,W_H2O_MEAS_COV,W_T_SONIC_COV_IBROM,W_T_SONIC_COV_IBROM_N1626,W_T_SONIC_COV_IBROM_N0614,W_T_SONIC_COV_IBROM_N0277,W_T_SONIC_COV_IBROM_N0133,W_T_SONIC_COV_IBROM_N0065,W_T_SONIC_COV_IBROM_N0032,W_T_SONIC_COV_IBROM_N0016,W_T_SONIC_COV_IBROM_N0008,W_T_SONIC_COV_IBROM_N0004,W_NUM_SPIKES,WD_FILTER_NREX,W_SPIKE_NREX,W_ABSLIM_NREX,W_VM97_TEST,W_LGD,W_KID,W_ZCD,W_ITC,W_ITC_TEST,WBOOST_APPLIED,WPL_APPLIED,ZL,ZL_UNCORR
TIMESTAMP_MIDDLE,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2023-11-07 15:45:00,0.024459,1.18057,1191.96,1009.65,0.0,1.0,NaN,0.0,47.4806,8.91186,547.0,0.5,20.0,30.0,2.03,113.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,801001100.0,NaN,NaN,NaN,2.0,200.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,311.646,311.666,94.5797,1.17462,0.024659,0.0,0.0,0.34,36000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.4901,-3.41295,7.72011,19.2242,29.3181,41.1190,49.2089,61.6038,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,360.0,NaN,33907.0,-0.173415,0.405821,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.168951,-0.168951,-0.168951,1.02642,0.0,0.0,0.0,0.0,801001100.0,NaN,NaN,NaN,0.039091,3.728430,143.0,6.0,2.0,11.0,NaN,NaN,9999.0,9999.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5762.1200,5811.7200,NaN,NaN,0.0,9.0,6.0,95.3500,95.3500,75.2000,46.1374,1.78762,0.08,0.02,NaN,NaN,267.16400,33907.0,NaN,NaN,0.000000,NaN,NaN,0.005040,2482680.0,0.0,4.0,2.023111e+11,33907.0,33907.0,-0.061388,0.007171,0.600401,-0.000638,14.1285,7.36667,3.23349,14.12,14.09,14.16,0.063338,0.648345,4.81246,-0.060675,-0.061388,-0.061388,7.36667,1.01174,86.0,169.0,0.0,801000111.0,0.0,18.30680,15470.0,0.021502,0.376819,1.0,245.0,1.0,6.0,0.0,2.0,1.645400,2.37570,0.228032,2.30049,1.84719,2.83140,0.765680,0.425654,3.02780,0.226705,8.0,12.0,0.0,800000000.0,0.0,7.76702,14.0,15.0,2.0,1.712060,2.566390e-14,0.005951,7.70346,10.24400,2.54050,0.005066,-0.003421,-0.515508,0.449916,0.735135,0.263470,3.28923,39.0,72.0,0.0,800000000.0,80000.0,80000.0,80.0,81.0,0.0,7.59743,131.0,12.5,NaN,NaN,33907.0,0.074109,3.509980e-15,2.37570,5.24356,247.240,19.3050,-0.005830,-0.159624,0.156614,0.272238,0.066080,4.66270,-0.046808,-0.000142,NaN,NaN,-0.000054,-0.000120,-0.000217,-0.000328,-0.000442,-0.000537,-0.000600,-0.000638,-0.000628,-0.000544,8.0,0.0,11.0,0.0,800000000.0,0.0,7.55335,14.0,19.0,2.0,0.0,0.0,0.000293,0.000291
2023-11-07 16:15:00,0.024448,1.18107,1192.57,1009.74,0.0,1.0,NaN,0.0,47.4806,8.91186,547.0,0.5,20.0,30.0,2.03,113.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,801001100.0,NaN,NaN,NaN,2.0,200.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,311.666,311.687,94.5875,1.17499,0.024651,0.0,0.0,0.34,36000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,360.0,NaN,36000.0,-5.344500,0.514667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-5.203780,-5.203780,-5.203780,1.02704,0.0,0.0,0.0,0.0,801001100.0,NaN,NaN,NaN,0.016272,0.980613,4.0,1.0,0.0,11.0,NaN,NaN,9999.0,9999.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99.7293,100.5720,NaN,NaN,0.0,9.0,6.0,95.3733,95.3733,77.0667,49.4614,2.04700,0.08,0.02,NaN,NaN,168.35800,36000.0,-0.089664,-1634.690000,-2.367600,NaN,-36.537000,0.005141,2482830.0,0.0,4.0,2.023111e+11,36000.0,36000.0,-0.040387,0.005945,0.565629,-0.024235,14.0625,7.30000,3.51602,14.07,14.03,14.10,0.050827,-0.293210,2.87542,-0.039899,-0.040387,-0.040387,7.30000,1.01225,8.0,16.0,0.0,801000011.0,0.0,9.08786,17153.0,0.035920,1.232820,0.0,44.0,1.0,3.0,1.0,2.0,1.310570,2.01768,0.184921,1.99414,1.41907,2.58162,0.788707,0.211800,2.51568,0.183799,5.0,9.0,0.0,800000000.0,0.0,12.23850,31.0,41.0,3.0,1.532390,-4.584680e-14,0.006072,7.85875,10.19730,2.33859,0.005168,-0.021533,-0.460614,0.466410,0.663861,0.120429,3.57962,19.0,31.0,0.0,800000000.0,80000.0,80000.0,80.0,80.0,0.0,8.10957,235.0,12.5,NaN,NaN,36000.0,0.072070,3.216510e-15,2.01768,5.17510,243.374,21.2881,0.007512,-0.142191,0.154485,0.261699,-0.258009,5.00192,-0.031525,-0.004364,NaN,NaN,-0.004330,-0.004202,-0.004004,-0.003727,-0.003373,-0.002928,-0.002393,-0.001825,-0.001300,-0.000878,2.0,0.0,4.0,0.0,800000101.0,0.0,8.81569,31.0,7.0,1.0,0.0,0.0,0.016946,0.016804
2023-11-07 16:45:00,0.024430,1.18176,1193.50,1009.93,0.0,1.0,NaN,0.0,47.4806,8.91186,547.0,0.5,20.0,30.0,2.03,113.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,801001100.0,NaN,NaN,NaN,2.0,200.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,311.687,311.708,94.5768,1.17542,0.024642,0.0,0.0,0.34,36000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,360.0,NaN,36000.0,-1.796300,0.999846,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.753860,-1.753860,-1.753860,1.02420,0.0,0.0,0.0,0.0,801001100.0,NaN,NaN,NaN,0.049171,1.684960,43.0,3.0,1.0,11.0,NaN,NaN,9999.0,9999.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,301.6870,303.8440,NaN,NaN,1.0,9.0,6.0,95.3967,95.3967,81.1333,32.9954,2.41931,0.08,0.02,NaN,NaN,61.77900,36000.0,-0.179467,-3599.350000,-5.212440,NaN,-80.438900,0.005363,2483150.0,0.0,4.0,2.023111e+11,36000.0,36000.0,-0.040854,0.007455,0.576129,-0.008095,13.9995,7.16667,4.11689,14.05,13.99,14.10,0.173610,-2.074720,6.40439,-0.040400,-0.040854,-0.040854,7.16667,1.01125,15.0,30.0,0.0,800000111.0,0.0,15.71570,17749.0,0.039154,1.977710,13.0,225.0,1.0,6.0,1.0,2.0,1.299840,1.55119,0.185932,1.42476,0.99706,1.91482,0.780558,1.091680,4.33767,0.184895,1.0,2.0,0.0,800000000.0,0.0,12.02880,69.0,39.0,3.0,0.843979,-6.718370e-14,0.006337,8.19824,10.10470,1.90641,0.005391,-0.029499,-0.355619,0.290065,0.702736,0.088211,6.12003,3.0,4.0,0.0,800000100.0,80000.0,80000.0,80.0,81.0,0.0,12.47370,303.0,12.5,NaN,NaN,36000.0,0.065479,-5.944700e-15,1.55119,5.08381,262.811,22.5450,0.005028,-0.117357,0.121096,0.221694,-0.210290,6.81205,-0.031297,-0.001470,NaN,NaN,-0.002660,-0.002590,-0.002490,-0.002349,-0.002160,-0.001926,-0.001665,-0.001389,-0.001065,-0.000709,3.0,0.0,7.0,0.0,800000101.0,0.0,11.90360,69.0,21.0,2.0,0.0,0.0,0.005602,0.005562
2023-11-07 17:15:00,0.024377,1.18428,1196.09,1009.97,0.0,1.0,NaN,0.0,47.4806,8.91186,547.0,0.5,20.0,30.0,2.03,113.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,801001100.0,NaN,NaN,NaN,2.0,200.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,311.708,311.729,94.5823,1.17787,0.024591,0.0,0.0,0.34,36000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.5076,-2.80860,6.35307,15.8200,24.1266,33.8379,40.4953,50.6953,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,360.0,NaN,36000.0,-10.919400,1.494270,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-10.600500,-10.600500,-10.600500,1.03008,0.0,0.0,0.0,0.0,801001100.0,NaN,NaN,NaN,0.020398,1.837270,3.0,1.0,0.0,11.0,NaN,NaN,9999.0,9999.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.5050,103.5110,NaN,NaN,1.0,9.0,6.0,95.4100,95.4100,85.1667,69.4138,2.33996,0.08,0.02,NaN,NaN,3.38364,36000.0,-0.764389,-832.975000,-1.205630,NaN,-18.605400,0.005414,2484490.0,0.0,4.0,2.023111e+11,36000.0,36000.0,-0.066396,0.008170,0.801651,-0.038556,13.2112,6.60000,4.25367,13.21,13.14,13.28,0.119839,0.244437,3.19968,-0.065522,-0.066396,-0.066396,6.60000,1.01334,8.0,13.0,0.0,800000011.0,0.0,17.66640,15215.0,0.054555,1.392790,0.0,18.0,1.0,2.0,0.0,2.0,0.955768,2.72048,0.236779,2.61725,2.11501,3.23396,0.853786,0.592468,3.73113,0.235215,12.0,19.0,0.0,800000000.0,0.0,6.76029,6.0,24.0,2.0,2.544640,4.458560e-14,0.006411,8.27731,9.71895,1.44164,0.005443,-0.012888,-0.490790,0.534196,0.862834,-0.319424,4.19020,28.0,49.0,0.0,800000000.0,80000.0,80000.0,80.0,81.0,0.0,7.20865,96.0,12.5,NaN,NaN,36000.0,0.111073,-1.805990e-15,2.72048,7.10203,223.221,17.3483,0.018840,-0.202975,0.226264,0.360373,-0.425796,4.44633,-0.051714,-0.008863,NaN,NaN,-0.008348,-0.008106,-0.007725,-0.007200,-0.006509,-0.005634,-0.004639,-0.003703,-0.002888,-0.002163,8.0,0.0,18.0,0.0,800000000.0,0.0,8.91091,6.0,3.0,1.0,0.0,0.0,0.016487,0.016327
2023-11-07 17:45:00,0.024372,1.18448,1196.40,1010.06,0.0,1.0,NaN,0.0,47.4806,8.91186,547.0,0.5,20.0,30.0,2.03,113.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,801001100.0,NaN,NaN,NaN,2.0,200.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,311.729,311.750,94.5994,1.17794,0.024589,0.0,0.0,0.34,36000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.5982,-2.97411,6.72744,16.7523,25.5483,35.8318,42.8816,53.6826,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,360.0,NaN,36000.0,-10.874100,1.200400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-10.552000,-10.552000,-10.552000,1.03052,0.0,0.0,0.0,0.0,801001100.0,NaN,NaN,NaN,0.001114,1.290340,1.0,1.0,0.0,11.0,NaN,NaN,9999.0,9999.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,167.4780,169.1710,NaN,NaN,1.0,9.0,6.0,95.4433,95.4433,86.6333,72.1923,2.51939,0.08,0.02,NaN,NaN,0.00000,36000.0,0.044976,-1699.380000,-2.459720,NaN,-37.958700,0.005518,2484410.0,0.0,4.0,2.023111e+11,36000.0,36000.0,-0.091847,0.011294,0.902566,-0.032640,13.2558,6.63333,4.53015,13.24,13.19,13.31,0.102951,0.926548,4.88694,-0.090631,-0.091847,-0.091847,6.63333,1.01342,12.0,17.0,0.0,800000011.0,0.0,14.76220,12621.0,0.049471,1.114210,0.0,35.0,1.0,3.0,0.0,2.0,0.912536,2.98675,0.278465,2.87024,2.31425,3.56926,0.932995,0.542603,3.20374,0.276615,13.0,19.0,0.0,800000000.0,0.0,6.48186,0.0,18.0,2.0,2.840900,2.054460e-13,0.006536,8.43919,9.74127,1.30208,0.005549,-0.061476,-0.602705,0.543933,0.882609,0.365205,3.28590,18.0,33.0,0.0,800000000.0,80000.0,80000.0,80.0,80.0,0.0,6.78122,70.0,12.5,NaN,NaN,36000.0,0.131290,-1.004420e-14,2.98675,7.00917,221.055,16.7315,0.027332,-0.223583,0.246510,0.394530,-0.405291,4.11250,-0.076123,-0.008820,NaN,NaN,-0.009130,-0.008750,-0.008114,-0.007236,-0.006175,-0.004970,-0.003700,-0.002537,-0.001597,-0.000934,6.0,0.0,9.0,0.0,800000000.0,0.0,7.65645,0.0,1.0,1.0,0.0,0.0,0.010091,0.009990
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-06-04 22:45:00,0.025232,1.14117,1157.16,1014.01,0.0,1.0,-10.51900,0.0,47.4806,8.91186,547.0,0.5,20.0,30.0,2.03,113.0,-16.0,2.0,-2.5,100.0,9.5,12.4310,-16.0,2.0,-2.5,100.0,9.5,12.4310,36000.0,35988.0,0.0,17.2291,444.070,437.537,1.3,1.3,1.3,1.2,1.4,444.011,443.017,445.118,1.48169,0.167802,2.55412,0.134723,3.0,0.0,0.0,5.0,0.0,801000000.0,1.25,7.55495,102.0,26.0,0.0,8190.0,93.38,578.893,17.2156,95089.5,2.07113,0.000207,155.937,155.958,93.6786,1.13002,0.025632,0.0,0.0,0.34,36000.0,0.005439,0.002695,0.003262,0.003262,0.003262,1.66712,0.002660,0.0,36000.0,35988.0,10.10000,0.083930,0.580992,0.041591,1.128400e-10,4.027990e-12,21.1889,-3.21549,7.27345,18.1119,27.6218,38.7400,46.3619,58.0396,7.57948,0.050344,7.57948,0.050344,7.57948,0.050345,1.33255,1.66712,0.002074,0.002660,0.763819,0.894327,1.0,18.0,1.0,2.0,0.0,0.0,0.0,360.0,35988.0,36000.0,-39.184600,2.197470,0.0,615.018,15.8663,15.6185,4.00,1.4,1.4,1.25,4.0,14.9513,14.839,15.029,0.117328,-0.455418,2.27536,-37.958500,-37.958500,-37.907600,1.03369,2.0,0.0,2.0,0.0,801000011.0,1.35,3.00607,4829.0,0.009163,1.807780,0.0,1.0,0.0,11.0,1.27,1.27,9999.0,9999.0,35988.0,3.72513,1.84594,2.234470,2.234470,2.234470,1.66712,0.002660,0.0,147.4460,148.9100,0.025395,0.025395,1.0,9.0,6.0,95.1653,94.6207,83.8200,75.2541,1.39783,0.08,0.02,0.1,0.1,0.00000,36000.0,0.187053,0.053195,0.000078,-0.004990,0.001199,0.009775,2463020.0,0.0,4.0,2.025060e+11,36000.0,36000.0,-0.191152,0.014956,1.496490,-0.082739,21.7283,15.66000,12.89860,21.73,21.60,21.86,0.194978,0.029866,2.60717,-0.188380,-0.191152,-0.191152,15.86990,1.01472,1.0,1.0,0.0,800000001.0,0.0,10.22050,5489.0,0.068684,1.158590,0.0,48.0,1.0,3.0,0.0,2.0,0.904371,3.55413,0.409273,3.39351,2.69482,4.24913,1.204340,0.695603,3.60124,0.406295,29.0,49.0,0.0,800000000.0,0.0,6.32934,1.0,10.0,1.0,3.436050,-5.295810e-16,0.011154,14.86740,17.73730,2.86989,0.009871,-0.060060,-0.751711,0.656610,1.125290,0.406770,3.72094,31.0,44.0,0.0,800000000.0,81100.0,81100.0,80.0,80.0,0.0,6.71147,24.0,12.5,12.7,12.7,36000.0,0.086701,6.549380e-15,3.55413,8.68823,218.431,17.4509,0.003604,-0.298624,0.314153,0.525633,-0.127784,4.34710,-0.164623,-0.032803,0.194277,0.001290,-0.032209,-0.029887,-0.026716,-0.022829,-0.018432,-0.013932,-0.009827,-0.006516,-0.004072,-0.002404,2.0,0.0,2.0,0.0,800000000.0,0.0,6.91874,1.0,5.0,1.0,0.0,0.0,0.011462,0.011349

# Save to file

In [19]:
OUTNAME = "31.1_CH-TAN_IRGA_Level-1_eddypro_fluxnet"
filepath = save_parquet(filename=OUTNAME, data=df_reduced)
df_reduced.to_csv(f"{OUTNAME}.csv")

Saved file 31.1_CH-TAN_IRGA_Level-1_eddypro_fluxnet.parquet (2.033 seconds).

# **End of notebook**.

In [20]:
dt_string = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
print(f"Finished. {dt_string}")

Finished. 2025-08-21 16:44:32