# Imports

In [1]:
import importlib.metadata
import warnings
from datetime import datetime

import pandas as pd
from diive.core.io.filereader import search_files, MultiDataFileReader
from diive.core.io.files import save_parquet

# pd.options.display.width = None
# pd.options.display.max_columns = None
pd.set_option('display.max_rows', 3000)
pd.set_option('display.max_columns', 3000)
warnings.filterwarnings(action='ignore', category=FutureWarning)
warnings.filterwarnings(action='ignore', category=UserWarning)
dt_string = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
version_diive = importlib.metadata.version("diive")
print(f"diive version: v{version_diive}")

diive version: v0.89.0

# Merge L1 results to parquet

In [2]:
# Search original files and store filepaths in list
SOURCEDIR = r"..\..\data\FLUXES\LGR"
sourcefiles = search_files(searchdirs=SOURCEDIR, pattern='*')
sourcefiles

[WindowsPath('../../data/FLUXES/LGR/eddypro_CH-TAN_FR-20250819-170305_fluxnet_2025-08-20T224041_adv.csv')]

In [3]:
# Read data from files to dataframe
d = MultiDataFileReader(filepaths=sourcefiles,
                        filetype='EDDYPRO-FLUXNET-CSV-30MIN',
                        output_middle_timestamp=True)
df = d.data_df
df

Reading file eddypro_CH-TAN_FR-20250819-170305_fluxnet_2025-08-20T224041_adv.csv ...

,AIR_MV,AIR_DENSITY,AIR_RHO_CP,AIR_CP,AOA_METHOD,AXES_ROTATION_METHOD,BOWEN,BURBA_METHOD,BADM_LOCATION_LAT,BADM_LOCATION_LONG,BADM_LOCATION_ELEV,BADM_HEIGHTC,BADM_INST_SAMPLING_INT,BADM_INST_AVERAGING_INT,BADM_INST_MODEL_SA,BADM_INST_HEIGHT_SA,BADM_INST_SA_WIND_FORMAT,BADM_INST_SA_GILL_ALIGN,BADM_SA_OFFSET_NORTH,BADM_INST_MODEL_GA_CO2,BADM_INSTPAIR_NORTHWARD_SEP_GA_CO2,BADM_INSTPAIR_EASTWARD_SEP_GA_CO2,BADM_INSTPAIR_HEIGHT_SEP_GA_CO2,BADM_INST_GA_CP_TUBE_LENGTH_GA_CO2,BADM_INST_GA_CP_TUBE_IN_DIAM_GA_CO2,BADM_INST_GA_CP_TUBE_FLOW_RATE_GA_CO2,BADM_INST_MODEL_GA_H2O,BADM_INSTPAIR_NORTHWARD_SEP_GA_H2O,BADM_INSTPAIR_EASTWARD_SEP_GA_H2O,BADM_INSTPAIR_HEIGHT_SEP_GA_H2O,BADM_INST_GA_CP_TUBE_LENGTH_GA_H2O,BADM_INST_GA_CP_TUBE_IN_DIAM_GA_H2O,BADM_INST_GA_CP_TUBE_FLOW_RATE_GA_H2O,BADM_INST_MODEL_GA_CH4,BADM_INSTPAIR_NORTHWARD_SEP_GA_CH4,BADM_INSTPAIR_EASTWARD_SEP_GA_CH4,BADM_INSTPAIR_HEIGHT_SEP_GA_CH4,BADM_INST_GA_CP_TUBE_LENGTH_GA_CH4,BADM_INST_GA_CP_TUBE_IN_DIAM_GA_CH4,BADM_INST_GA_CP_TUBE_FLOW_RATE_GA_CH4,BADM_INST_MODEL_GA_N2O,BADM_INSTPAIR_NORTHWARD_SEP_GA_N2O,BADM_INSTPAIR_EASTWARD_SEP_GA_N2O,BADM_INSTPAIR_HEIGHT_SEP_GA_N2O,BADM_INST_GA_CP_TUBE_LENGTH_GA_N2O,BADM_INST_GA_CP_TUBE_IN_DIAM_GA_N2O,BADM_INST_GA_CP_TUBE_FLOW_RATE_GA_N2O,CUSTOM_FILTER_NR,CO2_NR,CH4_NR,CO2_MEAS_TYPE,CO2_MOLAR_DENSITY,CO2_MIXING_RATIO,CO2,CH4_MEAS_TYPE,CH4_MOLAR_DENSITY,CH4_MIXING_RATIO,CH4,CO2_TLAG_ACTUAL,CO2_TLAG_USED,CO2_TLAG_NOMINAL,CO2_TLAG_MIN,CO2_TLAG_MAX,CH4_TLAG_ACTUAL,CH4_TLAG_USED,CH4_TLAG_NOMINAL,CH4_TLAG_MIN,CH4_TLAG_MAX,CO2_MEAS_MEDIAN,CH4_MEAS_MEDIAN,CO2_MEAS_P25,CH4_MEAS_P25,CO2_MEAS_P75,CH4_MEAS_P75,CO2_MEAS_SIGMA,CH4_MEAS_SIGMA,CO2_MEAS_SKW,CH4_MEAS_SKW,CO2_MEAS_KUR,CH4_MEAS_KUR,CO2_MEAS_H2O_MEAS_COV,CO2_MEAS_CH4_MEAS_COV,CO2_MEAS_N2O_MEAS_COV,CH4_MEAS_N2O_MEAS_COV,CO2_NUM_SPIKES,CH4_NUM_SPIKES,CUSTOM_FILTER_NREX,CO2_DIAG_NREX,CH4_DIAG_NREX,CO2_SPIKE_NREX,CH4_SPIKE_NREX,CO2_ABSLIM_NREX,CH4_ABSLIM_NREX,CO2_VM97_TEST,CH4_VM97_TEST,CO2_LGD,CH4_LGD,CO2_KID,CH4_KID,CO2_ZCD,CH4_ZCD,CUSTOM_DATA_SIZE_LGR_MEAN,CUSTOM_STATUS_CODE_LGR_MEAN,CUSTOM_CH4_MEAN,CUSTOM_N2O_MEAN,CUSTOM_T_UNKNOWN_MEAN,CUSTOM_MIRROR_RINGDOWNTIME_MEAN,CUSTOM_FIT_FLAG_MEAN,DOY_START,DOY_END,DRYAIR_PARTIAL_PRESSURE,DRYAIR_DENSITY,DRYAIR_MV,DETRENDING_METHOD,DENTRENDING_TIME_CONSTANT,DISPLACEMENT_HEIGHT,EXPECT_NR,ET,ET_RANDUNC_HF,ET_UNCORR,ET_STAGE1,ET_STAGE2,ET_SCF,ET_CORRDIFF,ET_SSITC_TEST,FILENAME_HF,FILE_NR,FC_NR,FCH4_NR,FN2O_NR,FC,FH2O,FCH4,FN2O,FC_RANDUNC_HF,FH2O_RANDUNC_HF,FCH4_RANDUNC_HF,FN2O_RANDUNC_HF,FC_VADV,FH2O_VADV,FCH4_VADV,FN2O_VADV,FETCH_MAX,FETCH_OFFSET,FETCH_10,FETCH_30,FETCH_50,FETCH_70,FETCH_80,FETCH_90,FC_UNCORR,FH2O_UNCORR,FCH4_UNCORR,FN2O_UNCORR,FC_STAGE1,FH2O_STAGE1,FCH4_STAGE1,FN2O_STAGE1,FC_STAGE2,FH2O_STAGE2,FCH4_STAGE2,FN2O_STAGE2,FH2O_CELL_CO2,FH2O_CELL_CH4,FH2O_CELL_N2O,FC_SCF,FH2O_SCF,FCH4_SCF,FN2O_SCF,FC_CORRDIFF,FH2O_CORRDIFF,FCH4_CORRDIFF,FN2O_CORRDIFF,FC_NSR,FH2O_NSR,FCH4_NSR,FN2O_NSR,FC_SS,FH2O_SS,FCH4_SS,FN2O_SS,FC_SS_TEST,FH2O_SS_TEST,FCH4_SS_TEST,FN2O_SS_TEST,FC_SSITC_TEST,FH2O_SSITC_TEST,FCH4_SSITC_TEST,FN2O_SSITC_TEST,FOOTPRINT_MODEL,FILE_TIME_DURATION,H2O_NR,H_NR,H,H_RANDUNC_HF,H2O_MEAS_TYPE,H2O_MOLAR_DENSITY,H2O_MIXING_RATIO,H2O,H2O_TLAG_ACTUAL,H2O_TLAG_USED,H2O_TLAG_NOMINAL,H2O_TLAG_MIN,H2O_TLAG_MAX,H2O_MEAS_MEDIAN,H2O_MEAS_P25,H2O_MEAS_P75,H2O_MEAS_SIGMA,H2O_MEAS_SKW,H2O_MEAS_KUR,H2O_MEAS_CH4_MEAS_COV,H2O_MEAS_N2O_MEAS_COV,H_UNCORR,H_STAGE1,H_STAGE2,H_CELL_CO2,H_CELL_H2O,H_CELL_CH4,H_CELL_N2O,H_BU_BOT,H_BU_TOP,H_BU_SPAR,H_SCF,H2O_NUM_SPIKES,H2O_DIAG_NREX,H2O_SPIKE_NREX,H2O_ABSLIM_NREX,H2O_VM97_TEST,H2O_LGD,H2O_KID,H2O_ZCD,H_CORRDIFF,H_NSR,H_SS,H_SS_TEST,H_SSITC_TEST,HPATH_SA,HPATH_GA_CO2,HPATH_GA_H2O,HPATH_GA_CH4,HPATH_GA_N2O,INST_LI7200_HEAD_DETECT,INST_LI7200_T_OUT,INST_LI7200_T_IN,INST_LI7200_AUX_IN,INST_LI7200_DELTA_P,INST_LI7200_CHOPPER,INST_LI7200_DETECTOR,INST_LI7200_PLL,INST_LI7200_SYNC,INST_LI7500_CHOPPER,INST_LI7500_DETECTOR,INST_LI7500_PLL,INST_LI7500_SYNC,INST_LI7700_NOT_READY,INST_LI7700_NO_SIGNAL,INST_LI7700_RE_UNLOCKED,INST_LI7700_BAD_TEMP,INST_LI7700_LASER_T_UNREG,INST_LI7700_BLOCK_T_UNREG,INST_LI7700_MOTOR_SPINNING,INST_LI7700_PUMP_ON,INST_LI7700_TOP_HEATER_ON,INST_LI7700_BOTTOM_HEATER_ON,INST_LI7700_CALIBRATING,INST_LI7700_MOTOR_FAILURE,INST_LI7700_BAD_AUX_TC1,INST_LI7700_BAD_AUX_TC2,INST_LI7700_BAD_AUX_TC3,INST_LI7700_BOX_CONNECTED,INST_LI7200_AGC_OR_RSSI,INST_LI7500_AGC_OR_RSSI,INST_LI7700_RSSI,KRYPTON_HYDRO_KH2O_GA_H2O,KRYPTON_HYDRO_KO2_GA_H2O,LE_NR,LE,LE_RANDUNC_HF,LE_UNCORR,LE_STAGE1,LE_STAGE2,LE_SCF,LE_CORRDIFF,LE_SSITC_TEST,LOGGER_SWVER_MAJOR,LOGGER_SWVER_MINOR,LOGGER_SWVER_REVISION,LW_IN_1_1_1,MO_LENGTH,MO_LENGTH_UNCORR,MV_AIR_CELL_CO2,MV_AIR_CELL_H2O,MV_AIR_CELL_CH4,MV_AIR_CELL_N2O,MANUFACTURER_SA,MANUFACTURER_GA_CO2,MANUFACTURER_GA_H2O,MANUFACTURER_GA_CH4,MANUFACTURER_GA_N2O,NIGHT,N2O_NR,N2O_MEAS_TYPE,N2O_MOLAR_DENSITY,N2O_MIXING_RATIO,N2O,N2O_TLAG_ACTUAL,N2O_TLAG_USED,N2O_TLAG_NOMINAL,N2O_TLAG_MIN,N2O_TLAG_MAX,N2O_MEAS_MEDIAN,N2O_MEAS_P25,N2O_MEAS_P75,N2O_MEAS_SIGMA,N2O_MEAS_SKW,N2O_MEAS_KUR,N2O_NUM_SPIKES,N2O_DIAG_NREX,N2O_SPIKE_NREX,N2O_ABSLIM_NREX,N2O_VM97_TEST,N2O_LGD,N2O_KID,N2O_ZCD,NUM_CUSTOM_VARS,NUM_BIOMET_VARS,PA_EP,PA_CELL,PA_1_1_1,PPFD_IN_1_1_1,RH_EP,ROT_YAW,ROT_PITCH,ROT_ROLL,ROUGHNESS_LENGTH,RESPONSE_TIME_SA,RESPONSE_TIME_GA_CO2,RESPONSE_TIME_GA_H2O,RESPONSE_TIME_GA_CH4,RESPONSE_TIME_GA_N2O,RH_1_1_1,SW_IN_POT,SONIC_NR,SH_SINGLE,SLE_SINGLE,SET_SINGLE,SC_SINGLE,SH2O_SINGLE,SCH4_SINGLE,SN2O_SINGLE,SPECIFIC_HUMIDITY,SPECIFIC_HEAT_EVAP,SPEC_CORR_LI7700_A,SPEC_CORR_LI7700_B,SPEC_CORR_LI7700_C,SONIC_DIAG_NREX,SPECTRAL_CORRECTION_METHOD,SW_IN_1_1_1,TIMESTAMP_START,T_SONIC_NR,TAU_NR,TAU,TAU_RANDUNC_HF,TKE,TSTAR,T_SONIC,TA_EP,TDEW,T_SONIC_MEDIAN,T_SONIC_P25,T_SONIC_P75,T_SONIC_SIGMA,T_SONIC_SKW,T_SONIC_KUR,TAU_UNCORR,TAU_STAGE1,TAU_STAGE2,T_CELL,TAU_SCF,T_SONIC_NUM_SPIKES,T_SONIC_SPIKE_NREX,T_SONIC_ABSLIM_NREX,T_SONIC_VM97_TEST,T_SONIC_LGD,T_SONIC_KID,T_SONIC_ZCD,TAU_CORRDIFF,TAU_NSR,TAU_SS,T_SONIC_ITC,TAU_SS_TEST,T_SONIC_ITC_TEST,TAU_SSITC_TEST,TIMELAG_DETECTION_METHOD,TA_1_1_1,U_UNROT,U,USTAR,U_MEDIAN,U_P25,U_P75,U_SIGMA,U_SKW,U_KUR,USTAR_UNCORR,U_NUM_SPIKES,U_SPIKE_NREX,U_ABSLIM_NREX,U_VM97_TEST,U_LGD,U_KID,U_ZCD,U_ITC,U_ITC_TEST,V_UNROT,V,VAPOR_DENSITY,VAPOR_PARTIAL_PRESSURE,VAPOR_PARTIAL_PRESSURE_SAT,VPD_EP,VAPOR_DRYAIR_RATIO,V_MEDIAN,V_P25,V_P75,V_SIGMA,V_SKW,V_KUR,V_NUM_SPIKES,V_SPIKE_NREX,V_ABSLIM_NREX,V_VM97_TEST,VM97_TLAG_HF,VM97_TLAG_SF,VM97_AOA_HF,VM97_NSHW_HF,V_LGD,V_KID,V_ZCD,VPATH_SA,VPATH_GA_CO2,VPATH_GA_H2O,VPATH_GA_CH4,VPATH_GA_N2O,WD_FILTER_NR,W_UNROT,W,WS,WS_MAX,WD,WD_SIGMA,W_MEDIAN,W_P25,W_P75,W_SIGMA,W_SKW,W_KUR,W_U_COV,W_T_SONIC_COV,W_CO2_MEAS_COV,W_H2O_MEAS_COV,W_CH4_MEAS_COV,W_N2O_MEAS_COV,W_T_SONIC_COV_IBROM,W_T_SONIC_COV_IBROM_N1626,W_T_SONIC_COV_IBROM_N0614,W_T_SONIC_COV_IBROM_N0277,W_T_SONIC_COV_IBROM_N0133,W_T_SONIC_COV_IBROM_N0065,W_T_SONIC_COV_IBROM_N0032,W_T_SONIC_COV_IBROM_N0016,W_T_SONIC_COV_IBROM_N0008,W_T_SONIC_COV_IBROM_N0004,W_NUM_SPIKES,WD_FILTER_NREX,W_SPIKE_NREX,W_ABSLIM_NREX,W_VM97_TEST,W_LGD,W_KID,W_ZCD,W_ITC,W_ITC_TEST,WBOOST_APPLIED,WPL_APPLIED,ZL,ZL_UNCORR
TIMESTAMP_MIDDLE,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2023-11-07 15:45:00,0.024459,1.18057,1191.96,1009.65,0.0,1.0,-0.104503,0.0,47.4806,8.91186,547.0,0.5,20.0,30.0,NaN,2.03,NaN,NaN,113.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-13.0,-4.5,-3.0,600.0,10.0,10.0,NaN,-13.0,-4.5,-3.0,600.0,10.0,10.0,NaN,-13.0,-4.5,-3.0,600.0,10.0,10.0,36000.0,NaN,33907.0,NaN,NaN,NaN,NaN,0.0,0.004084,2056.92,2040.39,NaN,NaN,NaN,NaN,NaN,1.5,1.5,1.5,1.2,1.8,NaN,2.04999,NaN,2.03928,NaN,2.06459,NaN,0.026416,NaN,1.687580,NaN,6.45396,NaN,NaN,NaN,-0.000007,NaN,0.0,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,800000111.0,NaN,1.45,NaN,4.71668,NaN,17104.0,33.0,0.504881,2.04037,0.334208,47.4481,0.95,3.0,311.646,311.666,94.5797,1.17462,0.024659,0.0,0.0,0.34,36000.0,0.004106,0.001208,0.002920,0.002920,0.002920,1.40623,0.057478,0.0,NaN,36000.0,NaN,33907.0,33907.0,NaN,0.063369,-18.73130,-0.069361,NaN,0.018644,9.77577,0.205045,NaN,5.674690e-14,1.433520e-11,2.348090e-12,22.4901,-3.41295,7.72011,19.2242,29.3181,41.1190,49.2089,61.6038,NaN,0.045063,-11.009500,-0.064029,NaN,0.045063,-11.009500,-0.064029,NaN,0.045063,-11.009500,-0.064029,NaN,NaN,NaN,NaN,1.40623,1.70137,1.08328,NaN,0.057478,0.008068,0.022674,NaN,0.783730,1.911990,0.549682,NaN,2.0,27.0,133.0,NaN,1.0,2.0,6.0,NaN,0.0,0.0,2.0,0.0,360.0,33907.0,33907.0,-0.296263,0.405821,1.0,16.1673,8.14275,8.07698,1.65,1.65,1.65,1.4,3.0,8.04152,7.95401,8.12923,0.133112,-0.185823,3.06162,0.000752,-0.000031,-0.168951,-0.168951,-0.288637,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.02642,0.0,0.0,0.0,0.0,800000001.0,1.6,5.08671,17100.0,0.039091,3.728430,143.0,6.0,2.0,11.0,NaN,4.445,4.445,4.445,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9999.0,9999.0,NaN,NaN,NaN,33907.0,2.834980,0.834096,2.016010,2.016010,2.016010,1.40623,0.057478,0.0,NaN,NaN,NaN,271.667,3372.8100,5811.7200,NaN,0.499588,0.499588,0.499588,NaN,NaN,NaN,NaN,NaN,0.0,33907.0,0.0,0.000669,336.921,334.212,1.4,1.4,1.4,1.0,1.8,0.336843,0.335467,0.338169,0.002384,0.408973,4.36558,0.0,0.0,0.0,0.0,800000011.0,1.35,7.12347,17107.0,7.0,6.0,95.3500,5.28834,95.3500,134.556000,75.2000,46.1374,1.78762,NaN,0.08,0.02,NaN,0.1,0.1,0.1,75.2000,267.16400,33907.0,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,0.005040,2482680.0,NaN,NaN,NaN,0.0,4.0,65.666700,2.023111e+11,33907.0,33907.0,-0.061388,0.007171,0.600401,-0.001090,14.1285,7.36667,3.23349,14.12,14.09,14.16,0.063338,0.648345,4.81246,-0.060675,-0.061388,-0.061388,44.6260,1.01174,86.0,169.0,0.0,801000111.0,0.0,18.30680,15470.0,0.021502,0.376819,1.0,245.0,1.0,6.0,0.0,1.0,7.36667,1.645400,2.37570,0.228032,2.30049,1.84719,2.83140,0.765680,0.425654,3.02780,0.226705,8.0,12.0,0.0,800000000.0,0.0,7.76702,14.0,15.0,2.0,1.712060,2.566390e-14,0.005951,7.70346,10.24400,2.54050,0.005066,-0.003421,-0.515508,0.449916,0.735135,0.263470,3.28923,39.0,72.0,0.0,800000000.0,80100.0,80100.0,80.0,81.0,0.0,7.59743,131.0,12.5,NaN,28.0,28.0,28.0,33907.0,0.074109,3.509980e-15,2.37570,5.24356,247.240,19.3050,-0.005830,-0.159624,0.156614,0.272238,0.066080,4.66270,-0.046808,-0.000142,NaN,0.001102,-0.000271,-1.578860e-06,-0.000054,-0.000120,-0.000217,-0.000328,-0.000442,-0.000537,-0.000600,-0.000638,-0.000628,-0.000544,8.0,0.0,11.0,0.0,800000000.0,0.0,7.55335,14.0,19.0,2.0,0.0,0.0,0.000501,0.000291
2023-11-07 16:15:00,0.024448,1.18107,1192.57,1009.74,0.0,1.0,-1.155120,0.0,47.4806,8.91186,547.0,0.5,20.0,30.0,NaN,2.03,NaN,NaN,113.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-13.0,-4.5,-3.0,600.0,10.0,10.0,NaN,-13.0,-4.5,-3.0,600.0,10.0,10.0,NaN,-13.0,-4.5,-3.0,600.0,10.0,10.0,36000.0,NaN,36000.0,NaN,NaN,NaN,NaN,0.0,0.003884,2055.97,2039.08,NaN,NaN,NaN,NaN,NaN,1.5,1.5,1.5,1.2,1.8,NaN,2.05119,NaN,2.04456,NaN,2.05971,NaN,0.020089,NaN,2.319250,NaN,9.74080,NaN,NaN,NaN,0.000002,NaN,0.0,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,800001111.0,NaN,1.45,NaN,6.11444,NaN,18125.0,33.0,0.503889,2.03904,0.334307,47.4801,0.95,3.0,311.666,311.687,94.5875,1.17499,0.024651,0.0,0.0,0.34,36000.0,0.006952,0.002756,0.005066,0.005066,0.005066,1.37231,0.000905,1.0,NaN,36000.0,NaN,36000.0,36000.0,NaN,0.107283,-4.30116,0.320649,NaN,0.042537,5.25593,0.124789,NaN,5.047570e-14,1.249410e-11,2.048420e-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.078177,-2.669360,0.295447,NaN,0.078177,-2.669360,0.295447,NaN,0.078177,-2.669360,0.295447,NaN,NaN,NaN,NaN,1.37231,1.61131,1.08530,NaN,0.000905,0.007448,0.002244,NaN,0.770812,0.582154,0.588735,NaN,52.0,90.0,4.0,NaN,4.0,5.0,1.0,NaN,1.0,1.0,0.0,0.0,360.0,36000.0,36000.0,-5.544480,0.514667,1.0,15.6927,8.30620,8.23778,1.65,1.65,1.65,1.4,3.0,8.20683,8.10983,8.31355,0.151473,0.321722,2.95509,0.001039,0.000025,-5.203780,-5.203780,-5.398500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.02704,1.0,0.0,2.0,0.0,800000000.0,1.6,4.80733,18122.0,0.016272,0.980613,4.0,1.0,0.0,11.0,NaN,4.445,4.445,4.445,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9999.0,9999.0,NaN,NaN,NaN,36000.0,4.799900,1.903140,3.497670,3.497670,3.497670,1.37231,0.000905,1.0,NaN,NaN,NaN,309.667,96.1322,100.5720,NaN,0.524944,0.524944,0.524944,NaN,NaN,NaN,NaN,NaN,0.0,36000.0,0.0,0.000637,337.077,334.308,1.4,1.4,1.4,1.0,1.8,0.337155,0.335836,0.338301,0.001698,-0.066421,2.56853,0.0,0.0,0.0,0.0,800000011.0,1.35,5.52639,18130.0,7.0,6.0,95.3733,5.04337,95.3733,54.595100,77.0667,49.4614,2.04700,NaN,0.08,0.02,NaN,0.1,0.1,0.1,77.0667,168.35800,36000.0,-0.089664,0.326971,0.000474,NaN,0.007308,-0.059239,0.004324,0.005141,2482830.0,NaN,NaN,NaN,0.0,4.0,27.333300,2.023111e+11,36000.0,36000.0,-0.040387,0.005945,0.565629,-0.025142,14.0625,7.30000,3.51602,14.07,14.03,14.10,0.050827,-0.293210,2.87542,-0.039899,-0.040387,-0.040387,45.2873,1.01225,8.0,16.0,0.0,801000011.0,0.0,9.08786,17153.0,0.035920,1.232820,0.0,44.0,1.0,3.0,1.0,1.0,7.30000,1.310570,2.01768,0.184921,1.99414,1.41907,2.58162,0.788707,0.211800,2.51568,0.183799,5.0,9.0,0.0,800000000.0,0.0,12.23850,31.0,41.0,3.0,1.532390,-4.584680e-14,0.006072,7.85875,10.19730,2.33859,0.005168,-0.021533,-0.460614,0.466410,0.663861,0.120429,3.57962,19.0,31.0,0.0,800000000.0,80101.0,80101.0,80.0,80.0,0.0,8.10957,235.0,12.5,NaN,28.0,28.0,28.0,36000.0,0.072070,3.216510e-15,2.01768,5.17510,243.374,21.2881,0.007512,-0.142191,0.154485,0.261699,-0.258009,5.00192,-0.031525,-0.004364,NaN,0.001911,-0.000066,7.283030e-06,-0.004330,-0.004202,-0.004004,-0.003727,-0.003373,-0.002928,-0.002393,-0.001825,-0.001300,-0.000878,2.0,0.0,4.0,0.0,800000101.0,0.0,8.81569,31.0,7.0,1.0,0.0,0.0,0.017580,0.016804
2023-11-07 16:45:00,0.024430,1.18176,1193.50,1009.93,0.0,1.0,-0.448918,0.0,47.4806,8.91186,547.0,0.5,20.0,30.0,NaN,2.03,NaN,NaN,113.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-13.0,-4.5,-3.0,600.0,10.0,10.0,NaN,-13.0,-4.5,-3.0,600.0,10.0,10.0,NaN,-13.0,-4.5,-3.0,600.0,10.0,10.0,36000.0,NaN,36000.0,NaN,NaN,NaN,NaN,0.0,0.003867,2081.52,2063.72,NaN,NaN,NaN,NaN,NaN,1.5,1.5,1.5,1.2,1.8,NaN,2.06325,NaN,2.04954,NaN,2.09248,NaN,0.052240,NaN,2.183620,NaN,7.94592,NaN,NaN,NaN,0.000004,NaN,1.0,0.0,NaN,0.0,NaN,2.0,NaN,0.0,NaN,800001111.0,NaN,1.45,NaN,6.42937,NaN,18130.0,33.0,0.504000,2.06370,0.334381,47.5030,0.95,3.0,311.687,311.708,94.5768,1.17542,0.024642,0.0,0.0,0.34,36000.0,0.006427,0.002405,0.004766,0.004766,0.004766,1.34830,0.017514,0.0,NaN,36000.0,NaN,36000.0,36000.0,NaN,0.099175,5.72280,0.050173,NaN,0.037119,19.08020,0.106846,NaN,-9.569960e-14,-2.298740e-11,-3.724630e-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.073555,3.782120,0.045517,NaN,0.073555,3.782120,0.045517,NaN,0.073555,3.782120,0.045517,NaN,NaN,NaN,NaN,1.34830,1.51312,1.10231,NaN,0.017514,0.016181,0.008255,NaN,1.010460,1.043610,1.675790,NaN,9.0,141.0,0.0,NaN,1.0,6.0,1.0,NaN,0.0,2.0,0.0,0.0,360.0,36000.0,36000.0,-1.992170,0.999846,1.0,16.0983,8.66599,8.59154,1.65,1.65,1.65,1.4,3.0,8.53993,8.43511,8.66410,0.164651,0.327461,2.81337,0.000791,0.000042,-1.753860,-1.753860,-1.945100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.02420,0.0,0.0,0.0,0.0,800000000.0,1.6,4.79605,18127.0,0.049171,1.684960,43.0,3.0,1.0,11.0,NaN,4.445,4.445,4.445,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9999.0,9999.0,NaN,NaN,NaN,36000.0,4.437720,1.660950,3.291330,3.291330,3.291330,1.34830,0.017514,0.0,NaN,NaN,NaN,337.333,272.0260,303.8440,NaN,0.533691,0.533691,0.533691,NaN,NaN,NaN,NaN,NaN,1.0,36000.0,0.0,0.000627,337.267,334.382,1.4,1.4,1.4,1.0,1.8,0.337298,0.335819,0.338690,0.001892,0.018583,2.42516,0.0,0.0,0.0,0.0,800000011.0,1.35,5.48256,18135.0,7.0,6.0,95.3967,4.96230,95.3967,11.485700,81.1333,32.9954,2.41931,NaN,0.08,0.02,NaN,0.1,0.1,0.1,81.1333,61.77900,36000.0,-0.179467,0.719942,0.001043,NaN,0.016089,1.120350,0.003377,0.005363,2483150.0,NaN,NaN,NaN,0.0,4.0,6.666670,2.023111e+11,36000.0,36000.0,-0.040854,0.007455,0.576129,-0.008977,13.9995,7.16667,4.11689,14.05,13.99,14.10,0.173610,-2.074720,6.40439,-0.040400,-0.040854,-0.040854,45.3890,1.01125,15.0,30.0,0.0,800000111.0,0.0,15.71570,17749.0,0.039154,1.977710,13.0,225.0,1.0,6.0,1.0,1.0,7.16667,1.299840,1.55119,0.185932,1.42476,0.99706,1.91482,0.780558,1.091680,4.33767,0.184895,1.0,2.0,0.0,800000000.0,0.0,12.02880,69.0,39.0,3.0,0.843979,-6.718370e-14,0.006337,8.19824,10.10470,1.90641,0.005391,-0.029499,-0.355619,0.290065,0.702736,0.088211,6.12003,3.0,4.0,0.0,800000100.0,80100.0,80100.0,80.0,81.0,0.0,12.47370,303.0,12.5,NaN,28.0,28.0,28.0,36000.0,0.065479,-5.944700e-15,1.55119,5.08381,262.811,22.5450,0.005028,-0.117357,0.121096,0.221694,-0.210290,6.81205,-0.031297,-0.001470,NaN,0.001797,0.000093,1.121610e-06,-0.002660,-0.002590,-0.002490,-0.002349,-0.002160,-0.001926,-0.001665,-0.001389,-0.001065,-0.000709,3.0,0.0,7.0,0.0,800000101.0,0.0,11.90360,69.0,21.0,2.0,0.0,0.0,0.006213,0.005562

# Remove vars with zero records

In [4]:
stats = df.describe().T

In [5]:
# Find available variables that have more than 0 records, remove all others from data
available_vars = stats.loc[stats['count'] > 0].index
not_available_vars = stats.loc[stats['count'] == 0].index
print("No records for the following vars:")
print(stats.loc[not_available_vars])

No records for the following vars:
                                       count  mean  std  min  25%  50%  75%  max
BADM_INST_MODEL_SA                       0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
BADM_INST_SA_WIND_FORMAT                 0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
BADM_INST_SA_GILL_ALIGN                  0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
BADM_INST_MODEL_GA_CO2                   0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
BADM_INSTPAIR_NORTHWARD_SEP_GA_CO2       0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
BADM_INSTPAIR_EASTWARD_SEP_GA_CO2        0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
BADM_INSTPAIR_HEIGHT_SEP_GA_CO2          0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
BADM_INST_GA_CP_TUBE_LENGTH_GA_CO2       0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
BADM_INST_GA_CP_TUBE_IN_DIAM_GA_CO2      0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
BADM_INST_GA_CP_TUBE_FLOW_RATE_GA_CO2    0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
BADM_INST_MODEL_GA_H2O                   0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
BADM_INST_MODEL_GA_CH4                   0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
BADM_INST_MODEL_GA_N2O                   0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CO2_NR                                   0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CO2_MEAS_TYPE                            0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CO2_MOLAR_DENSITY                        0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CO2_MIXING_RATIO                         0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CO2                                      0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CO2_TLAG_ACTUAL                          0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CO2_TLAG_USED                            0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CO2_TLAG_NOMINAL                         0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CO2_TLAG_MIN                             0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CO2_TLAG_MAX                             0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CO2_MEAS_MEDIAN                          0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CO2_MEAS_P25                             0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CO2_MEAS_P75                             0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CO2_MEAS_SIGMA                           0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CO2_MEAS_SKW                             0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CO2_MEAS_KUR                             0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CO2_MEAS_H2O_MEAS_COV                    0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CO2_MEAS_CH4_MEAS_COV                    0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CO2_MEAS_N2O_MEAS_COV                    0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CO2_NUM_SPIKES                           0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CO2_DIAG_NREX                            0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CO2_SPIKE_NREX                           0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CO2_ABSLIM_NREX                          0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CO2_VM97_TEST                            0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CO2_LGD                                  0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CO2_KID                                  0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CO2_ZCD                                  0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FILENAME_HF                              0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FC_NR                                    0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FC                                       0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FC_RANDUNC_HF                            0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FC_VADV                                  0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FC_UNCORR                                0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FC_STAGE1                                0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FC_STAGE2                                0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FH2O_CELL_CO2                            0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FH2O_CELL_CH4                            0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FH2O_CELL_N2O                            0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FC_SCF                                   0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FC_CORRDIFF                              0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FC_NSR                                   0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FC_SS                                    0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FC_SS_TEST                               0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FC_SSITC_TEST                            0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
H_CELL_CO2                               0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
H_CELL_H2O                               0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
H_CELL_CH4                               0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
H_CELL_N2O                               0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
H_BU_BOT                                 0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
H_BU_TOP                                 0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
H_BU_SPAR                                0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
HPATH_GA_CO2                             0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7200_HEAD_DETECT                  0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7200_T_OUT                        0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7200_T_IN                         0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7200_AUX_IN                       0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7200_DELTA_P                      0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7200_CHOPPER                      0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7200_DETECTOR                     0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7200_PLL                          0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7200_SYNC                         0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7500_CHOPPER                      0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7500_DETECTOR                     0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7500_PLL                          0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7500_SYNC                         0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7700_NOT_READY                    0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7700_NO_SIGNAL                    0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7700_RE_UNLOCKED                  0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7700_BAD_TEMP                     0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7700_LASER_T_UNREG                0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7700_BLOCK_T_UNREG                0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7700_MOTOR_SPINNING               0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7700_PUMP_ON                      0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7700_TOP_HEATER_ON                0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7700_BOTTOM_HEATER_ON             0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7700_CALIBRATING                  0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7700_MOTOR_FAILURE                0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7700_BAD_AUX_TC1                  0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7700_BAD_AUX_TC2                  0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7700_BAD_AUX_TC3                  0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7700_BOX_CONNECTED                0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7700_RSSI                         0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
KRYPTON_HYDRO_KH2O_GA_H2O                0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
KRYPTON_HYDRO_KO2_GA_H2O                 0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
LOGGER_SWVER_MAJOR                       0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
LOGGER_SWVER_MINOR                       0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
LOGGER_SWVER_REVISION                    0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
MV_AIR_CELL_CO2                          0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
MANUFACTURER_SA                          0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
MANUFACTURER_GA_CO2                      0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
MANUFACTURER_GA_H2O                      0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
MANUFACTURER_GA_CH4                      0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
MANUFACTURER_GA_N2O                      0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
ROT_ROLL                                 0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
RESPONSE_TIME_GA_CO2                     0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
SC_SINGLE                                0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
SPEC_CORR_LI7700_A                       0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
SPEC_CORR_LI7700_B                       0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
SPEC_CORR_LI7700_C                       0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
VPATH_GA_CO2                             0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
W_CO2_MEAS_COV                           0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN

In [6]:
print("Removing variables with 0 records ...")
df_available = df[available_vars].copy()

print(f"Variables removed:")
df_not_available = df[not_available_vars].copy()
_list = df_not_available.columns.tolist()
for c in _list:
    print(c, end=" ")

Removing variables with 0 records ...
Variables removed:
BADM_INST_MODEL_SA BADM_INST_SA_WIND_FORMAT BADM_INST_SA_GILL_ALIGN BADM_INST_MODEL_GA_CO2 BADM_INSTPAIR_NORTHWARD_SEP_GA_CO2 BADM_INSTPAIR_EASTWARD_SEP_GA_CO2 BADM_INSTPAIR_HEIGHT_SEP_GA_CO2 BADM_INST_GA_CP_TUBE_LENGTH_GA_CO2 BADM_INST_GA_CP_TUBE_IN_DIAM_GA_CO2 BADM_INST_GA_CP_TUBE_FLOW_RATE_GA_CO2 BADM_INST_MODEL_GA_H2O BADM_INST_MODEL_GA_CH4 BADM_INST_MODEL_GA_N2O CO2_NR CO2_MEAS_TYPE CO2_MOLAR_DENSITY CO2_MIXING_RATIO CO2 CO2_TLAG_ACTUAL CO2_TLAG_USED CO2_TLAG_NOMINAL CO2_TLAG_MIN CO2_TLAG_MAX CO2_MEAS_MEDIAN CO2_MEAS_P25 CO2_MEAS_P75 CO2_MEAS_SIGMA CO2_MEAS_SKW CO2_MEAS_KUR CO2_MEAS_H2O_MEAS_COV CO2_MEAS_CH4_MEAS_COV CO2_MEAS_N2O_MEAS_COV CO2_NUM_SPIKES CO2_DIAG_NREX CO2_SPIKE_NREX CO2_ABSLIM_NREX CO2_VM97_TEST CO2_LGD CO2_KID CO2_ZCD FILENAME_HF FC_NR FC FC_RANDUNC_HF FC_VADV FC_UNCORR FC_STAGE1 FC_STAGE2 FH2O_CELL_CO2 FH2O_CELL_CH4 FH2O_CELL_N2O FC_SCF FC_CORRDIFF FC_NSR FC_SS FC_SS_TEST FC_SSITC_TEST H_CELL_CO2 H_CELL_H2O H_CELL_CH4 H_CELL_N2O H_BU_BOT H_BU_TOP H_BU_SPAR HPATH_GA_CO2 INST_LI7200_HEAD_DETECT INST_LI7200_T_OUT INST_LI7200_T_IN INST_LI7200_AUX_IN INST_LI7200_DELTA_P INST_LI7200_CHOPPER INST_LI7200_DETECTOR INST_LI7200_PLL INST_LI7200_SYNC INST_LI7500_CHOPPER INST_LI7500_DETECTOR INST_LI7500_PLL INST_LI7500_SYNC INST_LI7700_NOT_READY INST_LI7700_NO_SIGNAL INST_LI7700_RE_UNLOCKED INST_LI7700_BAD_TEMP INST_LI7700_LASER_T_UNREG INST_LI7700_BLOCK_T_UNREG INST_LI7700_MOTOR_SPINNING INST_LI7700_PUMP_ON INST_LI7700_TOP_HEATER_ON INST_LI7700_BOTTOM_HEATER_ON INST_LI7700_CALIBRATING INST_LI7700_MOTOR_FAILURE INST_LI7700_BAD_AUX_TC1 INST_LI7700_BAD_AUX_TC2 INST_LI7700_BAD_AUX_TC3 INST_LI7700_BOX_CONNECTED INST_LI7700_RSSI KRYPTON_HYDRO_KH2O_GA_H2O KRYPTON_HYDRO_KO2_GA_H2O LOGGER_SWVER_MAJOR LOGGER_SWVER_MINOR LOGGER_SWVER_REVISION MV_AIR_CELL_CO2 MANUFACTURER_SA MANUFACTURER_GA_CO2 MANUFACTURER_GA_H2O MANUFACTURER_GA_CH4 MANUFACTURER_GA_N2O ROT_ROLL RESPONSE_TIME_GA_CO2 SC_SINGLE SPEC_CORR_LI7700_A SPEC_CORR_LI7700_B SPEC_CORR_LI7700_C VPATH_GA_CO2 W_CO2_MEAS_COV

# Remove meteo variables from EC L1 output

In [7]:
removecols = [v for v in df_available if str(v).endswith("_1_1_1")]
print("The following variables will be removed from EC results:")
print(removecols)

The following variables will be removed from EC results:
['LW_IN_1_1_1', 'PA_1_1_1', 'PPFD_IN_1_1_1', 'RH_1_1_1', 'SW_IN_1_1_1', 'TA_1_1_1']

In [8]:
# Remove meteo data from flux results because this meteo has gaps after flux processing
keepcols = []
[keepcols.append(c) for c in df_available.columns if "_1_1_1" not in c]
df_reduced = df_available[keepcols].copy()
df_reduced

,AIR_MV,AIR_DENSITY,AIR_RHO_CP,AIR_CP,AOA_METHOD,AXES_ROTATION_METHOD,BOWEN,BURBA_METHOD,BADM_LOCATION_LAT,BADM_LOCATION_LONG,BADM_LOCATION_ELEV,BADM_HEIGHTC,BADM_INST_SAMPLING_INT,BADM_INST_AVERAGING_INT,BADM_INST_HEIGHT_SA,BADM_SA_OFFSET_NORTH,BADM_INSTPAIR_NORTHWARD_SEP_GA_H2O,BADM_INSTPAIR_EASTWARD_SEP_GA_H2O,BADM_INSTPAIR_HEIGHT_SEP_GA_H2O,BADM_INST_GA_CP_TUBE_LENGTH_GA_H2O,BADM_INST_GA_CP_TUBE_IN_DIAM_GA_H2O,BADM_INST_GA_CP_TUBE_FLOW_RATE_GA_H2O,BADM_INSTPAIR_NORTHWARD_SEP_GA_CH4,BADM_INSTPAIR_EASTWARD_SEP_GA_CH4,BADM_INSTPAIR_HEIGHT_SEP_GA_CH4,BADM_INST_GA_CP_TUBE_LENGTH_GA_CH4,BADM_INST_GA_CP_TUBE_IN_DIAM_GA_CH4,BADM_INST_GA_CP_TUBE_FLOW_RATE_GA_CH4,BADM_INSTPAIR_NORTHWARD_SEP_GA_N2O,BADM_INSTPAIR_EASTWARD_SEP_GA_N2O,BADM_INSTPAIR_HEIGHT_SEP_GA_N2O,BADM_INST_GA_CP_TUBE_LENGTH_GA_N2O,BADM_INST_GA_CP_TUBE_IN_DIAM_GA_N2O,BADM_INST_GA_CP_TUBE_FLOW_RATE_GA_N2O,CUSTOM_FILTER_NR,CH4_NR,CH4_MEAS_TYPE,CH4_MOLAR_DENSITY,CH4_MIXING_RATIO,CH4,CH4_TLAG_ACTUAL,CH4_TLAG_USED,CH4_TLAG_NOMINAL,CH4_TLAG_MIN,CH4_TLAG_MAX,CH4_MEAS_MEDIAN,CH4_MEAS_P25,CH4_MEAS_P75,CH4_MEAS_SIGMA,CH4_MEAS_SKW,CH4_MEAS_KUR,CH4_MEAS_N2O_MEAS_COV,CH4_NUM_SPIKES,CUSTOM_FILTER_NREX,CH4_DIAG_NREX,CH4_SPIKE_NREX,CH4_ABSLIM_NREX,CH4_VM97_TEST,CH4_LGD,CH4_KID,CH4_ZCD,CUSTOM_DATA_SIZE_LGR_MEAN,CUSTOM_STATUS_CODE_LGR_MEAN,CUSTOM_CH4_MEAN,CUSTOM_N2O_MEAN,CUSTOM_T_UNKNOWN_MEAN,CUSTOM_MIRROR_RINGDOWNTIME_MEAN,CUSTOM_FIT_FLAG_MEAN,DOY_START,DOY_END,DRYAIR_PARTIAL_PRESSURE,DRYAIR_DENSITY,DRYAIR_MV,DETRENDING_METHOD,DENTRENDING_TIME_CONSTANT,DISPLACEMENT_HEIGHT,EXPECT_NR,ET,ET_RANDUNC_HF,ET_UNCORR,ET_STAGE1,ET_STAGE2,ET_SCF,ET_CORRDIFF,ET_SSITC_TEST,FILE_NR,FCH4_NR,FN2O_NR,FH2O,FCH4,FN2O,FH2O_RANDUNC_HF,FCH4_RANDUNC_HF,FN2O_RANDUNC_HF,FH2O_VADV,FCH4_VADV,FN2O_VADV,FETCH_MAX,FETCH_OFFSET,FETCH_10,FETCH_30,FETCH_50,FETCH_70,FETCH_80,FETCH_90,FH2O_UNCORR,FCH4_UNCORR,FN2O_UNCORR,FH2O_STAGE1,FCH4_STAGE1,FN2O_STAGE1,FH2O_STAGE2,FCH4_STAGE2,FN2O_STAGE2,FH2O_SCF,FCH4_SCF,FN2O_SCF,FH2O_CORRDIFF,FCH4_CORRDIFF,FN2O_CORRDIFF,FH2O_NSR,FCH4_NSR,FN2O_NSR,FH2O_SS,FCH4_SS,FN2O_SS,FH2O_SS_TEST,FCH4_SS_TEST,FN2O_SS_TEST,FH2O_SSITC_TEST,FCH4_SSITC_TEST,FN2O_SSITC_TEST,FOOTPRINT_MODEL,FILE_TIME_DURATION,H2O_NR,H_NR,H,H_RANDUNC_HF,H2O_MEAS_TYPE,H2O_MOLAR_DENSITY,H2O_MIXING_RATIO,H2O,H2O_TLAG_ACTUAL,H2O_TLAG_USED,H2O_TLAG_NOMINAL,H2O_TLAG_MIN,H2O_TLAG_MAX,H2O_MEAS_MEDIAN,H2O_MEAS_P25,H2O_MEAS_P75,H2O_MEAS_SIGMA,H2O_MEAS_SKW,H2O_MEAS_KUR,H2O_MEAS_CH4_MEAS_COV,H2O_MEAS_N2O_MEAS_COV,H_UNCORR,H_STAGE1,H_STAGE2,H_SCF,H2O_NUM_SPIKES,H2O_DIAG_NREX,H2O_SPIKE_NREX,H2O_ABSLIM_NREX,H2O_VM97_TEST,H2O_LGD,H2O_KID,H2O_ZCD,H_CORRDIFF,H_NSR,H_SS,H_SS_TEST,H_SSITC_TEST,HPATH_SA,HPATH_GA_H2O,HPATH_GA_CH4,HPATH_GA_N2O,INST_LI7200_AGC_OR_RSSI,INST_LI7500_AGC_OR_RSSI,LE_NR,LE,LE_RANDUNC_HF,LE_UNCORR,LE_STAGE1,LE_STAGE2,LE_SCF,LE_CORRDIFF,LE_SSITC_TEST,MO_LENGTH,MO_LENGTH_UNCORR,MV_AIR_CELL_H2O,MV_AIR_CELL_CH4,MV_AIR_CELL_N2O,NIGHT,N2O_NR,N2O_MEAS_TYPE,N2O_MOLAR_DENSITY,N2O_MIXING_RATIO,N2O,N2O_TLAG_ACTUAL,N2O_TLAG_USED,N2O_TLAG_NOMINAL,N2O_TLAG_MIN,N2O_TLAG_MAX,N2O_MEAS_MEDIAN,N2O_MEAS_P25,N2O_MEAS_P75,N2O_MEAS_SIGMA,N2O_MEAS_SKW,N2O_MEAS_KUR,N2O_NUM_SPIKES,N2O_DIAG_NREX,N2O_SPIKE_NREX,N2O_ABSLIM_NREX,N2O_VM97_TEST,N2O_LGD,N2O_KID,N2O_ZCD,NUM_CUSTOM_VARS,NUM_BIOMET_VARS,PA_EP,PA_CELL,RH_EP,ROT_YAW,ROT_PITCH,ROUGHNESS_LENGTH,RESPONSE_TIME_SA,RESPONSE_TIME_GA_H2O,RESPONSE_TIME_GA_CH4,RESPONSE_TIME_GA_N2O,SW_IN_POT,SONIC_NR,SH_SINGLE,SLE_SINGLE,SET_SINGLE,SH2O_SINGLE,SCH4_SINGLE,SN2O_SINGLE,SPECIFIC_HUMIDITY,SPECIFIC_HEAT_EVAP,SONIC_DIAG_NREX,SPECTRAL_CORRECTION_METHOD,TIMESTAMP_START,T_SONIC_NR,TAU_NR,TAU,TAU_RANDUNC_HF,TKE,TSTAR,T_SONIC,TA_EP,TDEW,T_SONIC_MEDIAN,T_SONIC_P25,T_SONIC_P75,T_SONIC_SIGMA,T_SONIC_SKW,T_SONIC_KUR,TAU_UNCORR,TAU_STAGE1,TAU_STAGE2,T_CELL,TAU_SCF,T_SONIC_NUM_SPIKES,T_SONIC_SPIKE_NREX,T_SONIC_ABSLIM_NREX,T_SONIC_VM97_TEST,T_SONIC_LGD,T_SONIC_KID,T_SONIC_ZCD,TAU_CORRDIFF,TAU_NSR,TAU_SS,T_SONIC_ITC,TAU_SS_TEST,T_SONIC_ITC_TEST,TAU_SSITC_TEST,TIMELAG_DETECTION_METHOD,U_UNROT,U,USTAR,U_MEDIAN,U_P25,U_P75,U_SIGMA,U_SKW,U_KUR,USTAR_UNCORR,U_NUM_SPIKES,U_SPIKE_NREX,U_ABSLIM_NREX,U_VM97_TEST,U_LGD,U_KID,U_ZCD,U_ITC,U_ITC_TEST,V_UNROT,V,VAPOR_DENSITY,VAPOR_PARTIAL_PRESSURE,VAPOR_PARTIAL_PRESSURE_SAT,VPD_EP,VAPOR_DRYAIR_RATIO,V_MEDIAN,V_P25,V_P75,V_SIGMA,V_SKW,V_KUR,V_NUM_SPIKES,V_SPIKE_NREX,V_ABSLIM_NREX,V_VM97_TEST,VM97_TLAG_HF,VM97_TLAG_SF,VM97_AOA_HF,VM97_NSHW_HF,V_LGD,V_KID,V_ZCD,VPATH_SA,VPATH_GA_H2O,VPATH_GA_CH4,VPATH_GA_N2O,WD_FILTER_NR,W_UNROT,W,WS,WS_MAX,WD,WD_SIGMA,W_MEDIAN,W_P25,W_P75,W_SIGMA,W_SKW,W_KUR,W_U_COV,W_T_SONIC_COV,W_H2O_MEAS_COV,W_CH4_MEAS_COV,W_N2O_MEAS_COV,W_T_SONIC_COV_IBROM,W_T_SONIC_COV_IBROM_N1626,W_T_SONIC_COV_IBROM_N0614,W_T_SONIC_COV_IBROM_N0277,W_T_SONIC_COV_IBROM_N0133,W_T_SONIC_COV_IBROM_N0065,W_T_SONIC_COV_IBROM_N0032,W_T_SONIC_COV_IBROM_N0016,W_T_SONIC_COV_IBROM_N0008,W_T_SONIC_COV_IBROM_N0004,W_NUM_SPIKES,WD_FILTER_NREX,W_SPIKE_NREX,W_ABSLIM_NREX,W_VM97_TEST,W_LGD,W_KID,W_ZCD,W_ITC,W_ITC_TEST,WBOOST_APPLIED,WPL_APPLIED,ZL,ZL_UNCORR
TIMESTAMP_MIDDLE,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2023-11-07 15:45:00,0.024459,1.18057,1191.96,1009.65,0.0,1.0,-0.104503,0.0,47.4806,8.91186,547.0,0.5,20.0,30.0,2.03,113.0,-13.0,-4.5,-3.0,600.0,10.0,10.0,-13.0,-4.5,-3.0,600.0,10.0,10.0,-13.0,-4.5,-3.0,600.0,10.0,10.0,36000.0,33907.0,0.0,0.004084,2056.92,2040.39,1.5,1.5,1.5,1.2,1.8,2.04999,2.03928,2.06459,0.026416,1.687580,6.45396,-0.000007,0.0,0.0,0.0,0.0,0.0,800000111.0,1.45,4.71668,17104.0,33.0,0.504881,2.04037,0.334208,47.4481,0.95,3.0,311.646,311.666,94.5797,1.17462,0.024659,0.0,0.0,0.34,36000.0,0.004106,0.001208,0.002920,0.002920,0.002920,1.40623,0.057478,0.0,36000.0,33907.0,33907.0,0.063369,-18.73130,-0.069361,0.018644,9.77577,0.205045,5.674690e-14,1.433520e-11,2.348090e-12,22.4901,-3.41295,7.72011,19.2242,29.3181,41.1190,49.2089,61.6038,0.045063,-11.009500,-0.064029,0.045063,-11.009500,-0.064029,0.045063,-11.009500,-0.064029,1.40623,1.70137,1.08328,0.057478,0.008068,0.022674,0.783730,1.911990,0.549682,2.0,27.0,133.0,1.0,2.0,6.0,0.0,0.0,2.0,0.0,360.0,33907.0,33907.0,-0.296263,0.405821,1.0,16.1673,8.14275,8.07698,1.65,1.65,1.65,1.4,3.0,8.04152,7.95401,8.12923,0.133112,-0.185823,3.06162,0.000752,-0.000031,-0.168951,-0.168951,-0.288637,1.02642,0.0,0.0,0.0,0.0,800000001.0,1.6,5.08671,17100.0,0.039091,3.728430,143.0,6.0,2.0,11.0,4.445,4.445,4.445,9999.0,9999.0,33907.0,2.834980,0.834096,2.016010,2.016010,2.016010,1.40623,0.057478,0.0,3372.8100,5811.7200,0.499588,0.499588,0.499588,0.0,33907.0,0.0,0.000669,336.921,334.212,1.4,1.4,1.4,1.0,1.8,0.336843,0.335467,0.338169,0.002384,0.408973,4.36558,0.0,0.0,0.0,0.0,800000011.0,1.35,7.12347,17107.0,7.0,6.0,95.3500,5.28834,75.2000,46.1374,1.78762,0.08,0.02,0.1,0.1,0.1,267.16400,33907.0,NaN,NaN,0.000000,NaN,NaN,NaN,0.005040,2482680.0,0.0,4.0,2.023111e+11,33907.0,33907.0,-0.061388,0.007171,0.600401,-0.001090,14.1285,7.36667,3.23349,14.12,14.09,14.16,0.063338,0.648345,4.81246,-0.060675,-0.061388,-0.061388,44.6260,1.01174,86.0,169.0,0.0,801000111.0,0.0,18.30680,15470.0,0.021502,0.376819,1.0,245.0,1.0,6.0,0.0,1.0,1.645400,2.37570,0.228032,2.30049,1.84719,2.83140,0.765680,0.425654,3.02780,0.226705,8.0,12.0,0.0,800000000.0,0.0,7.76702,14.0,15.0,2.0,1.712060,2.566390e-14,0.005951,7.70346,10.24400,2.54050,0.005066,-0.003421,-0.515508,0.449916,0.735135,0.263470,3.28923,39.0,72.0,0.0,800000000.0,80100.0,80100.0,80.0,81.0,0.0,7.59743,131.0,12.5,28.0,28.0,28.0,33907.0,0.074109,3.509980e-15,2.37570,5.24356,247.240,19.3050,-0.005830,-0.159624,0.156614,0.272238,0.066080,4.66270,-0.046808,-0.000142,0.001102,-0.000271,-1.578860e-06,-0.000054,-0.000120,-0.000217,-0.000328,-0.000442,-0.000537,-0.000600,-0.000638,-0.000628,-0.000544,8.0,0.0,11.0,0.0,800000000.0,0.0,7.55335,14.0,19.0,2.0,0.0,0.0,0.000501,0.000291
2023-11-07 16:15:00,0.024448,1.18107,1192.57,1009.74,0.0,1.0,-1.155120,0.0,47.4806,8.91186,547.0,0.5,20.0,30.0,2.03,113.0,-13.0,-4.5,-3.0,600.0,10.0,10.0,-13.0,-4.5,-3.0,600.0,10.0,10.0,-13.0,-4.5,-3.0,600.0,10.0,10.0,36000.0,36000.0,0.0,0.003884,2055.97,2039.08,1.5,1.5,1.5,1.2,1.8,2.05119,2.04456,2.05971,0.020089,2.319250,9.74080,0.000002,0.0,0.0,0.0,0.0,0.0,800001111.0,1.45,6.11444,18125.0,33.0,0.503889,2.03904,0.334307,47.4801,0.95,3.0,311.666,311.687,94.5875,1.17499,0.024651,0.0,0.0,0.34,36000.0,0.006952,0.002756,0.005066,0.005066,0.005066,1.37231,0.000905,1.0,36000.0,36000.0,36000.0,0.107283,-4.30116,0.320649,0.042537,5.25593,0.124789,5.047570e-14,1.249410e-11,2.048420e-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.078177,-2.669360,0.295447,0.078177,-2.669360,0.295447,0.078177,-2.669360,0.295447,1.37231,1.61131,1.08530,0.000905,0.007448,0.002244,0.770812,0.582154,0.588735,52.0,90.0,4.0,4.0,5.0,1.0,1.0,1.0,0.0,0.0,360.0,36000.0,36000.0,-5.544480,0.514667,1.0,15.6927,8.30620,8.23778,1.65,1.65,1.65,1.4,3.0,8.20683,8.10983,8.31355,0.151473,0.321722,2.95509,0.001039,0.000025,-5.203780,-5.203780,-5.398500,1.02704,1.0,0.0,2.0,0.0,800000000.0,1.6,4.80733,18122.0,0.016272,0.980613,4.0,1.0,0.0,11.0,4.445,4.445,4.445,9999.0,9999.0,36000.0,4.799900,1.903140,3.497670,3.497670,3.497670,1.37231,0.000905,1.0,96.1322,100.5720,0.524944,0.524944,0.524944,0.0,36000.0,0.0,0.000637,337.077,334.308,1.4,1.4,1.4,1.0,1.8,0.337155,0.335836,0.338301,0.001698,-0.066421,2.56853,0.0,0.0,0.0,0.0,800000011.0,1.35,5.52639,18130.0,7.0,6.0,95.3733,5.04337,77.0667,49.4614,2.04700,0.08,0.02,0.1,0.1,0.1,168.35800,36000.0,-0.089664,0.326971,0.000474,0.007308,-0.059239,0.004324,0.005141,2482830.0,0.0,4.0,2.023111e+11,36000.0,36000.0,-0.040387,0.005945,0.565629,-0.025142,14.0625,7.30000,3.51602,14.07,14.03,14.10,0.050827,-0.293210,2.87542,-0.039899,-0.040387,-0.040387,45.2873,1.01225,8.0,16.0,0.0,801000011.0,0.0,9.08786,17153.0,0.035920,1.232820,0.0,44.0,1.0,3.0,1.0,1.0,1.310570,2.01768,0.184921,1.99414,1.41907,2.58162,0.788707,0.211800,2.51568,0.183799,5.0,9.0,0.0,800000000.0,0.0,12.23850,31.0,41.0,3.0,1.532390,-4.584680e-14,0.006072,7.85875,10.19730,2.33859,0.005168,-0.021533,-0.460614,0.466410,0.663861,0.120429,3.57962,19.0,31.0,0.0,800000000.0,80101.0,80101.0,80.0,80.0,0.0,8.10957,235.0,12.5,28.0,28.0,28.0,36000.0,0.072070,3.216510e-15,2.01768,5.17510,243.374,21.2881,0.007512,-0.142191,0.154485,0.261699,-0.258009,5.00192,-0.031525,-0.004364,0.001911,-0.000066,7.283030e-06,-0.004330,-0.004202,-0.004004,-0.003727,-0.003373,-0.002928,-0.002393,-0.001825,-0.001300,-0.000878,2.0,0.0,4.0,0.0,800000101.0,0.0,8.81569,31.0,7.0,1.0,0.0,0.0,0.017580,0.016804
2023-11-07 16:45:00,0.024430,1.18176,1193.50,1009.93,0.0,1.0,-0.448918,0.0,47.4806,8.91186,547.0,0.5,20.0,30.0,2.03,113.0,-13.0,-4.5,-3.0,600.0,10.0,10.0,-13.0,-4.5,-3.0,600.0,10.0,10.0,-13.0,-4.5,-3.0,600.0,10.0,10.0,36000.0,36000.0,0.0,0.003867,2081.52,2063.72,1.5,1.5,1.5,1.2,1.8,2.06325,2.04954,2.09248,0.052240,2.183620,7.94592,0.000004,1.0,0.0,0.0,2.0,0.0,800001111.0,1.45,6.42937,18130.0,33.0,0.504000,2.06370,0.334381,47.5030,0.95,3.0,311.687,311.708,94.5768,1.17542,0.024642,0.0,0.0,0.34,36000.0,0.006427,0.002405,0.004766,0.004766,0.004766,1.34830,0.017514,0.0,36000.0,36000.0,36000.0,0.099175,5.72280,0.050173,0.037119,19.08020,0.106846,-9.569960e-14,-2.298740e-11,-3.724630e-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.073555,3.782120,0.045517,0.073555,3.782120,0.045517,0.073555,3.782120,0.045517,1.34830,1.51312,1.10231,0.017514,0.016181,0.008255,1.010460,1.043610,1.675790,9.0,141.0,0.0,1.0,6.0,1.0,0.0,2.0,0.0,0.0,360.0,36000.0,36000.0,-1.992170,0.999846,1.0,16.0983,8.66599,8.59154,1.65,1.65,1.65,1.4,3.0,8.53993,8.43511,8.66410,0.164651,0.327461,2.81337,0.000791,0.000042,-1.753860,-1.753860,-1.945100,1.02420,0.0,0.0,0.0,0.0,800000000.0,1.6,4.79605,18127.0,0.049171,1.684960,43.0,3.0,1.0,11.0,4.445,4.445,4.445,9999.0,9999.0,36000.0,4.437720,1.660950,3.291330,3.291330,3.291330,1.34830,0.017514,0.0,272.0260,303.8440,0.533691,0.533691,0.533691,1.0,36000.0,0.0,0.000627,337.267,334.382,1.4,1.4,1.4,1.0,1.8,0.337298,0.335819,0.338690,0.001892,0.018583,2.42516,0.0,0.0,0.0,0.0,800000011.0,1.35,5.48256,18135.0,7.0,6.0,95.3967,4.96230,81.1333,32.9954,2.41931,0.08,0.02,0.1,0.1,0.1,61.77900,36000.0,-0.179467,0.719942,0.001043,0.016089,1.120350,0.003377,0.005363,2483150.0,0.0,4.0,2.023111e+11,36000.0,36000.0,-0.040854,0.007455,0.576129,-0.008977,13.9995,7.16667,4.11689,14.05,13.99,14.10,0.173610,-2.074720,6.40439,-0.040400,-0.040854,-0.040854,45.3890,1.01125,15.0,30.0,0.0,800000111.0,0.0,15.71570,17749.0,0.039154,1.977710,13.0,225.0,1.0,6.0,1.0,1.0,1.299840,1.55119,0.185932,1.42476,0.99706,1.91482,0.780558,1.091680,4.33767,0.184895,1.0,2.0,0.0,800000000.0,0.0,12.02880,69.0,39.0,3.0,0.843979,-6.718370e-14,0.006337,8.19824,10.10470,1.90641,0.005391,-0.029499,-0.355619,0.290065,0.702736,0.088211,6.12003,3.0,4.0,0.0,800000100.0,80100.0,80100.0,80.0,81.0,0.0,12.47370,303.0,12.5,28.0,28.0,28.0,36000.0,0.065479,-5.944700e-15,1.55119,5.08381,262.811,22.5450,0.005028,-0.117357,0.121096,0.221694,-0.210290,6.81205,-0.031297,-0.001470,0.001797,0.000093,1.121610e-06,-0.002660,-0.002590,-0.002490,-0.002349,-0.002160,-0.001926,-0.001665,-0.001389,-0.001065,-0.000709,3.0,0.0,7.0,0.0,800000101.0,0.0,11.90360,69.0,21.0,2.0,0.0,0.0,0.006213,0.005562
2023-11-07 17:15:00,0.024377,1.18428,1196.09,1009.97,0.0,1.0,8.085210,0.0,47.4806,8.91186,547.0,0.5,20.0,30.0,2.03,113.0,-13.0,-4.5,-3.0,600.0,10.0,10.0,-13.0,-4.5,-3.0,600.0,10.0,10.0,-13.0,-4.5,-3.0,600.0,10.0,10.0,36000.0,36000.0,0.0,0.003695,2045.08,2027.43,1.5,1.5,1.5,1.2,1.8,2.04560,2.03914,2.05119,0.009691,-0.263145,3.72225,0.000004,0.0,0.0,0.0,0.0,0.0,800000011.0,1.45,6.72507,18144.0,33.0,0.504417,2.02747,0.334332,47.4707,0.95,3.0,311.708,311.729,94.5823,1.17787,0.024591,0.0,0.0,0.34,36000.0,-0.001940,0.001714,-0.001291,-0.001291,-0.001291,1.50281,0.002309,1.0,36000.0,36000.0,36000.0,-0.029932,4.14253,0.342042,0.026457,2.23130,0.264532,-2.854460e-14,-6.672570e-12,-1.100350e-12,18.5076,-2.80860,6.35307,15.8200,24.1266,33.8379,40.4953,50.6953,-0.019917,2.381070,0.325037,-0.019917,2.381070,0.325037,-0.019917,2.381070,0.325037,1.50281,1.73977,1.05232,0.002309,0.006065,0.011929,1.231780,1.322290,0.563663,74.0,17.0,5.0,4.0,2.0,1.0,1.0,0.0,0.0,0.0,360.0,36000.0,36000.0,-10.834700,1.494270,1.0,15.8055,8.74907,8.67319,1.65,1.65,1.65,1.4,3.0,8.60609,8.50513,8.74663,0.166733,0.424628,2.65943,0.000367,0.000043,-10.600500,-10.600500,-10.518300,1.03008,6.0,0.0,14.0,0.0,800000000.0,1.6,4.90681,18134.0,0.020398,1.837270,3.0,1.0,0.0,11.0,4.445,4.445,4.445,9999.0,9999.0,36000.0,-1.340070,1.184500,-0.891709,-0.891709,-0.891709,1.50281,0.002309,1.0,103.3060,103.5110,0.548743,0.548743,0.548743,1.0,36000.0,0.0,0.000609,337.247,334.336,1.4,1.4,1.4,1.0,1.8,0.337167,0.335518,0.338883,0.002270,0.177837,2.74611,0.0,0.0,0.0,0.0,800000011.0,1.35,5.31566,18145.0,7.0,6.0,95.4100,4.82708,85.1667,69.4138,2.33996,0.08,0.02,0.1,0.1,0.1,3.38364,36000.0,-0.764389,0.166612,0.000241,0.003721,-1.653730,-0.002079,0.005414,2484490.0,0.0,4.0,2.023111e+11,36000.0,36000.0,-0.066396,0.008170,0.801651,-0.038257,13.2112,6.60000,4.25367,13.21,13.14,13.28,0.119839,0.244437,3.19968,-0.065522,-0.066396,-0.066396,45.4484,1.01334,8.0,13.0,0.0,800000011.0,0.0,17.66640,15215.0,0.054555,1.392790,0.0,18.0,1.0,2.0,0.0,1.0,0.955768,2.72048,0.236779,2.61725,2.11501,3.23396,0.853786,0.592468,3.73113,0.235215,12.0,19.0,0.0,800000000.0,0.0,6.76029,6.0,24.0,2.0,2.544640,4.458560e-14,0.006411,8.27731,9.71895,1.44164,0.005443,-0.012888,-0.490790,0.534196,0.862834,-0.319424,4.19020,28.0,49.0,0.0,800000000.0,80011.0,80011.0,80.0,81.0,0.0,7.20865,96.0,12.5,28.0,28.0,28.0,36000.0,0.111073,-1.805990e-15,2.72048,7.10203,223.221,17.3483,0.018840,-0.202975,0.226264,0.360373,-0.425796,4.44633,-0.051714,-0.008863,-0.000486,0.000059,7.992870e-06,-0.008348,-0.008106,-0.007725,-0.007200,-0.006509,-0.005634,-0.004639,-0.003703,-0.002888,-0.002163,8.0,0.0,18.0,0.0,800000000.0,0.0,8.91091,6.0,3.0,1.0,0.0,0.0,0.016359,0.016327
2023-11-07 17:45:00,0.024372,1.18448,1196.40,1010.06,0.0,1.0,-15.579600,0.0,47.4806,8.91186,547.0,0.5,20.0,30.0,2.03,113.0,-13.0,-4.5,-3.0,600.0,10.0,10.0,-13.0,-4.5,-3.0,600.0,10.0,10.0,-13.0,-4.5,-3.0,600.0,10.0,10.0,36000.0,36000.0,0.0,0.003692,2046.10,2028.16,1.5,1.5,1.5,1.2,1.8,2.04623,2.03908,2.05339,0.010856,-0.096546,3.15376,0.000007,0.0,0.0,0.0,0.0,0.0,800000011.0,1.45,5.49138,18188.0,33.0,0.505667,2.02817,0.334617,47.4867,0.95,3.0,311.729,311.750,94.5994,1.17794,0.024589,0.0,0.0,0.34,36000.0,0.001010,0.001726,0.000650,0.000650,0.000650,1.55491,0.011907,2.0,36000.0,36000.0,36000.0,0.015586,-9.21018,-0.996599,0.026632,3.26868,0.344428,-1.616070e-13,-3.707860e-11,-6.117520e-12,19.5982,-2.97411,6.72744,16.7523,25.5483,35.8318,42.8816,53.6826,0.010024,-5.123750,-0.952016,0.010024,-5.123750,-0.952016,0.010024,-5.123750,-0.952016,1.55491,1.79755,1.04683,0.011907,0.005033,0.008266,0.639509,1.653120,1.054650,239.0,5.0,11.0,6.0,1.0,1.0,2.0,0.0,0.0,0.0,360.0,36000.0,36000.0,-10.870900,1.200400,1.0,16.0896,8.91856,8.83972,1.65,1.65,1.65,1.4,3.0,8.75585,8.64303,8.88557,0.176458,0.227414,2.75636,0.000358,0.000063,-10.552000,-10.552000,-10.549000,1.03052,2.0,0.0,4.0,0.0,800000000.0,1.6,4.76308,18185.0,0.001114,1.290340,1.0,1.0,0.0,11.0,4.445,4.445,4.445,9999.0,9999.0,36000.0,0.697766,1.192290,0.448751,0.448751,0.448751,1.55491,0.011907,2.0,167.5260,169.1710,0.549407,0.549407,0.549407,1.0,36000.0,0.0,0.000609,337.582,334.622,1.4,1.4,1.4,1.0,1.8,0.337467,0.335813,0.339105,0.002398,0.354056,3.00852,0.0,0.0,0.0,0.0,800000011.0,1.35,5.47986,18194.0,7.0,6.0,95.4433,4.82207,86.6333,72.1923,2.51939,0.08,0.02,0.1,0.1,0.1,0.00000,36000.0,0.044976,0.339909,0.000492,0.007593,0.033121,0.013033,0.005518,2484410.0,0.0,4.0,2.023111e+11,36000.0,36000.0,-0.091847,0.011294,0.902566,-0.032630,13.2558,6.63333,4.53015,13.24,13.19,13.31,0.102951,0.926548,4.88694,-0.090631,-0.091847,-0.091847,45.5032,1.01342,12.0,17.0,0.0,800000011.0,0.0,14.76220,12621.0,0.049471,1.114210,0.0,35.0,1.0,3.0,0.0,1.0,0.912536,2.98675,0.278465,2.87024,2.31425,3.56926,0.932995,0.542603,3.20374,0.276615,13.0,19.0,0.0,800000000.0,0.0,6.48186,0.0,18.0,2.0,2.840900,2.054460e-13,0.006536,8.43919,9.74127,1.30208,0.005549,-0.061476,-0.602705,0.543933,0.882609,0.365205,3.28590,18.0,33.0,0.0,800000000.0,80100.0,80100.0,80.0,80.0,0.0,6.78122,70.0,12.5,28.0,28.0,28.0,36000.0,0.131290,-1.004420e-14,2.98675,7.00917,221.055,16.7315,0.027332,-0.223583,0.246510,0.394530,-0.405291,4.11250,-0.076123,-0.008820,0.000244,-0.000126,-2.340930e-05,-0.009130,-0.008750,-0.008114,-0.007236,-0.006175,-0.004970,-0.003700,-0.002537,-0.001597,-0.000934,6.0,0.0,9.0,0.0,800000000.0,0.0,7.65645,0.0,1.0,1.0,0.0,0.0,0.010088,0.009990

# Save to file

In [9]:
OUTNAME = "32.1_CH-TAN_LGR_Level-1_eddypro_fluxnet"
filepath = save_parquet(filename=OUTNAME, data=df_reduced)
df_reduced.to_csv(f"{OUTNAME}.csv")

Saved file 32.1_CH-TAN_LGR_Level-1_eddypro_fluxnet.parquet (2.528 seconds).

# **End of notebook**.

In [10]:
dt_string = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
print(f"Finished. {dt_string}")

Finished. 2025-08-21 16:47:03