# Calc 3-hour means from preceding records

# Imports

In [1]:
import importlib.metadata
import pandas as pd
import warnings
from datetime import datetime
from pathlib import Path

from diive.core.io.filereader import search_files, MultiDataFileReader
from diive.core.io.files import save_parquet, load_parquet
# pd.options.display.width = None
# pd.options.display.max_columns = None
pd.set_option('display.max_rows', 3000)
pd.set_option('display.max_columns', 3000)
warnings.filterwarnings(action='ignore', category=FutureWarning)
warnings.filterwarnings(action='ignore', category=UserWarning)
dt_string = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
version_diive = importlib.metadata.version("diive")
print(f"diive version: v{version_diive}")

diive version: v0.85.0

# Load data

In [2]:
df = load_parquet(filepath="33.1_CH-OE2_IRGA+LGR+METEO+MGMT_Level-1_eddypro_fluxnet_2021-2023.parquet")
df

Loaded .parquet file 33.1_CH-OE2_IRGA+LGR+METEO+MGMT_Level-1_eddypro_fluxnet_2021-2023.parquet (0.276 seconds).
    --> Detected time resolution of <30 * Minutes> / 30min

,AIR_CP,AIR_DENSITY,AIR_MV,AIR_RHO_CP,AOA_METHOD,AXES_ROTATION_METHOD,BADM_HEIGHTC,BADM_INSTPAIR_EASTWARD_SEP_GA_CH4,BADM_INSTPAIR_EASTWARD_SEP_GA_CO2,BADM_INSTPAIR_EASTWARD_SEP_GA_H2O,BADM_INSTPAIR_EASTWARD_SEP_GA_N2O,BADM_INSTPAIR_HEIGHT_SEP_GA_CH4,BADM_INSTPAIR_HEIGHT_SEP_GA_CO2,BADM_INSTPAIR_HEIGHT_SEP_GA_H2O,BADM_INSTPAIR_HEIGHT_SEP_GA_N2O,BADM_INSTPAIR_NORTHWARD_SEP_GA_CH4,BADM_INSTPAIR_NORTHWARD_SEP_GA_CO2,BADM_INSTPAIR_NORTHWARD_SEP_GA_H2O,BADM_INSTPAIR_NORTHWARD_SEP_GA_N2O,BADM_INST_AVERAGING_INT,BADM_INST_GA_CP_TUBE_FLOW_RATE_GA_CH4,BADM_INST_GA_CP_TUBE_FLOW_RATE_GA_CO2,BADM_INST_GA_CP_TUBE_FLOW_RATE_GA_H2O,BADM_INST_GA_CP_TUBE_FLOW_RATE_GA_N2O,BADM_INST_GA_CP_TUBE_IN_DIAM_GA_CH4,BADM_INST_GA_CP_TUBE_IN_DIAM_GA_CO2,BADM_INST_GA_CP_TUBE_IN_DIAM_GA_H2O,BADM_INST_GA_CP_TUBE_IN_DIAM_GA_N2O,BADM_INST_GA_CP_TUBE_LENGTH_GA_CH4,BADM_INST_GA_CP_TUBE_LENGTH_GA_CO2,BADM_INST_GA_CP_TUBE_LENGTH_GA_H2O,BADM_INST_GA_CP_TUBE_LENGTH_GA_N2O,BADM_INST_HEIGHT_SA,BADM_INST_SAMPLING_INT,BADM_LOCATION_ELEV,BADM_LOCATION_LAT,BADM_LOCATION_LONG,BADM_SA_OFFSET_NORTH,BOWEN,BURBA_METHOD,CH4,CH4_ABSLIM_NREX,CH4_DIAG_NREX,CH4_KID,CH4_LGD,CH4_MEAS_KUR,CH4_MEAS_MEDIAN,CH4_MEAS_N2O_MEAS_COV,CH4_MEAS_P25,CH4_MEAS_P75,CH4_MEAS_SIGMA,CH4_MEAS_SKW,CH4_MEAS_TYPE,CH4_MIXING_RATIO,CH4_MOLAR_DENSITY,CH4_NR,CH4_NUM_SPIKES,CH4_SPIKE_NREX,CH4_TLAG_ACTUAL,CH4_TLAG_MAX,CH4_TLAG_MIN,CH4_TLAG_NOMINAL,CH4_TLAG_USED,CH4_VM97_TEST,CH4_ZCD,CO2,CO2_ABSLIM_NREX,CO2_DIAG_NREX,CO2_KID,CO2_LGD,CO2_MEAS_H2O_MEAS_COV,CO2_MEAS_KUR,CO2_MEAS_MEDIAN,CO2_MEAS_P25,CO2_MEAS_P75,CO2_MEAS_SIGMA,CO2_MEAS_SKW,CO2_MEAS_TYPE,CO2_MIXING_RATIO,CO2_MOLAR_DENSITY,CO2_NR,CO2_NUM_SPIKES,CO2_SPIKE_NREX,CO2_TLAG_ACTUAL,CO2_TLAG_MAX,CO2_TLAG_MIN,CO2_TLAG_NOMINAL,CO2_TLAG_USED,CO2_VM97_TEST,CO2_ZCD,CUSTOM_AIR_P_MEAN,CUSTOM_CH4_MEAN,CUSTOM_CO2_MEAN,CUSTOM_COOLER_V_MEAN,CUSTOM_DATA_SIZE_IRGA72_MEAN,CUSTOM_DATA_SIZE_LGR_MEAN,CUSTOM_FILTER_NR,CUSTOM_FILTER_NREX,CUSTOM_FIT_FLAG_MEAN,CUSTOM_FLOWRATE_MEAN,CUSTOM_GA_DIAG_CODE_IRGA72_MEAN,CUSTOM_H2O_MEAN,CUSTOM_MIRROR_RINGDOWNTIME_MEAN,CUSTOM_N2O_MEAN,CUSTOM_SIGNAL_STRENGTH_IRGA72_MEAN,CUSTOM_STATUS_CODE_IRGA72_MEAN,CUSTOM_STATUS_CODE_LGR_MEAN,CUSTOM_T_UNKNOWN_MEAN,DENTRENDING_TIME_CONSTANT,DETRENDING_METHOD,DISPLACEMENT_HEIGHT,DOY_END,DOY_START,DRYAIR_DENSITY,DRYAIR_MV,DRYAIR_PARTIAL_PRESSURE,ET,ET_CORRDIFF,ET_RANDUNC_HF,ET_SCF,ET_SSITC_TEST,ET_STAGE1,ET_STAGE2,ET_UNCORR,EXPECT_NR,FC,FCH4,FCH4_CORRDIFF,FCH4_NR,FCH4_NSR,FCH4_RANDUNC_HF,FCH4_SCF,FCH4_SS,FCH4_SSITC_TEST,FCH4_SS_TEST,FCH4_STAGE1,FCH4_STAGE2,FCH4_UNCORR,FCH4_VADV,FC_CORRDIFF,FC_NR,FC_NSR,FC_RANDUNC_HF,FC_SCF,FC_SS,FC_SSITC_TEST,FC_SS_TEST,FC_STAGE1,FC_STAGE2,FC_UNCORR,FC_VADV,FETCH_10,FETCH_30,FETCH_50,FETCH_70,FETCH_80,FETCH_90,FETCH_MAX,FETCH_OFFSET,FH2O,FH2O_CORRDIFF,FH2O_NSR,FH2O_RANDUNC_HF,FH2O_SCF,FH2O_SS,FH2O_SSITC_TEST,FH2O_SS_TEST,FH2O_STAGE1,FH2O_STAGE2,FH2O_UNCORR,FH2O_VADV,FILE_NR,FILE_TIME_DURATION,FLAG_PPFD_IN_ISFILLED,FLAG_SWC_0.05_gfXG_ISFILLED,FLAG_SWC_0.15_gfXG_ISFILLED,FLAG_SWC_0.3_gfXG_ISFILLED,FLAG_SWC_0.5_gfXG_ISFILLED,FLAG_SW_IN_ISFILLED,FLAG_TA_ISFILLED,FLAG_TS_0.05_gfXG_ISFILLED,FLAG_TS_0.15_gfXG_ISFILLED,FLAG_TS_0.3_gfXG_ISFILLED,FLAG_TS_0.5_gfXG_ISFILLED,FLAG_VPD_ISFILLED,FN2O,FN2O_CORRDIFF,FN2O_NR,FN2O_NSR,FN2O_RANDUNC_HF,FN2O_SCF,FN2O_SS,FN2O_SSITC_TEST,FN2O_SS_TEST,FN2O_STAGE1,FN2O_STAGE2,FN2O_UNCORR,FN2O_VADV,FOOTPRINT_MODEL,H,H2O,H2O_ABSLIM_NREX,H2O_DIAG_NREX,H2O_KID,H2O_LGD,H2O_MEAS_CH4_MEAS_COV,H2O_MEAS_KUR,H2O_MEAS_MEDIAN,H2O_MEAS_N2O_MEAS_COV,H2O_MEAS_P25,H2O_MEAS_P75,H2O_MEAS_SIGMA,H2O_MEAS_SKW,H2O_MEAS_TYPE,H2O_MIXING_RATIO,H2O_MOLAR_DENSITY,H2O_NR,H2O_NUM_SPIKES,H2O_SPIKE_NREX,H2O_TLAG_ACTUAL,H2O_TLAG_MAX,H2O_TLAG_MIN,H2O_TLAG_NOMINAL,H2O_TLAG_USED,H2O_VM97_TEST,H2O_ZCD,HPATH_GA_CH4,HPATH_GA_CO2,HPATH_GA_H2O,HPATH_GA_N2O,HPATH_SA,H_CORRDIFF,H_NR,H_NSR,H_RANDUNC_HF,H_SCF,H_SS,H_SSITC_TEST,H_SS_TEST,H_STAGE1,H_STAGE2,H_UNCORR,INST_LI7200_AGC_OR_RSSI,INST_LI7500_AGC_OR_RSSI,LE,LE_CORRDIFF,LE_NR,LE_RANDUNC_HF,LE_SCF,LE_SSITC_TEST,LE_STAGE1,LE_STAGE2,LE_UNCORR,LW_IN,MGMT_FERT_MIN,MGMT_FERT_ORG,MGMT_HARVEST,MGMT_PESTICIDE_HERBICIDE,MGMT_SOILCULTIVATION,MGMT_SOWING,MO_LENGTH,MO_LENGTH_UNCORR,MV_AIR_CELL_CH4,MV_AIR_CELL_CO2,MV_AIR_CELL_H2O,MV_AIR_CELL_N2O,N2O,N2O_ABSLIM_NREX,N2O_DIAG_NREX,N2O_KID,N2O_LGD,N2O_MEAS_KUR,N2O_MEAS_MEDIAN,N2O_MEAS_P25,N2O_MEAS_P75,N2O_MEAS_SIGMA,N2O_MEAS_SKW,N2O_MEAS_TYPE,N2O_MIXING_RATIO,N2O_MOLAR_DENSITY,N2O_NR,N2O_NUM_SPIKES,N2O_SPIKE_NREX,N2O_TLAG_ACTUAL,N2O_TLAG_MAX,N2O_TLAG_MIN,N2O_TLAG_NOMINAL,N2O_TLAG_USED,N2O_VM97_TEST,N2O_ZCD,NIGHT,NUM_BIOMET_VARS,NUM_CUSTOM_VARS,PA,PA_CELL,PA_EP,PPFD_IN,PREC,RESPONSE_TIME_GA_CH4,RESPONSE_TIME_GA_CO2,RESPONSE_TIME_GA_H2O,RESPONSE_TIME_GA_N2O,RESPONSE_TIME_SA,RH,RH_EP,ROT_PITCH,ROT_YAW,ROUGHNESS_LENGTH,SCH4_SINGLE,SC_SINGLE,SET_SINGLE,SH2O_SINGLE,SH_SINGLE,SLE_SINGLE,SN2O_SINGLE,SONIC_DIAG_NREX,SONIC_NR,SPECIFIC_HEAT_EVAP,SPECIFIC_HUMIDITY,SPECTRAL_CORRECTION_METHOD,SWC_0.05,SWC_0.05_gfXG,SWC_0.15,SWC_0.15_gfXG,SWC_0.3,SWC_0.3_gfXG,SWC_0.5,SWC_0.5_gfXG,SW_IN,SW_IN_POT,TA,TAU,TAU_CORRDIFF,TAU_NR,TAU_NSR,TAU_RANDUNC_HF,TAU_SCF,TAU_SS,TAU_SSITC_TEST,TAU_SS_TEST,TAU_STAGE1,TAU_STAGE2,TAU_UNCORR,TA_EP,TDEW,TIMELAG_DETECTION_METHOD,TIMESINCE_MGMT_FERT_MIN,TIMESINCE_MGMT_FERT_ORG,TIMESINCE_MGMT_HARVEST,TIMESINCE_MGMT_PESTICIDE_HERBICIDE,TIMESINCE_MGMT_SOILCULTIVATION,TIMESINCE_MGMT_SOWING,TIMESINCE_PREC,TIMESTAMP_START,TKE,TSTAR,TS_0.05,TS_0.05_gfXG,TS_0.15,TS_0.15_gfXG,TS_0.3,TS_0.3_gfXG,TS_0.5,TS_0.5_gfXG,T_CELL,T_SONIC,T_SONIC_ABSLIM_NREX,T_SONIC_ITC,T_SONIC_ITC_TEST,T_SONIC_KID,T_SONIC_KUR,T_SONIC_LGD,T_SONIC_MEDIAN,T_SONIC_NR,T_SONIC_NUM_SPIKES,T_SONIC_P25,T_SONIC_P75,T_SONIC_SIGMA,T_SONIC_SKW,T_SONIC_SPIKE_NREX,T_SONIC_VM97_TEST,T_SONIC_ZCD,U,USTAR,USTAR_UNCORR,U_ABSLIM_NREX,U_ITC,U_ITC_TEST,U_KID,U_KUR,U_LGD,U_MEDIAN,U_NUM_SPIKES,U_P25,U_P75,U_SIGMA,U_SKW,U_SPIKE_NREX,U_UNROT,U_VM97_TEST,U_ZCD,V,VAPOR_DENSITY,VAPOR_DRYAIR_RATIO,VAPOR_PARTIAL_PRESSURE,VAPOR_PARTIAL_PRESSURE_SAT,VM97_AOA_HF,VM97_NSHW_HF,VM97_TLAG_HF,VM97_TLAG_SF,VPATH_GA_CH4,VPATH_GA_CO2,VPATH_GA_H2O,VPATH_GA_N2O,VPATH_SA,VPD,VPD_EP,V_ABSLIM_NREX,V_KID,V_KUR,V_LGD,V_MEDIAN,V_NUM_SPIKES,V_P25,V_P75,V_SIGMA,V_SKW,V_SPIKE_NREX,V_UNROT,V_VM97_TEST,V_ZCD,W,WBOOST_APPLIED,WD,WD_FILTER_NR,WD_FILTER_NREX,WD_SIGMA,WPL_APPLIED,WS,WS_MAX,W_ABSLIM_NREX,W_CH4_MEAS_COV,W_CO2_MEAS_COV,W_H2O_MEAS_COV,W_ITC,W_ITC_TEST,W_KID,W_KUR,W_LGD,W_MEDIAN,W_N2O_MEAS_COV,W_NUM_SPIKES,W_P25,W_P75,W_SIGMA,W_SKW,W_SPIKE_NREX,W_T_SONIC_COV,W_T_SONIC_COV_IBROM,W_T_SONIC_COV_IBROM_N0004,W_T_SONIC_COV_IBROM_N0008,W_T_SONIC_COV_IBROM_N0016,W_T_SONIC_COV_IBROM_N0032,W_T_SONIC_COV_IBROM_N0065,W_T_SONIC_COV_IBROM_N0133,W_T_SONIC_COV_IBROM_N0277,W_T_SONIC_COV_IBROM_N0614,W_T_SONIC_COV_IBROM_N1626,W_UNROT,W_U_COV,W_VM97_TEST,W_ZCD,ZL,ZL_UNCORR
TIMESTAMP_MIDDLE,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2021-01-01 00:15:00,1008.65,1.20907,0.023898,1219.53,0.0,1.0,0.5,NaN,-2.5,-2.5,NaN,NaN,-17.0,-17.0,NaN,NaN,-2.5,-2.5,NaN,30.0,NaN,11.7783,11.7783,NaN,NaN,9.5,9.5,NaN,NaN,100.0,100.0,NaN,2.15,20.0,452.0,47.2864,7.73375,335.0,198.29000,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,448.159,0.0,0.0,28.84690,0.85,0.003781,3.91360,450.793,449.259,452.255,2.422590,0.634627,0.0,450.911,18.5244,35988.0,0.0,0.0,0.90,1.0,0.80,0.9,0.90,801000000.0,1577.0,95040.3,NaN,18.5866,1.87907,26.0,NaN,36000.0,0.0,NaN,0.000196,8191.0,253.143,NaN,NaN,100.05,0.0,NaN,NaN,0.0,0.0,0.34,1.0208,1.0000,1.20421,0.024053,94.4498,0.000009,0.013312,0.000038,1.33443,2.0,0.000007,0.000007,0.000007,36000.0,0.922521,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.006129,35988.0,3.263230,0.197057,1.01378,5.0,1.0,1.0,0.909977,0.909977,0.909977,-7.637670e-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000143,0.013312,1.181690,0.000584,1.33443,408.0,2.0,7.0,0.000107,0.000107,0.000107,-1.100050e-12,36000.0,360.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.27770,6.45479,0.0,0.0,3.10544,4.65,NaN,4.06288,6.139,NaN,6.137,6.143,0.005918,1.330050,0.0,6.49673,266.805,35988.0,3.0,3.0,4.70,5.0,0.90,1.05,4.70,801000011.0,8971.0,NaN,1.27,1.27,NaN,11.0,0.028809,36000.0,1.237880,0.088537,1.03957,30.0,1.0,2.0,1.23188,1.22907,1.23188,9999.0,9999.0,0.006444,0.013312,35988.0,0.026294,1.33443,2.0,0.004829,0.004829,0.004829,330.090577,0.0,0.0,0.0,0.0,0.0,0.0,-4.37718,-4.27653,NaN,0.024193,0.024193,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,6.0,9.0,95063.620000,94.4774,95.0636,0.0,0.4,NaN,0.1,0.1,NaN,0.02,99.997990,99.9980,2.098600,281.807,0.08,NaN,0.155503,-0.000086,-0.001326,-0.089267,-0.059738,NaN,0.0,36000.0,2499900.0,0.004026,4.0,42.786436,42.786436,41.951085,41.951085,39.873900,39.873900,39.600397,39.600397,0.0,0.0,0.098506,-0.001985,0.048913,36000.0,1.11706,0.000066,1.04066,5.0,1.0,1.0,-0.001985,-0.001985,-0.001908,0.098506,0.062529,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,2.021010e+11,0.023903,0.025856,2.396667,2.396667,3.395555,3.395555,3.337778,3.337778,4.452778,4.452778,1.76981,7.33580,0.0,691.0,8.0,3.19453,2.22821,0.0,7.28920,36000.0,17.0,7.155750,7.52289,0.249531,0.386567,17.0,801000011.0,112.0,0.158682,0.040521,0.039721,0.0,24.0,3.0,4.97020,2.99828,0.0,0.094403,15.0,0.028565,0.275450,0.184184,0.935370,15.0,0.032448,800000011.0,34.0,4.638030e-14,0.004867,0.004042,6.13780,6.13793,80.0,81.0,81000.0,81000.0,NaN,12.7,12.7,NaN,12.5,0.000012,0.000123,0.0,3.49713,2.79584,0.0,-0.012756,19.0,-0.082513,0.073461,0.109418,0.461707,19.0,-0.155220,800000011.0,178.0,-4.123030e-15,0.0,231.809,36000.0,0.0,59.4423,0.0,0.158682,0.743505,0.0,NaN,0.021888,0.000003,31.0,3.0,3.67096,4.18347,0.0,-0.001596,NaN,1.0,-0.023436,0.025835,0.043699,0.158666,1.0,0.001010,0.001276,0.000162,0.000244,0.000294,0.000326,0.000353,0.000384,0.000434,0.000526,0.000724,0.005811,-0.001009,801000011.0,34.0,-0.413508,-0.423241
2021-01-01 00:45:00,1008.64,1.20915,0.023896,1219.60,0.0,1.0,0.5,NaN,-2.5,-2.5,NaN,NaN,-17.0,-17.0,NaN,NaN,-2.5,-2.5,NaN,30.0,NaN,11.7908,11.7908,NaN,NaN,9.5,9.5,NaN,NaN,100.0,100.0,NaN,2.15,20.0,452.0,47.2864,7.73375,335.0,-20.67160,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,449.720,0.0,0.0,17.53220,0.85,0.017422,2.32802,452.134,449.314,455.037,3.908650,0.388416,0.0,452.474,18.5931,35989.0,1.0,1.0,0.90,1.0,0.80,0.9,0.90,801000000.0,1504.0,95042.1,NaN,18.6483,1.87668,26.0,NaN,36000.0,0.0,NaN,0.000197,8191.0,252.444,NaN,NaN,100.05,0.0,NaN,NaN,0.0,0.0,0.34,1.0416,1.0208,1.20428,0.024051,94.4517,-0.000203,0.065003,0.000082,2.34567,2.0,-0.000087,-0.000087,-0.000087,36000.0,0.970468,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.035704,35989.0,1.950340,0.315160,1.02242,33.0,1.0,3.0,0.949188,0.949188,0.949188,-3.884230e-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.003138,0.065003,0.993613,0.001263,2.34567,128.0,2.0,6.0,-0.001338,-0.001338,-0.001338,-5.570190e-13,36000.0,360.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,2.92216,6.44924,0.0,0.0,3.14046,1.65,NaN,2.10053,6.127,NaN,6.112,6.134,0.013174,0.045356,0.0,6.49110,266.635,35989.0,7.0,7.0,1.70,5.0,0.90,1.05,1.70,801000011.0,9061.0,NaN,1.27,1.27,NaN,11.0,0.066467,36000.0,1.872970,0.382685,1.02321,70.0,1.0,4.0,2.85824,2.85586,2.85824,9999.0,9999.0,-0.141361,0.065003,35989.0,0.056892,2.34567,2.0,-0.060265,-0.060265,-0.060265,325.793407,0.0,0.0,0.0,0.0,0.0,0.0,-18.41790,-18.39100,NaN,0.024188,0.024188,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,6.0,9.0,95064.982000,94.4424,95.0650,0.0,0.7,NaN,0.1,0.1,NaN,0.02,99.997990,99.9980,0.363879,283.671,0.08,NaN,0.071847,-0.000017,-0.000256,-0.016987,-0.011518,NaN,0.0,36000.0,2499930.0,0.004022,4.0,42.800190,42.800190,41.960116,41.960116,39.878056,39.878056,39.601892,39.601892,0.0,0.0,0.086844,-0.008982,0.079022,36000.0,2.00655,0.000486,1.01584,7.0,1.0,1.0,-0.008982,-0.008982,-0.008842,0.086844,0.050868,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,2.021010e+11,0.077329,0.027799,2.375000,2.375000,3.398889,3.398889,3.350556,3.350556,4.453333,4.453333,1.60617,8.00703,0.0,1106.0,9.0,3.38202,2.95849,0.0,7.85941,36000.0,4.0,7.591020,8.42541,0.590424,0.687110,4.0,800000011.0,16.0,0.655490,0.086189,0.085514,0.0,2.0,3.0,5.17170,2.83405,0.0,0.656914,10.0,0.475025,0.831839,0.280930,0.060744,10.0,0.154925,800000011.0,9.0,1.084410e-13,0.004863,0.004038,6.13261,6.13273,80.0,81.0,81100.0,81100.0,NaN,12.7,12.7,NaN,12.5,0.000012,0.000123,0.0,3.99285,2.38602,0.0,0.001043,3.0,-0.174280,0.210804,0.264676,-0.292127,4.0,-0.636905,800000001.0,83.0,-2.089070e-15,0.0,228.742,36000.0,0.0,29.8282,0.0,0.655490,1.653450,0.0,NaN,0.022829,-0.000032,48.0,3.0,3.57046,3.95580,0.0,-0.002488,NaN,1.0,-0.045645,0.045695,0.075390,-0.009142,1.0,0.002344,0.001284,0.000004,-0.000159,-0.000238,-0.000266,-0.000281,-0.000292,-0.000270,-0.000167,0.000133,0.004163,-0.007112,800000011.0,9.0,-0.098274,-0.098418
2021-01-01 01:15:00,1008.64,1.20925,0.023894,1219.70,0.0,1.0,0.5,NaN,-2.5,-2.5,NaN,NaN,-17.0,-17.0,NaN,NaN,-2.5,-2.5,NaN,30.0,NaN,11.7763,11.7763,NaN,NaN,9.5,9.5,NaN,NaN,100.0,100.0,NaN,2.15,20.0,452.0,47.2864,7.73375,335.0,30.61000,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,453.663,0.0,0.0,32.70000,0.90,0.000123,3.08086,456.145,454.997,457.630,1.890770,0.680794,0.0,456.440,18.7770,35989.0,0.0,0.0,0.95,1.0,0.80,0.9,0.95,801000000.0,1556.0,95049.3,NaN,18.8248,1.87243,26.0,NaN,36000.0,0.0,NaN,0.000196,8191.0,252.451,NaN,NaN,100.05,0.0,NaN,NaN,0.0,0.0,0.34,1.0624,1.0416,1.20438,0.024049,94.4591,0.000084,0.004569,0.000027,2.04423,1.0,0.000041,0.000041,0.000041,36000.0,0.982344,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.010475,35989.0,1.764920,0.209406,1.02393,0.0,1.0,1.0,0.959390,0.959390,0.959390,7.237310e-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.001298,0.004569,1.497680,0.000421,2.04423,80.0,1.0,5.0,0.000635,0.000635,0.000635,1.028620e-12,36000.0,360.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.78976,6.44779,0.0,0.0,3.12362,3.75,NaN,2.65837,6.121,NaN,6.119,6.123,0.003433,0.395873,0.0,6.48963,266.872,35989.0,6.0,6.0,3.80,5.0,0.90,1.05,3.80,801000011.0,8196.0,NaN,1.27,1.27,NaN,11.0,0.008104,36000.0,1.843310,0.232559,1.02479,129.0,2.0,6.0,1.75171,1.74647,1.75171,9999.0,9999.0,0.058470,0.004569,35989.0,0.018945,2.04423,1.0,0.028602,0.028602,0.028602,323.401640,0.0,0.0,0.0,0.0,0.0,0.0,-26.44370,-26.28800,NaN,0.024161,0.024161,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,6.0,9.0,95072.237667,94.4341,95.0722,0.0,0.8,NaN,0.1,0.1,NaN,0.02,99.997990,99.9980,1.191930,282.264,0.08,NaN,0.181543,-0.000004,-0.000067,-0.002978,-0.003006,NaN,0.0,36000.0,2499930.0,0.004021,4.0,42.806659,42.806659,41.966331,41.966331,39.886638,39.886638,39.608814,39.608814,0.0,0.0,0.084800,-0.008245,0.049492,36000.0,2.38037,0.000168,1.01843,5.0,1.0,1.0,-0.008245,-0.008245,-0.008096,0.084800,0.048824,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,2.021010e+11,0.075519,0.017771,2.353889,2.353889,3.393333,3.393333,3.347778,3.347778,4.452222,4.452222,1.27678,6.89030,0.0,1055.0,9.0,2.90721,3.42541,0.0,6.85753,36000.0,6.0,6.590040,7.12379,0.396014,0.566465,6.0,800000000.0,10.0,0.503220,0.082572,0.081822,0.0,1.0,3.0,2.30668,2.03851,0.0,0.508994,12.0,0.262014,0.727132,0.280148,0.069171,12.0,0.106869,800000011.0,5.0,-1.034570e-15,0.004863,0.004037,6.13170,6.13182,80.0,81.0,80000.0,80000.0,NaN,12.7,12.7,NaN,12.5,0.000012,0.000123,0.0,2.70154,2.25021,0.0,-0.005055,7.0,-0.205766,0.196853,0.257786,0.113740,7.0,-0.491630,800000011.0,43.0,3.854350e-15,0.0,242.593,36000.0,0.0,34.7883,0.0,0.503220,1.369160,0.0,NaN,0.023073,0.000015,44.0,3.0,2.68219,3.87191,0.0,-0.001923,NaN,0.0,-0.048197,0.049156,0.078113,-0.153266,0.0,0.001436,0.002152,-0.000323,-0.000469,-0.000614,-0.000713,-0.000766,-0.000777,-0.000717,-0.000527,-0.000036,0.010468,-0.006118,800000011.0,5.0,-0.068447,-0.068853
2021-01-01 01:45:00,1008.65,1.20925,0.023894,1219.71,0.0,1.0,0.5,NaN,-2.5,-2.5,NaN,NaN,-17.0,-17.0,NaN,NaN,-2.5,-2.5,NaN,30.0,NaN,11.7942,11.7942,NaN,NaN,9.5,9.5,NaN,NaN,100.0,100.0,NaN,2.15,20.0,452.0,47.2864,7.73375,335.0,25.84050,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,453.993,0.0,0.0,17.55270,0.85,-0.001698,2.05668,456.812,455.034,458.446,2.091470,0.076213,0.0,456.774,18.7907,35988.0,0.0,0.0,1.00,1.0,0.80,0.9,0.90,801000000.0,1536.0,95053.6,NaN,18.8407,1.87257,26.0,NaN,36000.0,0.0,NaN,0.000197,8191.0,252.698,NaN,NaN,100.05,0.0,NaN,NaN,0.0,0.0,0.34,1.0833,1.0624,1.20438,0.024049,94.4639,0.000482,0.052998,0.000085,2.02222,1.0,0.000238,0.000238,0.000238,36000.0,-0.007104,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.009468,35988.0,1.130200,0.229838,1.03665,4950.0,2.0,9.0,-0.006853,-0.006853,-0.006853,5.689300e-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.007436,0.052998,1.238730,0.001312,2.02222,85.0,1.0,5.0,0.003677,0.003677,0.003677,8.088250e-13,36000.0,360.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,8.65568,6.45423,0.0,0.0,3.06296,4.55,NaN,1.82183,6.126,NaN,6.119,6.133,0.007605,0.126054,0.0,6.49616,267.140,35988.0,0.0,0.0,4.60,5.0,0.90,1.05,4.60,801000111.0,8026.0,NaN,1.27,1.27,NaN,11.0,0.016507,36000.0,3.804000,0.366398,1.02513,20.0,1.0,2.0,8.47042,8.44348,8.47042,9999.0,9999.0,0.334966,0.052998,35988.0,0.059111,2.02222,1.0,0.165643,0.165643,0.165643,320.772343,0.0,0.0,0.0,0.0,0.0,0.0,-10.09030,-10.02440,NaN,0.024161,0.024161,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,6.0,9.0,95077.748000,94.4397,95.0777,0.0,0.9,NaN,0.1,0.1,NaN,0.02,99.997990,99.9980,2.154560,192.548,0.08,NaN,0.015187,0.000019,0.000297,0.021214,0.013366,NaN,0.0,36000.0,2499900.0,0.004025,4.0,42.808315,42.808315,41.972443,41.972443,39.884507,39.884507,39.597794,39.597794,0.0,0.0,0.099361,-0.012404,0.098808,36000.0,5.57184,0.000161,1.01897,8.0,1.0,1.0,-0.012404,-0.012404,-0.012173,0.099361,0.063384,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,2.021010e+11,0.051881,0.070068,2.313333,2.313333,3.383333,3.383333,3.345000,3.345000,4.451667,4.451667,1.29155,6.99496,0.0,426.0,7.0,3.84390,3.29667,0.0,6.92298,36000.0,23.0,6.622360,7.32276,0.558645,0.567374,24.0,800000001.0,9.0,0.479909,0.101280,0.100333,0.0,30.0,3.0,3.96947,2.42503,0.0,0.491255,16.0,0.301586,0.658679,0.230700,-0.133819,16.0,-0.468116,800000001.0,5.0,-2.999490e-14,0.004868,0.004042,6.13819,6.13831,80.0,81.0,81100.0,81100.0,NaN,12.7,12.7,NaN,12.5,0.000012,0.000123,0.0,2.47016,2.68303,0.0,-0.021757,8.0,-0.147942,0.143128,0.206404,0.321908,8.0,-0.104187,800000001.0,38.0,3.027720e-15,0.0,319.302,36000.0,0.0,31.3349,0.0,0.479909,1.275460,0.0,NaN,-0.000165,0.000088,46.0,3.0,3.60285,3.67925,0.0,-0.002968,NaN,1.0,-0.056091,0.054584,0.089086,0.111879,1.0,0.006945,0.005973,0.001264,0.001431,0.001526,0.001585,0.001627,0.001699,0.001851,0.002170,0.002921,0.018042,-0.009613,800000011.0,5.0,-0.179379,-0.180559

# Testing mean settings to get mean over *preceding* records

In [5]:
# Testing: closed='left' is the correct setting for preceding records
var = 'SWC_0.15_gfXG'
_df = df[[var]].copy()
_df['mean_left'] = _df[var].rolling(window=6, closed='left').mean()
_df['mean_right'] = _df[var].rolling(window=6, closed='right').mean()
display(_df[var].iloc[0:6].mean())
display(_df[var].iloc[1:7].mean())
display(_df.iloc[0:20])

np.float64(41.97574377777778)

np.float64(41.9879035)

                     SWC_0.15_gfXG  mean_left  mean_right
TIMESTAMP_MIDDLE
2021-01-01 00:15:00      41.951085        NaN         NaN
2021-01-01 00:45:00      41.960116        NaN         NaN
2021-01-01 01:15:00      41.966331        NaN         NaN
2021-01-01 01:45:00      41.972443        NaN         NaN
2021-01-01 02:15:00      41.991071        NaN         NaN
2021-01-01 02:45:00      42.013417        NaN   41.975744
2021-01-01 03:15:00      42.024043  41.975744   41.987903
2021-01-01 03:45:00      42.035993  41.987903   42.000550
2021-01-01 04:15:00      42.047588  42.000550   42.014093
2021-01-01 04:45:00      42.049554  42.014093   42.026944
2021-01-01 05:15:00      42.045082  42.026944   42.035946
2021-01-01 05:45:00      42.045821  42.035946   42.041347
2021-01-01 06:15:00      42.066195  42.041347   42.048372
2021-01-01 06:45:00      42.090182  42.048372   42.057404
2021-01-01 07:15:00      42.080377  42.057404   42.062869
2021-01-01 07:45:00      42.090231  42.062869   42.069648
2021-01-01 08:15:00      42.061629  42.069648   42.072406
2021-01-01 08:45:00      42.039875  42.072406   42.071415
2021-01-01 09:15:00      42.015661  42.071415   42.062993
2021-01-01 09:45:00      42.051027  42.062993   42.056467

# Calc 3-hour means from preceding records

In [6]:
[print(c) for c in df.columns if "SWC_" in c];
[print(c) for c in df.columns if "TS_" in c];
[print(c) for c in df.columns if "PREC_" in c];

FLAG_SWC_0.05_gfXG_ISFILLED
FLAG_SWC_0.15_gfXG_ISFILLED
FLAG_SWC_0.3_gfXG_ISFILLED
FLAG_SWC_0.5_gfXG_ISFILLED
SWC_0.05
SWC_0.05_gfXG
SWC_0.15
SWC_0.15_gfXG
SWC_0.3
SWC_0.3_gfXG
SWC_0.5
SWC_0.5_gfXG
FLAG_TS_0.05_gfXG_ISFILLED
FLAG_TS_0.15_gfXG_ISFILLED
FLAG_TS_0.3_gfXG_ISFILLED
FLAG_TS_0.5_gfXG_ISFILLED
TS_0.05
TS_0.05_gfXG
TS_0.15
TS_0.15_gfXG
TS_0.3
TS_0.3_gfXG
TS_0.5
TS_0.5_gfXG

In [8]:
var = ['SWC_0.05_gfXG', 'SWC_0.15_gfXG', 'SWC_0.3_gfXG', 'SWC_0.5_gfXG', 'TS_0.05_gfXG', 'TS_0.15_gfXG', 'TS_0.3_gfXG', 'TS_0.5_gfXG', 'PREC']

for v in var:    
    name_mean = f"{v}_MEAN3H"
    df[name_mean] = df[v].rolling(window=6, closed='left').mean()

In [9]:
for v in var:
    print(f"\nResults for {v}: ")
    display(df[[v, f"{v}_MEAN3H"]].iloc[0:9])

Results for SWC_0.05_gfXG:

                     SWC_0.05_gfXG  SWC_0.05_gfXG_MEAN3H
TIMESTAMP_MIDDLE
2021-01-01 00:15:00      42.786436                   NaN
2021-01-01 00:45:00      42.800190                   NaN
2021-01-01 01:15:00      42.806659                   NaN
2021-01-01 01:45:00      42.808315                   NaN
2021-01-01 02:15:00      42.816295                   NaN
2021-01-01 02:45:00      42.829703                   NaN
2021-01-01 03:15:00      42.831537             42.807933
2021-01-01 03:45:00      42.838665             42.815450
2021-01-01 04:15:00      42.837676             42.821862

Results for SWC_0.15_gfXG:

                     SWC_0.15_gfXG  SWC_0.15_gfXG_MEAN3H
TIMESTAMP_MIDDLE
2021-01-01 00:15:00      41.951085                   NaN
2021-01-01 00:45:00      41.960116                   NaN
2021-01-01 01:15:00      41.966331                   NaN
2021-01-01 01:45:00      41.972443                   NaN
2021-01-01 02:15:00      41.991071                   NaN
2021-01-01 02:45:00      42.013417                   NaN
2021-01-01 03:15:00      42.024043             41.975744
2021-01-01 03:45:00      42.035993             41.987903
2021-01-01 04:15:00      42.047588             42.000550

Results for SWC_0.3_gfXG:

                     SWC_0.3_gfXG  SWC_0.3_gfXG_MEAN3H
TIMESTAMP_MIDDLE
2021-01-01 00:15:00     39.873900                  NaN
2021-01-01 00:45:00     39.878056                  NaN
2021-01-01 01:15:00     39.886638                  NaN
2021-01-01 01:45:00     39.884507                  NaN
2021-01-01 02:15:00     39.893629                  NaN
2021-01-01 02:45:00     39.901603                  NaN
2021-01-01 03:15:00     39.904990            39.886389
2021-01-01 03:45:00     39.905099            39.891570
2021-01-01 04:15:00     39.914051            39.896077

Results for SWC_0.5_gfXG:

                     SWC_0.5_gfXG  SWC_0.5_gfXG_MEAN3H
TIMESTAMP_MIDDLE
2021-01-01 00:15:00     39.600397                  NaN
2021-01-01 00:45:00     39.601892                  NaN
2021-01-01 01:15:00     39.608814                  NaN
2021-01-01 01:45:00     39.597794                  NaN
2021-01-01 02:15:00     39.604877                  NaN
2021-01-01 02:45:00     39.624531                  NaN
2021-01-01 03:15:00     39.623146            39.606384
2021-01-01 03:45:00     39.626301            39.610176
2021-01-01 04:15:00     39.631222            39.614244

Results for TS_0.05_gfXG:

                     TS_0.05_gfXG  TS_0.05_gfXG_MEAN3H
TIMESTAMP_MIDDLE
2021-01-01 00:15:00      2.396667                  NaN
2021-01-01 00:45:00      2.375000                  NaN
2021-01-01 01:15:00      2.353889                  NaN
2021-01-01 01:45:00      2.313333                  NaN
2021-01-01 02:15:00      2.301667                  NaN
2021-01-01 02:45:00      2.298333                  NaN
2021-01-01 03:15:00      2.297778             2.339815
2021-01-01 03:45:00      2.297222             2.323333
2021-01-01 04:15:00      2.293333             2.310370

Results for TS_0.15_gfXG:

                     TS_0.15_gfXG  TS_0.15_gfXG_MEAN3H
TIMESTAMP_MIDDLE
2021-01-01 00:15:00      3.395555                  NaN
2021-01-01 00:45:00      3.398889                  NaN
2021-01-01 01:15:00      3.393333                  NaN
2021-01-01 01:45:00      3.383333                  NaN
2021-01-01 02:15:00      3.376667                  NaN
2021-01-01 02:45:00      3.358333                  NaN
2021-01-01 03:15:00      3.352778             3.384352
2021-01-01 03:45:00      3.337222             3.377222
2021-01-01 04:15:00      3.330000             3.366944

Results for TS_0.3_gfXG:

                     TS_0.3_gfXG  TS_0.3_gfXG_MEAN3H
TIMESTAMP_MIDDLE
2021-01-01 00:15:00     3.337778                 NaN
2021-01-01 00:45:00     3.350556                 NaN
2021-01-01 01:15:00     3.347778                 NaN
2021-01-01 01:45:00     3.345000                 NaN
2021-01-01 02:15:00     3.351111                 NaN
2021-01-01 02:45:00     3.346667                 NaN
2021-01-01 03:15:00     3.343889            3.346482
2021-01-01 03:45:00     3.327222            3.347500
2021-01-01 04:15:00     3.324444            3.343611

Results for TS_0.5_gfXG:

                     TS_0.5_gfXG  TS_0.5_gfXG_MEAN3H
TIMESTAMP_MIDDLE
2021-01-01 00:15:00     4.452778                 NaN
2021-01-01 00:45:00     4.453333                 NaN
2021-01-01 01:15:00     4.452222                 NaN
2021-01-01 01:45:00     4.451667                 NaN
2021-01-01 02:15:00     4.453889                 NaN
2021-01-01 02:45:00     4.459445                 NaN
2021-01-01 03:15:00     4.456667            4.453889
2021-01-01 03:45:00     4.455556            4.454537
2021-01-01 04:15:00     4.451111            4.454907

Results for PREC:

                     PREC  PREC_MEAN3H
TIMESTAMP_MIDDLE
2021-01-01 00:15:00   0.4          NaN
2021-01-01 00:45:00   0.7          NaN
2021-01-01 01:15:00   0.8          NaN
2021-01-01 01:45:00   0.9          NaN
2021-01-01 02:15:00   0.6          NaN
2021-01-01 02:45:00   0.4          NaN
2021-01-01 03:15:00   0.3     0.633333
2021-01-01 03:45:00   0.4     0.616667
2021-01-01 04:15:00   0.2     0.566667

# Save to file

In [12]:
OUTNAME = "33.3_CH-OE2_IRGA+LGR+METEO+MGMT_Level-1_eddypro_fluxnet_2021-2023"
filepath = save_parquet(filename=OUTNAME, data=df)
df.to_csv(f"{OUTNAME}.csv")

Saved file 33.3_CH-OE2_IRGA+LGR+METEO+MGMT_Level-1_eddypro_fluxnet_2021-2023.parquet (1.526 seconds).

# **End of notebook**.

In [13]:
dt_string = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
print(f"Finished. {dt_string}")

Finished. 2025-01-17 15:21:46