# Imports

In [14]:
from pathlib import Path
import pandas as pd
from diive.core.io.files import save_parquet, load_parquet

# Load L3.3 results for NEE, LE and H

In [15]:
nee = load_parquet(filepath=r"../40_FLUX_PROCESSING_CHAIN/NEE/41.1_FluxProcessingChain_L3.2_NEE.parquet")
le = load_parquet(filepath=r"../40_FLUX_PROCESSING_CHAIN/LE/42.1_FluxProcessingChain_L3.2_LE.parquet")
h = load_parquet(filepath=r"../40_FLUX_PROCESSING_CHAIN/H/43.1_FluxProcessingChain_L3.2_H.parquet")
n2o = load_parquet(filepath=r"../40_FLUX_PROCESSING_CHAIN/FN2O/44.1_FluxProcessingChain_L3.2_FN2O.parquet")
ch4 = load_parquet(filepath=r"../40_FLUX_PROCESSING_CHAIN/FCH4/45.1_FluxProcessingChain_L3.2_FCH4.parquet")

Loaded .parquet file ../40_FLUX_PROCESSING_CHAIN/NEE/41.1_FluxProcessingChain_L3.2_NEE.parquet (0.408 seconds).
    --> Detected time resolution of <30 * Minutes> / 30min
Loaded .parquet file ../40_FLUX_PROCESSING_CHAIN/LE/42.1_FluxProcessingChain_L3.2_LE.parquet (0.353 seconds).
    --> Detected time resolution of <30 * Minutes> / 30min
Loaded .parquet file ../40_FLUX_PROCESSING_CHAIN/H/43.1_FluxProcessingChain_L3.2_H.parquet (0.359 seconds).
    --> Detected time resolution of <30 * Minutes> / 30min
Loaded .parquet file ../40_FLUX_PROCESSING_CHAIN/FN2O/44.1_FluxProcessingChain_L3.2_FN2O.parquet (0.329 seconds).
    --> Detected time resolution of <30 * Minutes> / 30min
Loaded .parquet file ../40_FLUX_PROCESSING_CHAIN/FCH4/45.1_FluxProcessingChain_L3.2_FCH4.parquet (0.337 seconds).
    --> Detected time resolution of <30 * Minutes> / 30min

# Load main data

In [16]:
SOURCEDIR = r"../30_MERGE_DATA"
FILENAME = r"33.1_CH-TAN_IRGA+LGR+METEO+MGMT_Level-1_eddypro_fluxnet.parquet"
FILEPATH = Path(SOURCEDIR) / FILENAME
maindf = load_parquet(filepath=FILEPATH)

Loaded .parquet file ..\30_MERGE_DATA\33.1_CH-TAN_IRGA+LGR+METEO+MGMT_Level-1_eddypro_fluxnet.parquet (0.401 seconds).
    --> Detected time resolution of <30 * Minutes> / 30min

## Add results for NEE

In [17]:
newcols = [c for c in nee.columns if c not in maindf]
print("NEW VARIABLES FROM FLUX PROCESSING CHAIN:")
[print(f"++ {c}") for c in newcols]
maindf = pd.concat([maindf, nee[newcols]], axis=1)
maindf

NEW VARIABLES FROM FLUX PROCESSING CHAIN:
++ DAYTIME
++ NIGHTTIME
++ FLAG_L2_FC_MISSING_TEST
++ FLAG_L2_FC_SSITC_TEST
++ FLAG_L2_FC_COMPLETENESS_TEST
++ FLAG_L2_FC_SCF_TEST
++ FLAG_L2_FC_SIGNAL_STRENGTH_TEST
++ FLAG_L2_FC_CO2_VM97_SPIKE_HF_TEST
++ FLAG_L2_FC_CO2_VM97_DROPOUT_TEST
++ SUM_L2_FC_HARDFLAGS
++ SUM_L2_FC_SOFTFLAGS
++ SUM_L2_FC_FLAGS
++ FLAG_L2_FC_QCF
++ FC_L2_QCF
++ FC_L2_QCF0
++ SC_SINGLE_gfRMED_L3.1
++ FLAG_SC_SINGLE_gfRMED_L3.1_ISFILLED
++ NEE_L3.1
++ NEE_L3.1_QCF
++ NEE_L3.1_QCF0
++ FLAG_L3.2_NEE_L3.1_QCF_OUTLIER_ABSLIM_TEST
++ FLAG_L3.2_NEE_L3.1_QCF_OUTLIER_MANUAL_TEST
++ FLAG_L3.2_NEE_L3.1_QCF_OUTLIER_HQROLL
++ FLAG_L3.2_NEE_L3.1_QCF_OUTLIER_HQROLL_TEST
++ FLAG_L3.2_NEE_L3.1_QCF_OUTLIER_HAMPELDTNT_TEST
++ SUM_L3.2_NEE_L3.1_HARDFLAGS
++ SUM_L3.2_NEE_L3.1_SOFTFLAGS
++ SUM_L3.2_NEE_L3.1_FLAGS
++ FLAG_L3.2_NEE_L3.1_QCF
++ NEE_L3.1_L3.2_QCF
++ NEE_L3.1_L3.2_QCF0

                     AIR_CP  AIR_DENSITY  AIR_MV  AIR_RHO_CP  AOA_METHOD  AXES_ROTATION_METHOD  BADM_HEIGHTC  BADM_INSTPAIR_EASTWARD_SEP_GA_CH4  BADM_INSTPAIR_EASTWARD_SEP_GA_CO2  BADM_INSTPAIR_EASTWARD_SEP_GA_H2O  BADM_INSTPAIR_EASTWARD_SEP_GA_N2O  BADM_INSTPAIR_HEIGHT_SEP_GA_CH4  BADM_INSTPAIR_HEIGHT_SEP_GA_CO2  BADM_INSTPAIR_HEIGHT_SEP_GA_H2O  BADM_INSTPAIR_HEIGHT_SEP_GA_N2O  ...  FLAG_SC_SINGLE_gfRMED_L3.1_ISFILLED  NEE_L3.1  NEE_L3.1_QCF  NEE_L3.1_QCF0  FLAG_L3.2_NEE_L3.1_QCF_OUTLIER_ABSLIM_TEST  FLAG_L3.2_NEE_L3.1_QCF_OUTLIER_MANUAL_TEST  FLAG_L3.2_NEE_L3.1_QCF_OUTLIER_HQROLL  FLAG_L3.2_NEE_L3.1_QCF_OUTLIER_HQROLL_TEST  FLAG_L3.2_NEE_L3.1_QCF_OUTLIER_HAMPELDTNT_TEST  SUM_L3.2_NEE_L3.1_HARDFLAGS  SUM_L3.2_NEE_L3.1_SOFTFLAGS  SUM_L3.2_NEE_L3.1_FLAGS  FLAG_L3.2_NEE_L3.1_QCF  NEE_L3.1_L3.2_QCF  NEE_L3.1_L3.2_QCF0
TIMESTAMP_MIDDLE                                                                                                                                                                                                                                                                                                                                                                              ...
2023-10-31 23:45:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                                  NaN       NaN           NaN            NaN                                         0.0                                         0.0                                  False                                         0.0                                             0.0                          2.0                          0.0                      2.0                     2.0                NaN                 NaN
2023-11-01 00:15:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                                  NaN       NaN           NaN            NaN                                         0.0                                         0.0                                  False                                         0.0                                             0.0                          2.0                          0.0                      2.0                     2.0                NaN                 NaN
2023-11-01 00:45:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                                  NaN       NaN           NaN            NaN                                         0.0                                         0.0                                  False                                         0.0                                             0.0                          2.0                          0.0                      2.0                     2.0                NaN                 NaN
2023-11-01 01:15:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                                  NaN       NaN           NaN            NaN                                         0.0                                         0.0                                  False                                         0.0                                             0.0                          2.0                          0.0                      2.0                     2.0                NaN                 NaN
2023-11-01 01:45:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                                  NaN       NaN           NaN            NaN                                         0.0                                         0.0                                  False                                         0.0                                             0.0                          2.0                          0.0                      2.0                     2.0                NaN                 NaN
...                     ...          ...     ...         ...         ...                   ...           ...                                ...                                ...                                ...                                ...                              ...                              ...                              ...                              ...  ...                                  ...       ...           ...            ...                                         ...                                         ...                                    ...                                         ...                                             ...                          ...                          ...                      ...                     ...                ...                 ...
2025-06-05 21:45:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                                  NaN       NaN           NaN            NaN                                         0.0                                         0.0                                  False                                         0.0                                             0.0                          2.0                          0.0                      2.0                     2.0                NaN                 NaN
2025-06-05 22:15:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                                  NaN       NaN           NaN            NaN                                         0.0                                         0.0                                  False                                         0.0                                             0.0                          2.0                          0.0                      2.0                     2.0                NaN                 NaN
2025-06-05 22:45:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                                  NaN       NaN           NaN            NaN                                         0.0                                         0.0                                  False                                         0.0                                             0.0                          2.0                          0.0                      2.0                     2.0                NaN                 NaN
2025-06-05 23:15:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                                  NaN       NaN           NaN            NaN                                         0.0                                         0.0                                  False                                         0.0                                             0.0                          2.0                          0.0                      2.0                     2.0                NaN                 NaN
2025-06-05 23:45:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                                  NaN       NaN           NaN            NaN                                         0.0                                         0.0                                  False                                         0.0                                             0.0                          2.0                          0.0                      2.0                     2.0                NaN                 NaN

[27985 rows x 495 columns]

## Add results for LE

In [18]:
newcols = [c for c in le.columns if c not in maindf]
print("NEW VARIABLES FROM FLUX PROCESSING CHAIN:")
[print(f"++ {c}") for c in newcols]
maindf = pd.concat([maindf, le[newcols]], axis=1)
maindf

NEW VARIABLES FROM FLUX PROCESSING CHAIN:
++ FLAG_L2_LE_MISSING_TEST
++ FLAG_L2_LE_SSITC_TEST
++ FLAG_L2_LE_COMPLETENESS_TEST
++ FLAG_L2_LE_SCF_TEST
++ FLAG_L2_LE_SIGNAL_STRENGTH_TEST
++ FLAG_L2_LE_H2O_VM97_SPIKE_HF_TEST
++ FLAG_L2_LE_H2O_VM97_DROPOUT_TEST
++ SUM_L2_LE_HARDFLAGS
++ SUM_L2_LE_SOFTFLAGS
++ SUM_L2_LE_FLAGS
++ FLAG_L2_LE_QCF
++ LE_L2_QCF
++ LE_L2_QCF0
++ SLE_SINGLE_gfRMED_L3.1
++ FLAG_SLE_SINGLE_gfRMED_L3.1_ISFILLED
++ LE_L3.1
++ LE_L3.1_QCF
++ LE_L3.1_QCF0
++ FLAG_L3.2_LE_L3.1_QCF_OUTLIER_ABSLIM_TEST
++ FLAG_L3.2_LE_L3.1_QCF_OUTLIER_MANUAL_TEST
++ FLAG_L3.2_LE_L3.1_QCF_OUTLIER_HQROLL
++ FLAG_L3.2_LE_L3.1_QCF_OUTLIER_HQROLL_TEST
++ SUM_L3.2_LE_L3.1_HARDFLAGS
++ SUM_L3.2_LE_L3.1_SOFTFLAGS
++ SUM_L3.2_LE_L3.1_FLAGS
++ FLAG_L3.2_LE_L3.1_QCF
++ LE_L3.1_L3.2_QCF
++ LE_L3.1_L3.2_QCF0

                     AIR_CP  AIR_DENSITY  AIR_MV  AIR_RHO_CP  AOA_METHOD  AXES_ROTATION_METHOD  BADM_HEIGHTC  BADM_INSTPAIR_EASTWARD_SEP_GA_CH4  BADM_INSTPAIR_EASTWARD_SEP_GA_CO2  BADM_INSTPAIR_EASTWARD_SEP_GA_H2O  BADM_INSTPAIR_EASTWARD_SEP_GA_N2O  BADM_INSTPAIR_HEIGHT_SEP_GA_CH4  BADM_INSTPAIR_HEIGHT_SEP_GA_CO2  BADM_INSTPAIR_HEIGHT_SEP_GA_H2O  BADM_INSTPAIR_HEIGHT_SEP_GA_N2O  ...  SLE_SINGLE_gfRMED_L3.1  FLAG_SLE_SINGLE_gfRMED_L3.1_ISFILLED  LE_L3.1  LE_L3.1_QCF  LE_L3.1_QCF0  FLAG_L3.2_LE_L3.1_QCF_OUTLIER_ABSLIM_TEST  FLAG_L3.2_LE_L3.1_QCF_OUTLIER_MANUAL_TEST  FLAG_L3.2_LE_L3.1_QCF_OUTLIER_HQROLL  FLAG_L3.2_LE_L3.1_QCF_OUTLIER_HQROLL_TEST  SUM_L3.2_LE_L3.1_HARDFLAGS  SUM_L3.2_LE_L3.1_SOFTFLAGS  SUM_L3.2_LE_L3.1_FLAGS  FLAG_L3.2_LE_L3.1_QCF  LE_L3.1_L3.2_QCF  LE_L3.1_L3.2_QCF0
TIMESTAMP_MIDDLE                                                                                                                                                                                                                                                                                                                                                                              ...
2023-10-31 23:45:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                     NaN                                   NaN      NaN          NaN           NaN                                        NaN                                        NaN                                   NaN                                        NaN                         NaN                         NaN                     NaN                    NaN               NaN                NaN
2023-11-01 00:15:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                     NaN                                   NaN      NaN          NaN           NaN                                        NaN                                        NaN                                   NaN                                        NaN                         NaN                         NaN                     NaN                    NaN               NaN                NaN
2023-11-01 00:45:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                     NaN                                   NaN      NaN          NaN           NaN                                        NaN                                        NaN                                   NaN                                        NaN                         NaN                         NaN                     NaN                    NaN               NaN                NaN
2023-11-01 01:15:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                     NaN                                   NaN      NaN          NaN           NaN                                        NaN                                        NaN                                   NaN                                        NaN                         NaN                         NaN                     NaN                    NaN               NaN                NaN
2023-11-01 01:45:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                     NaN                                   NaN      NaN          NaN           NaN                                        NaN                                        NaN                                   NaN                                        NaN                         NaN                         NaN                     NaN                    NaN               NaN                NaN
...                     ...          ...     ...         ...         ...                   ...           ...                                ...                                ...                                ...                                ...                              ...                              ...                              ...                              ...  ...                     ...                                   ...      ...          ...           ...                                        ...                                        ...                                   ...                                        ...                         ...                         ...                     ...                    ...               ...                ...
2025-06-05 21:45:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                     NaN                                   NaN      NaN          NaN           NaN                                        NaN                                        NaN                                   NaN                                        NaN                         NaN                         NaN                     NaN                    NaN               NaN                NaN
2025-06-05 22:15:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                     NaN                                   NaN      NaN          NaN           NaN                                        NaN                                        NaN                                   NaN                                        NaN                         NaN                         NaN                     NaN                    NaN               NaN                NaN
2025-06-05 22:45:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                     NaN                                   NaN      NaN          NaN           NaN                                        NaN                                        NaN                                   NaN                                        NaN                         NaN                         NaN                     NaN                    NaN               NaN                NaN
2025-06-05 23:15:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                     NaN                                   NaN      NaN          NaN           NaN                                        NaN                                        NaN                                   NaN                                        NaN                         NaN                         NaN                     NaN                    NaN               NaN                NaN
2025-06-05 23:45:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                     NaN                                   NaN      NaN          NaN           NaN                                        NaN                                        NaN                                   NaN                                        NaN                         NaN                         NaN                     NaN                    NaN               NaN                NaN

[27985 rows x 523 columns]

## Add results for H

In [19]:
newcols = [c for c in h.columns if c not in maindf]
print("NEW VARIABLES FROM FLUX PROCESSING CHAIN:")
[print(f"++ {c}") for c in newcols]
maindf = pd.concat([maindf, h[newcols]], axis=1)
maindf

NEW VARIABLES FROM FLUX PROCESSING CHAIN:
++ FLAG_L2_H_MISSING_TEST
++ FLAG_L2_H_SSITC_TEST
++ FLAG_L2_H_COMPLETENESS_TEST
++ FLAG_L2_H_SCF_TEST
++ FLAG_L2_H_T_SONIC_VM97_SPIKE_HF_TEST
++ FLAG_L2_H_T_SONIC_VM97_AMPLITUDE_RESOLUTION_HF_TEST
++ FLAG_L2_H_T_SONIC_VM97_DROPOUT_TEST
++ SUM_L2_H_HARDFLAGS
++ SUM_L2_H_SOFTFLAGS
++ SUM_L2_H_FLAGS
++ FLAG_L2_H_QCF
++ H_L2_QCF
++ H_L2_QCF0
++ SH_SINGLE_gfRMED_L3.1
++ FLAG_SH_SINGLE_gfRMED_L3.1_ISFILLED
++ H_L3.1
++ H_L3.1_QCF
++ H_L3.1_QCF0
++ FLAG_L3.2_H_L3.1_QCF_OUTLIER_ABSLIM_TEST
++ FLAG_L3.2_H_L3.1_QCF_OUTLIER_HQROLL
++ FLAG_L3.2_H_L3.1_QCF_OUTLIER_HQROLL_TEST
++ SUM_L3.2_H_L3.1_HARDFLAGS
++ SUM_L3.2_H_L3.1_SOFTFLAGS
++ SUM_L3.2_H_L3.1_FLAGS
++ FLAG_L3.2_H_L3.1_QCF
++ H_L3.1_L3.2_QCF
++ H_L3.1_L3.2_QCF0

                     AIR_CP  AIR_DENSITY  AIR_MV  AIR_RHO_CP  AOA_METHOD  AXES_ROTATION_METHOD  BADM_HEIGHTC  BADM_INSTPAIR_EASTWARD_SEP_GA_CH4  BADM_INSTPAIR_EASTWARD_SEP_GA_CO2  BADM_INSTPAIR_EASTWARD_SEP_GA_H2O  BADM_INSTPAIR_EASTWARD_SEP_GA_N2O  BADM_INSTPAIR_HEIGHT_SEP_GA_CH4  BADM_INSTPAIR_HEIGHT_SEP_GA_CO2  BADM_INSTPAIR_HEIGHT_SEP_GA_H2O  BADM_INSTPAIR_HEIGHT_SEP_GA_N2O  ...  H_L2_QCF0  SH_SINGLE_gfRMED_L3.1  FLAG_SH_SINGLE_gfRMED_L3.1_ISFILLED  H_L3.1  H_L3.1_QCF  H_L3.1_QCF0  FLAG_L3.2_H_L3.1_QCF_OUTLIER_ABSLIM_TEST  FLAG_L3.2_H_L3.1_QCF_OUTLIER_HQROLL  FLAG_L3.2_H_L3.1_QCF_OUTLIER_HQROLL_TEST  SUM_L3.2_H_L3.1_HARDFLAGS  SUM_L3.2_H_L3.1_SOFTFLAGS  SUM_L3.2_H_L3.1_FLAGS  FLAG_L3.2_H_L3.1_QCF  H_L3.1_L3.2_QCF  H_L3.1_L3.2_QCF0
TIMESTAMP_MIDDLE                                                                                                                                                                                                                                                                                                                                                                              ...
2023-10-31 23:45:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...        NaN                    NaN                                  NaN     NaN         NaN          NaN                                       NaN                                  NaN                                       NaN                        NaN                        NaN                    NaN                   NaN              NaN               NaN
2023-11-01 00:15:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...        NaN                    NaN                                  NaN     NaN         NaN          NaN                                       NaN                                  NaN                                       NaN                        NaN                        NaN                    NaN                   NaN              NaN               NaN
2023-11-01 00:45:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...        NaN                    NaN                                  NaN     NaN         NaN          NaN                                       NaN                                  NaN                                       NaN                        NaN                        NaN                    NaN                   NaN              NaN               NaN
2023-11-01 01:15:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...        NaN                    NaN                                  NaN     NaN         NaN          NaN                                       NaN                                  NaN                                       NaN                        NaN                        NaN                    NaN                   NaN              NaN               NaN
2023-11-01 01:45:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...        NaN                    NaN                                  NaN     NaN         NaN          NaN                                       NaN                                  NaN                                       NaN                        NaN                        NaN                    NaN                   NaN              NaN               NaN
...                     ...          ...     ...         ...         ...                   ...           ...                                ...                                ...                                ...                                ...                              ...                              ...                              ...                              ...  ...        ...                    ...                                  ...     ...         ...          ...                                       ...                                  ...                                       ...                        ...                        ...                    ...                   ...              ...               ...
2025-06-05 21:45:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...        NaN                    NaN                                  NaN     NaN         NaN          NaN                                       NaN                                  NaN                                       NaN                        NaN                        NaN                    NaN                   NaN              NaN               NaN
2025-06-05 22:15:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...        NaN                    NaN                                  NaN     NaN         NaN          NaN                                       NaN                                  NaN                                       NaN                        NaN                        NaN                    NaN                   NaN              NaN               NaN
2025-06-05 22:45:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...        NaN                    NaN                                  NaN     NaN         NaN          NaN                                       NaN                                  NaN                                       NaN                        NaN                        NaN                    NaN                   NaN              NaN               NaN
2025-06-05 23:15:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...        NaN                    NaN                                  NaN     NaN         NaN          NaN                                       NaN                                  NaN                                       NaN                        NaN                        NaN                    NaN                   NaN              NaN               NaN
2025-06-05 23:45:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...        NaN                    NaN                                  NaN     NaN         NaN          NaN                                       NaN                                  NaN                                       NaN                        NaN                        NaN                    NaN                   NaN              NaN               NaN

[27985 rows x 550 columns]

## Add results for N2O

In [20]:
newcols = [c for c in n2o.columns if c not in maindf]
print("NEW VARIABLES FROM FLUX PROCESSING CHAIN:")
[print(f"++ {c}") for c in newcols]
maindf = pd.concat([maindf, n2o[newcols]], axis=1)
maindf

NEW VARIABLES FROM FLUX PROCESSING CHAIN:
++ FLAG_L2_FN2O_MISSING_TEST
++ FLAG_L2_FN2O_SSITC_TEST
++ FLAG_L2_FN2O_COMPLETENESS_TEST
++ FLAG_L2_FN2O_SCF_TEST
++ FLAG_L2_FN2O_N2O_VM97_SPIKE_HF_TEST
++ FLAG_L2_FN2O_N2O_VM97_AMPLITUDE_RESOLUTION_HF_TEST
++ FLAG_L2_FN2O_N2O_VM97_DROPOUT_TEST
++ SUM_L2_FN2O_HARDFLAGS
++ SUM_L2_FN2O_SOFTFLAGS
++ SUM_L2_FN2O_FLAGS
++ FLAG_L2_FN2O_QCF
++ FN2O_L2_QCF
++ FN2O_L2_QCF0
++ SN2O_SINGLE_gfRMED_L3.1
++ FLAG_SN2O_SINGLE_gfRMED_L3.1_ISFILLED
++ FN2O_L3.1
++ FN2O_L3.1_QCF
++ FN2O_L3.1_QCF0
++ FLAG_L3.2_FN2O_L3.1_QCF_OUTLIER_ABSLIM_TEST
++ FLAG_L3.2_FN2O_L3.1_QCF_OUTLIER_HQROLL
++ FLAG_L3.2_FN2O_L3.1_QCF_OUTLIER_HQROLL_TEST
++ FLAG_L3.2_FN2O_L3.1_QCF_OUTLIER_HAMPEL_TEST
++ FLAG_L3.2_FN2O_L3.1_QCF_OUTLIER_ZSCOREROLLING_TEST
++ SUM_L3.2_FN2O_L3.1_HARDFLAGS
++ SUM_L3.2_FN2O_L3.1_SOFTFLAGS
++ SUM_L3.2_FN2O_L3.1_FLAGS
++ FLAG_L3.2_FN2O_L3.1_QCF
++ FN2O_L3.1_L3.2_QCF
++ FN2O_L3.1_L3.2_QCF0

                     AIR_CP  AIR_DENSITY  AIR_MV  AIR_RHO_CP  AOA_METHOD  AXES_ROTATION_METHOD  BADM_HEIGHTC  BADM_INSTPAIR_EASTWARD_SEP_GA_CH4  BADM_INSTPAIR_EASTWARD_SEP_GA_CO2  BADM_INSTPAIR_EASTWARD_SEP_GA_H2O  BADM_INSTPAIR_EASTWARD_SEP_GA_N2O  BADM_INSTPAIR_HEIGHT_SEP_GA_CH4  BADM_INSTPAIR_HEIGHT_SEP_GA_CO2  BADM_INSTPAIR_HEIGHT_SEP_GA_H2O  BADM_INSTPAIR_HEIGHT_SEP_GA_N2O  ...  FLAG_SN2O_SINGLE_gfRMED_L3.1_ISFILLED  FN2O_L3.1  FN2O_L3.1_QCF  FN2O_L3.1_QCF0  FLAG_L3.2_FN2O_L3.1_QCF_OUTLIER_ABSLIM_TEST  FLAG_L3.2_FN2O_L3.1_QCF_OUTLIER_HQROLL  FLAG_L3.2_FN2O_L3.1_QCF_OUTLIER_HQROLL_TEST  FLAG_L3.2_FN2O_L3.1_QCF_OUTLIER_HAMPEL_TEST  FLAG_L3.2_FN2O_L3.1_QCF_OUTLIER_ZSCOREROLLING_TEST  SUM_L3.2_FN2O_L3.1_HARDFLAGS  SUM_L3.2_FN2O_L3.1_SOFTFLAGS  SUM_L3.2_FN2O_L3.1_FLAGS  FLAG_L3.2_FN2O_L3.1_QCF  FN2O_L3.1_L3.2_QCF  FN2O_L3.1_L3.2_QCF0
TIMESTAMP_MIDDLE                                                                                                                                                                                                                                                                                                                                                                              ...
2023-10-31 23:45:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                                    NaN        NaN            NaN             NaN                                          NaN                                     NaN                                          NaN                                          NaN                                                NaN                            NaN                           NaN                       NaN                      NaN                 NaN                  NaN
2023-11-01 00:15:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                                    NaN        NaN            NaN             NaN                                          NaN                                     NaN                                          NaN                                          NaN                                                NaN                            NaN                           NaN                       NaN                      NaN                 NaN                  NaN
2023-11-01 00:45:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                                    NaN        NaN            NaN             NaN                                          NaN                                     NaN                                          NaN                                          NaN                                                NaN                            NaN                           NaN                       NaN                      NaN                 NaN                  NaN
2023-11-01 01:15:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                                    NaN        NaN            NaN             NaN                                          NaN                                     NaN                                          NaN                                          NaN                                                NaN                            NaN                           NaN                       NaN                      NaN                 NaN                  NaN
2023-11-01 01:45:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                                    NaN        NaN            NaN             NaN                                          NaN                                     NaN                                          NaN                                          NaN                                                NaN                            NaN                           NaN                       NaN                      NaN                 NaN                  NaN
...                     ...          ...     ...         ...         ...                   ...           ...                                ...                                ...                                ...                                ...                              ...                              ...                              ...                              ...  ...                                    ...        ...            ...             ...                                          ...                                     ...                                          ...                                          ...                                                ...                            ...                           ...                       ...                      ...                 ...                  ...
2025-06-05 21:45:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                                    NaN        NaN            NaN             NaN                                          NaN                                     NaN                                          NaN                                          NaN                                                NaN                            NaN                           NaN                       NaN                      NaN                 NaN                  NaN
2025-06-05 22:15:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                                    NaN        NaN            NaN             NaN                                          NaN                                     NaN                                          NaN                                          NaN                                                NaN                            NaN                           NaN                       NaN                      NaN                 NaN                  NaN
2025-06-05 22:45:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                                    NaN        NaN            NaN             NaN                                          NaN                                     NaN                                          NaN                                          NaN                                                NaN                            NaN                           NaN                       NaN                      NaN                 NaN                  NaN
2025-06-05 23:15:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                                    NaN        NaN            NaN             NaN                                          NaN                                     NaN                                          NaN                                          NaN                                                NaN                            NaN                           NaN                       NaN                      NaN                 NaN                  NaN
2025-06-05 23:45:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                                    NaN        NaN            NaN             NaN                                          NaN                                     NaN                                          NaN                                          NaN                                                NaN                            NaN                           NaN                       NaN                      NaN                 NaN                  NaN

[27985 rows x 579 columns]

## Add results for CH4

In [21]:
newcols = [c for c in ch4.columns if c not in maindf]
print("NEW VARIABLES FROM FLUX PROCESSING CHAIN:")
[print(f"++ {c}") for c in newcols]
maindf = pd.concat([maindf, ch4[newcols]], axis=1)
maindf

NEW VARIABLES FROM FLUX PROCESSING CHAIN:
++ FLAG_L2_FCH4_MISSING_TEST
++ FLAG_L2_FCH4_SSITC_TEST
++ FLAG_L2_FCH4_COMPLETENESS_TEST
++ FLAG_L2_FCH4_SCF_TEST
++ FLAG_L2_FCH4_CH4_VM97_SPIKE_HF_TEST
++ FLAG_L2_FCH4_CH4_VM97_AMPLITUDE_RESOLUTION_HF_TEST
++ FLAG_L2_FCH4_CH4_VM97_DROPOUT_TEST
++ SUM_L2_FCH4_HARDFLAGS
++ SUM_L2_FCH4_SOFTFLAGS
++ SUM_L2_FCH4_FLAGS
++ FLAG_L2_FCH4_QCF
++ FCH4_L2_QCF
++ FCH4_L2_QCF0
++ SCH4_SINGLE_gfRMED_L3.1
++ FLAG_SCH4_SINGLE_gfRMED_L3.1_ISFILLED
++ FCH4_L3.1
++ FCH4_L3.1_QCF
++ FCH4_L3.1_QCF0
++ FLAG_L3.2_FCH4_L3.1_QCF_OUTLIER_ABSLIM_TEST
++ FLAG_L3.2_FCH4_L3.1_QCF_OUTLIER_HQROLL
++ FLAG_L3.2_FCH4_L3.1_QCF_OUTLIER_HQROLL_TEST
++ FLAG_L3.2_FCH4_L3.1_QCF_OUTLIER_HAMPEL_TEST
++ FLAG_L3.2_FCH4_L3.1_QCF_OUTLIER_ZSCOREROLLING_TEST
++ SUM_L3.2_FCH4_L3.1_HARDFLAGS
++ SUM_L3.2_FCH4_L3.1_SOFTFLAGS
++ SUM_L3.2_FCH4_L3.1_FLAGS
++ FLAG_L3.2_FCH4_L3.1_QCF
++ FCH4_L3.1_L3.2_QCF
++ FCH4_L3.1_L3.2_QCF0

                     AIR_CP  AIR_DENSITY  AIR_MV  AIR_RHO_CP  AOA_METHOD  AXES_ROTATION_METHOD  BADM_HEIGHTC  BADM_INSTPAIR_EASTWARD_SEP_GA_CH4  BADM_INSTPAIR_EASTWARD_SEP_GA_CO2  BADM_INSTPAIR_EASTWARD_SEP_GA_H2O  BADM_INSTPAIR_EASTWARD_SEP_GA_N2O  BADM_INSTPAIR_HEIGHT_SEP_GA_CH4  BADM_INSTPAIR_HEIGHT_SEP_GA_CO2  BADM_INSTPAIR_HEIGHT_SEP_GA_H2O  BADM_INSTPAIR_HEIGHT_SEP_GA_N2O  ...  FLAG_SCH4_SINGLE_gfRMED_L3.1_ISFILLED  FCH4_L3.1  FCH4_L3.1_QCF  FCH4_L3.1_QCF0  FLAG_L3.2_FCH4_L3.1_QCF_OUTLIER_ABSLIM_TEST  FLAG_L3.2_FCH4_L3.1_QCF_OUTLIER_HQROLL  FLAG_L3.2_FCH4_L3.1_QCF_OUTLIER_HQROLL_TEST  FLAG_L3.2_FCH4_L3.1_QCF_OUTLIER_HAMPEL_TEST  FLAG_L3.2_FCH4_L3.1_QCF_OUTLIER_ZSCOREROLLING_TEST  SUM_L3.2_FCH4_L3.1_HARDFLAGS  SUM_L3.2_FCH4_L3.1_SOFTFLAGS  SUM_L3.2_FCH4_L3.1_FLAGS  FLAG_L3.2_FCH4_L3.1_QCF  FCH4_L3.1_L3.2_QCF  FCH4_L3.1_L3.2_QCF0
TIMESTAMP_MIDDLE                                                                                                                                                                                                                                                                                                                                                                              ...
2023-10-31 23:45:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                                    NaN        NaN            NaN             NaN                                          NaN                                     NaN                                          NaN                                          NaN                                                NaN                            NaN                           NaN                       NaN                      NaN                 NaN                  NaN
2023-11-01 00:15:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                                    NaN        NaN            NaN             NaN                                          NaN                                     NaN                                          NaN                                          NaN                                                NaN                            NaN                           NaN                       NaN                      NaN                 NaN                  NaN
2023-11-01 00:45:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                                    NaN        NaN            NaN             NaN                                          NaN                                     NaN                                          NaN                                          NaN                                                NaN                            NaN                           NaN                       NaN                      NaN                 NaN                  NaN
2023-11-01 01:15:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                                    NaN        NaN            NaN             NaN                                          NaN                                     NaN                                          NaN                                          NaN                                                NaN                            NaN                           NaN                       NaN                      NaN                 NaN                  NaN
2023-11-01 01:45:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                                    NaN        NaN            NaN             NaN                                          NaN                                     NaN                                          NaN                                          NaN                                                NaN                            NaN                           NaN                       NaN                      NaN                 NaN                  NaN
...                     ...          ...     ...         ...         ...                   ...           ...                                ...                                ...                                ...                                ...                              ...                              ...                              ...                              ...  ...                                    ...        ...            ...             ...                                          ...                                     ...                                          ...                                          ...                                                ...                            ...                           ...                       ...                      ...                 ...                  ...
2025-06-05 21:45:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                                    NaN        NaN            NaN             NaN                                          NaN                                     NaN                                          NaN                                          NaN                                                NaN                            NaN                           NaN                       NaN                      NaN                 NaN                  NaN
2025-06-05 22:15:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                                    NaN        NaN            NaN             NaN                                          NaN                                     NaN                                          NaN                                          NaN                                                NaN                            NaN                           NaN                       NaN                      NaN                 NaN                  NaN
2025-06-05 22:45:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                                    NaN        NaN            NaN             NaN                                          NaN                                     NaN                                          NaN                                          NaN                                                NaN                            NaN                           NaN                       NaN                      NaN                 NaN                  NaN
2025-06-05 23:15:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                                    NaN        NaN            NaN             NaN                                          NaN                                     NaN                                          NaN                                          NaN                                                NaN                            NaN                           NaN                       NaN                      NaN                 NaN                  NaN
2025-06-05 23:45:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                                    NaN        NaN            NaN             NaN                                          NaN                                     NaN                                          NaN                                          NaN                                                NaN                            NaN                           NaN                       NaN                      NaN                 NaN                  NaN

[27985 rows x 608 columns]

# Export

## Export all data

In [22]:
filename = "51.1_FLUXES_METEO_MGMT_L3.2_NEE_LE_H_FN2O_FCH4"
maindf.to_csv(f"{filename}.csv", index=True)
save_parquet(data=maindf, filename=filename)

Saved file 51.1_FLUXES_METEO_MGMT_L3.2_NEE_LE_H_FN2O_FCH4.parquet (3.203 seconds).

'51.1_FLUXES_METEO_MGMT_L3.2_NEE_LE_H_FN2O_FCH4.parquet'

## Export subset for REddyProc

In [23]:
from diive.core.times.times import insert_timestamp
export_REddyProc = maindf.copy()

In [24]:
exportcols = ['NEE_L3.1_L3.2_QCF', 'LE_L3.1_L3.2_QCF', 'H_L3.1_L3.2_QCF', 'FN2O_L3.1_L3.2_QCF', 'FCH4_L3.1_L3.2_QCF',
              'USTAR',
              'sw_in', 'ta', 'vpd']
export_REddyProc = export_REddyProc[exportcols].copy()
locs = (export_REddyProc.index.year >= 2023) & (export_REddyProc.index.year <= 2025)
export_REddyProc = export_REddyProc[locs].copy()
export_REddyProc = insert_timestamp(data=export_REddyProc, convention="end", set_as_index=True)
export_REddyProc

                     NEE_L3.1_L3.2_QCF  LE_L3.1_L3.2_QCF  H_L3.1_L3.2_QCF  FN2O_L3.1_L3.2_QCF  FCH4_L3.1_L3.2_QCF  USTAR  sw_in         ta       vpd
TIMESTAMP_END
2023-11-01 00:00:00                NaN               NaN              NaN                 NaN                 NaN    NaN    0.0   8.000000  0.216913
2023-11-01 00:30:00                NaN               NaN              NaN                 NaN                 NaN    NaN    0.0   8.633333  0.272054
2023-11-01 01:00:00                NaN               NaN              NaN                 NaN                 NaN    NaN    0.0   8.266667  0.257705
2023-11-01 01:30:00                NaN               NaN              NaN                 NaN                 NaN    NaN    0.0   6.966667  0.171078
2023-11-01 02:00:00                NaN               NaN              NaN                 NaN                 NaN    NaN    0.0   5.666667  0.104550
...                                ...               ...              ...                 ...                 ...    ...    ...        ...       ...
2025-06-05 22:00:00                NaN               NaN              NaN                 NaN                 NaN    NaN    0.0  15.833333  0.285270
2025-06-05 22:30:00                NaN               NaN              NaN                 NaN                 NaN    NaN    0.0  15.733333  0.289417
2025-06-05 23:00:00                NaN               NaN              NaN                 NaN                 NaN    NaN    0.0  16.200000  0.404542
2025-06-05 23:30:00                NaN               NaN              NaN                 NaN                 NaN    NaN    0.0  15.666667  0.316704
2025-06-06 00:00:00                NaN               NaN              NaN                 NaN                 NaN    NaN    0.0  15.500000  0.298935

[27985 rows x 9 columns]

In [ ]:
filename = "51.2_FluxProcessingChain_L3.2_subset-forREddyProc"
export_REddyProc.to_csv(f"{filename}.csv", index=True)
save_parquet(data=export_REddyProc, filename=filename)

Saved file 51.2_FluxProcessingChain_L3.3_subset-forREddyProc.parquet (0.096 seconds).

'51.2_FluxProcessingChain_L3.3_subset-forREddyProc.parquet'

</br>

---

# **End of notebook**

---

Congratulations, you reached the end of this notebook! Before you go let's store your finish time.

In [26]:
from datetime import datetime
dt_string = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
print(f"Finished. {dt_string}")

Finished. 2025-08-25 15:39:02