# Imports

In [1]:
from pathlib import Path
import pandas as pd
from diive.core.io.files import save_parquet, load_parquet

# Load L3.3 results for NEE, LE and H

In [2]:
nee = load_parquet(filepath=r"NEE/41.1_FluxProcessingChain_L3.2_NEE.parquet")
le = load_parquet(filepath=r"LE/42.1_FluxProcessingChain_L3.2_LE.parquet")
h = load_parquet(filepath=r"H/43.1_FluxProcessingChain_L3.2_H.parquet")
n2o = load_parquet(filepath=r"FN2O/44.1_FluxProcessingChain_L3.2_FN2O.parquet")
ch4 = load_parquet(filepath=r"FCH4/45.1_FluxProcessingChain_L3.2_FCH4.parquet")

Loaded .parquet file NEE/41.1_FluxProcessingChain_L3.2_NEE.parquet (0.501 seconds).
    --> Detected time resolution of <30 * Minutes> / 30min
Loaded .parquet file LE/42.1_FluxProcessingChain_L3.2_LE.parquet (0.488 seconds).
    --> Detected time resolution of <30 * Minutes> / 30min
Loaded .parquet file H/43.1_FluxProcessingChain_L3.2_H.parquet (0.589 seconds).
    --> Detected time resolution of <30 * Minutes> / 30min
Loaded .parquet file FN2O/44.1_FluxProcessingChain_L3.2_FN2O.parquet (0.459 seconds).
    --> Detected time resolution of <30 * Minutes> / 30min
Loaded .parquet file FCH4/45.1_FluxProcessingChain_L3.2_FCH4.parquet (0.422 seconds).
    --> Detected time resolution of <30 * Minutes> / 30min

In [3]:
# Load METEO
SOURCEDIR = r"../10_METEO"
FILENAME = r"13.1_CH-TAN_meteo_gapfilled.parquet"
FILEPATH = Path(SOURCEDIR) / FILENAME
meteo = load_parquet(filepath=FILEPATH)

Loaded .parquet file ..\10_METEO\13.1_CH-TAN_meteo_gapfilled.parquet (0.167 seconds).
    --> Detected time resolution of <30 * Minutes> / 30min

# Load main data

In [4]:
SOURCEDIR = r"../30_MERGE_DATA"
FILENAME = r"33.1_CH-TAN_IRGA+LGR_Level-1_eddypro_fluxnet.parquet"
FILEPATH = Path(SOURCEDIR) / FILENAME
maindf = load_parquet(filepath=FILEPATH)

Loaded .parquet file ..\30_MERGE_DATA\33.1_CH-TAN_IRGA+LGR_Level-1_eddypro_fluxnet.parquet (0.374 seconds).
    --> Detected time resolution of <30 * Minutes> / 30min

## Add results for NEE

In [5]:
newcols = [c for c in nee.columns if c not in maindf]
print("NEW VARIABLES FROM FLUX PROCESSING CHAIN:")
[print(f"++ {c}") for c in newcols]
maindf = pd.concat([maindf, nee[newcols]], axis=1)
maindf

NEW VARIABLES FROM FLUX PROCESSING CHAIN:
++ DAYTIME
++ NIGHTTIME
++ FLAG_L2_FC_MISSING_TEST
++ FLAG_L2_FC_SSITC_TEST
++ FLAG_L2_FC_COMPLETENESS_TEST
++ FLAG_L2_FC_SCF_TEST
++ FLAG_L2_FC_SIGNAL_STRENGTH_TEST
++ FLAG_L2_FC_CO2_VM97_SPIKE_HF_TEST
++ FLAG_L2_FC_CO2_VM97_DROPOUT_TEST
++ SUM_L2_FC_HARDFLAGS
++ SUM_L2_FC_SOFTFLAGS
++ SUM_L2_FC_FLAGS
++ FLAG_L2_FC_QCF
++ FC_L2_QCF
++ FC_L2_QCF0
++ SC_SINGLE_gfRMED_L3.1
++ FLAG_SC_SINGLE_gfRMED_L3.1_ISFILLED
++ NEE_L3.1
++ NEE_L3.1_QCF
++ NEE_L3.1_QCF0
++ FLAG_L3.2_NEE_L3.1_QCF_OUTLIER_ABSLIM_TEST
++ FLAG_L3.2_NEE_L3.1_QCF_OUTLIER_MANUAL_TEST
++ FLAG_L3.2_NEE_L3.1_QCF_OUTLIER_HQROLL
++ FLAG_L3.2_NEE_L3.1_QCF_OUTLIER_HQROLL_TEST
++ FLAG_L3.2_NEE_L3.1_QCF_OUTLIER_HAMPELDTNT_TEST
++ SUM_L3.2_NEE_L3.1_HARDFLAGS
++ SUM_L3.2_NEE_L3.1_SOFTFLAGS
++ SUM_L3.2_NEE_L3.1_FLAGS
++ FLAG_L3.2_NEE_L3.1_QCF
++ NEE_L3.1_L3.2_QCF
++ NEE_L3.1_L3.2_QCF0

                      AIR_CP  AIR_DENSITY    AIR_MV  AIR_RHO_CP  AOA_METHOD  AXES_ROTATION_METHOD  BADM_HEIGHTC  BADM_INSTPAIR_EASTWARD_SEP_GA_CH4  BADM_INSTPAIR_EASTWARD_SEP_GA_CO2  BADM_INSTPAIR_EASTWARD_SEP_GA_H2O  BADM_INSTPAIR_EASTWARD_SEP_GA_N2O  BADM_INSTPAIR_HEIGHT_SEP_GA_CH4  BADM_INSTPAIR_HEIGHT_SEP_GA_CO2  BADM_INSTPAIR_HEIGHT_SEP_GA_H2O  BADM_INSTPAIR_HEIGHT_SEP_GA_N2O  ...  FLAG_SC_SINGLE_gfRMED_L3.1_ISFILLED   NEE_L3.1  NEE_L3.1_QCF  NEE_L3.1_QCF0  FLAG_L3.2_NEE_L3.1_QCF_OUTLIER_ABSLIM_TEST  FLAG_L3.2_NEE_L3.1_QCF_OUTLIER_MANUAL_TEST  FLAG_L3.2_NEE_L3.1_QCF_OUTLIER_HQROLL  FLAG_L3.2_NEE_L3.1_QCF_OUTLIER_HQROLL_TEST  FLAG_L3.2_NEE_L3.1_QCF_OUTLIER_HAMPELDTNT_TEST  SUM_L3.2_NEE_L3.1_HARDFLAGS  SUM_L3.2_NEE_L3.1_SOFTFLAGS  SUM_L3.2_NEE_L3.1_FLAGS  FLAG_L3.2_NEE_L3.1_QCF  NEE_L3.1_L3.2_QCF  NEE_L3.1_L3.2_QCF0
TIMESTAMP_MIDDLE                                                                                                                                                                                                                                                                                                                                                                                 ...
2023-11-07 15:45:00  1009.65      1.18057  0.024459     1191.96         0.0                   1.0           0.5                               -4.5                                NaN                                NaN                               -4.5                             -3.0                              NaN                              NaN                             -3.0  ...                                  NaN        NaN           NaN            NaN                                         0.0                                         0.0                                  False                                         0.0                                             0.0                          2.0                          0.0                      2.0                     2.0                NaN                 NaN
2023-11-07 16:15:00  1009.74      1.18107  0.024448     1192.57         0.0                   1.0           0.5                               -4.5                                NaN                                NaN                               -4.5                             -3.0                              NaN                              NaN                             -3.0  ...                                  NaN        NaN           NaN            NaN                                         0.0                                         0.0                                  False                                         0.0                                             0.0                          2.0                          0.0                      2.0                     2.0                NaN                 NaN
2023-11-07 16:45:00  1009.93      1.18176  0.024430     1193.50         0.0                   1.0           0.5                               -4.5                                NaN                                NaN                               -4.5                             -3.0                              NaN                              NaN                             -3.0  ...                                  NaN        NaN           NaN            NaN                                         0.0                                         0.0                                  False                                         0.0                                             0.0                          2.0                          0.0                      2.0                     2.0                NaN                 NaN
2023-11-07 17:15:00  1009.97      1.18428  0.024377     1196.09         0.0                   1.0           0.5                               -4.5                                NaN                                NaN                               -4.5                             -3.0                              NaN                              NaN                             -3.0  ...                                  NaN        NaN           NaN            NaN                                         0.0                                         0.0                                  False                                         0.0                                             0.0                          2.0                          0.0                      2.0                     2.0                NaN                 NaN
2023-11-07 17:45:00  1010.06      1.18448  0.024372     1196.40         0.0                   1.0           0.5                               -4.5                                NaN                                NaN                               -4.5                             -3.0                              NaN                              NaN                             -3.0  ...                                  NaN        NaN           NaN            NaN                                         0.0                                         0.0                                  False                                         0.0                                             0.0                          2.0                          0.0                      2.0                     2.0                NaN                 NaN
...                      ...          ...       ...         ...         ...                   ...           ...                                ...                                ...                                ...                                ...                              ...                              ...                              ...                              ...  ...                                  ...        ...           ...            ...                                         ...                                         ...                                    ...                                         ...                                             ...                          ...                          ...                      ...                     ...                ...                 ...
2025-06-04 22:45:00  1014.01      1.14117  0.025232     1157.16         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                                  0.0  10.095010     10.095010      10.095010                                         0.0                                         0.0                                  False                                         0.0                                             0.0                          0.0                          0.0                      0.0                     0.0          10.095010           10.095010
2025-06-04 23:15:00  1014.04      1.14156  0.025222     1157.59         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                                  0.0   8.641342      8.641342       8.641342                                         0.0                                         0.0                                  False                                         0.0                                             0.0                          0.0                          0.0                      0.0                     0.0           8.641342            8.641342
2025-06-04 23:45:00  1013.47      1.14369  0.025185     1159.10         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                                  0.0   8.664543      8.664543       8.664543                                         0.0                                         0.0                                  False                                         0.0                                             0.0                          0.0                          0.0                      0.0                     0.0           8.664543            8.664543
2025-06-05 00:15:00  1013.36      1.14191  0.025226     1157.17         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                                  0.0  10.864698     10.864698      10.864698                                         0.0                                         0.0                                  False                                         0.0                                             0.0                          0.0                          0.0                      0.0                     0.0          10.864698           10.864698
2025-06-05 00:45:00  1013.39      1.14237  0.025216     1157.67         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                                  0.0  11.402250     11.402250      11.402250                                         0.0                                         0.0                                  False                                         0.0                                             0.0                          0.0                          0.0                      0.0                     0.0          11.402250           11.402250

[27619 rows x 456 columns]

## Add results for LE

In [6]:
newcols = [c for c in le.columns if c not in maindf]
print("NEW VARIABLES FROM FLUX PROCESSING CHAIN:")
[print(f"++ {c}") for c in newcols]
maindf = pd.concat([maindf, le[newcols]], axis=1)
maindf

NEW VARIABLES FROM FLUX PROCESSING CHAIN:
++ FLAG_L2_LE_MISSING_TEST
++ FLAG_L2_LE_SSITC_TEST
++ FLAG_L2_LE_COMPLETENESS_TEST
++ FLAG_L2_LE_SCF_TEST
++ FLAG_L2_LE_SIGNAL_STRENGTH_TEST
++ FLAG_L2_LE_H2O_VM97_SPIKE_HF_TEST
++ FLAG_L2_LE_H2O_VM97_DROPOUT_TEST
++ SUM_L2_LE_HARDFLAGS
++ SUM_L2_LE_SOFTFLAGS
++ SUM_L2_LE_FLAGS
++ FLAG_L2_LE_QCF
++ LE_L2_QCF
++ LE_L2_QCF0
++ SLE_SINGLE_gfRMED_L3.1
++ FLAG_SLE_SINGLE_gfRMED_L3.1_ISFILLED
++ LE_L3.1
++ LE_L3.1_QCF
++ LE_L3.1_QCF0
++ FLAG_L3.2_LE_L3.1_QCF_OUTLIER_ABSLIM_TEST
++ FLAG_L3.2_LE_L3.1_QCF_OUTLIER_MANUAL_TEST
++ FLAG_L3.2_LE_L3.1_QCF_OUTLIER_HQROLL
++ FLAG_L3.2_LE_L3.1_QCF_OUTLIER_HQROLL_TEST
++ SUM_L3.2_LE_L3.1_HARDFLAGS
++ SUM_L3.2_LE_L3.1_SOFTFLAGS
++ SUM_L3.2_LE_L3.1_FLAGS
++ FLAG_L3.2_LE_L3.1_QCF
++ LE_L3.1_L3.2_QCF
++ LE_L3.1_L3.2_QCF0

                      AIR_CP  AIR_DENSITY    AIR_MV  AIR_RHO_CP  AOA_METHOD  AXES_ROTATION_METHOD  BADM_HEIGHTC  BADM_INSTPAIR_EASTWARD_SEP_GA_CH4  BADM_INSTPAIR_EASTWARD_SEP_GA_CO2  BADM_INSTPAIR_EASTWARD_SEP_GA_H2O  BADM_INSTPAIR_EASTWARD_SEP_GA_N2O  BADM_INSTPAIR_HEIGHT_SEP_GA_CH4  BADM_INSTPAIR_HEIGHT_SEP_GA_CO2  BADM_INSTPAIR_HEIGHT_SEP_GA_H2O  BADM_INSTPAIR_HEIGHT_SEP_GA_N2O  ...  SLE_SINGLE_gfRMED_L3.1  FLAG_SLE_SINGLE_gfRMED_L3.1_ISFILLED   LE_L3.1  LE_L3.1_QCF  LE_L3.1_QCF0  FLAG_L3.2_LE_L3.1_QCF_OUTLIER_ABSLIM_TEST  FLAG_L3.2_LE_L3.1_QCF_OUTLIER_MANUAL_TEST  FLAG_L3.2_LE_L3.1_QCF_OUTLIER_HQROLL  FLAG_L3.2_LE_L3.1_QCF_OUTLIER_HQROLL_TEST  SUM_L3.2_LE_L3.1_HARDFLAGS  SUM_L3.2_LE_L3.1_SOFTFLAGS  SUM_L3.2_LE_L3.1_FLAGS  FLAG_L3.2_LE_L3.1_QCF  LE_L3.1_L3.2_QCF  LE_L3.1_L3.2_QCF0
TIMESTAMP_MIDDLE                                                                                                                                                                                                                                                                                                                                                                                 ...
2023-11-07 15:45:00  1009.65      1.18057  0.024459     1191.96         0.0                   1.0           0.5                               -4.5                                NaN                                NaN                               -4.5                             -3.0                              NaN                              NaN                             -3.0  ...                     NaN                                   NaN       NaN          NaN           NaN                                        0.0                                        0.0                                 False                                        0.0                         2.0                         0.0                     2.0                    2.0               NaN                NaN
2023-11-07 16:15:00  1009.74      1.18107  0.024448     1192.57         0.0                   1.0           0.5                               -4.5                                NaN                                NaN                               -4.5                             -3.0                              NaN                              NaN                             -3.0  ...                     NaN                                   NaN       NaN          NaN           NaN                                        0.0                                        0.0                                 False                                        0.0                         2.0                         0.0                     2.0                    2.0               NaN                NaN
2023-11-07 16:45:00  1009.93      1.18176  0.024430     1193.50         0.0                   1.0           0.5                               -4.5                                NaN                                NaN                               -4.5                             -3.0                              NaN                              NaN                             -3.0  ...                     NaN                                   NaN       NaN          NaN           NaN                                        0.0                                        0.0                                 False                                        0.0                         2.0                         0.0                     2.0                    2.0               NaN                NaN
2023-11-07 17:15:00  1009.97      1.18428  0.024377     1196.09         0.0                   1.0           0.5                               -4.5                                NaN                                NaN                               -4.5                             -3.0                              NaN                              NaN                             -3.0  ...                     NaN                                   NaN       NaN          NaN           NaN                                        0.0                                        0.0                                 False                                        0.0                         2.0                         0.0                     2.0                    2.0               NaN                NaN
2023-11-07 17:45:00  1010.06      1.18448  0.024372     1196.40         0.0                   1.0           0.5                               -4.5                                NaN                                NaN                               -4.5                             -3.0                              NaN                              NaN                             -3.0  ...                     NaN                                   NaN       NaN          NaN           NaN                                        0.0                                        0.0                                 False                                        0.0                         2.0                         0.0                     2.0                    2.0               NaN                NaN
...                      ...          ...       ...         ...         ...                   ...           ...                                ...                                ...                                ...                                ...                              ...                              ...                              ...                              ...  ...                     ...                                   ...       ...          ...           ...                                        ...                                        ...                                   ...                                        ...                         ...                         ...                     ...                    ...               ...                ...
2025-06-04 22:45:00  1014.01      1.14117  0.025232     1157.16         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                0.053195                                   0.0  3.778325     3.778325      3.778325                                        0.0                                        0.0                                 False                                        0.0                         0.0                         0.0                     0.0                    0.0          3.778325           3.778325
2025-06-04 23:15:00  1014.04      1.14156  0.025222     1157.59         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                0.109881                                   0.0 -0.947239    -0.947239     -0.947239                                        0.0                                        0.0                                 False                                        0.0                         0.0                         0.0                     0.0                    0.0         -0.947239          -0.947239
2025-06-04 23:45:00  1013.47      1.14369  0.025185     1159.10         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...               -1.944100                                   0.0 -4.271550          NaN           NaN                                        0.0                                        0.0                                 False                                        0.0                         0.0                         1.0                     1.0                    2.0               NaN                NaN
2025-06-05 00:15:00  1013.36      1.14191  0.025226     1157.17         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...               -0.434597                                   0.0  5.462043     5.462043      5.462043                                        0.0                                        0.0                                 False                                        0.0                         0.0                         0.0                     0.0                    0.0          5.462043           5.462043
2025-06-05 00:45:00  1013.39      1.14237  0.025216     1157.67         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                0.136608                                   0.0  9.108098     9.108098      9.108098                                        0.0                                        0.0                                 False                                        0.0                         0.0                         0.0                     0.0                    0.0          9.108098           9.108098

[27619 rows x 484 columns]

## Add results for H

In [7]:
newcols = [c for c in h.columns if c not in maindf]
print("NEW VARIABLES FROM FLUX PROCESSING CHAIN:")
[print(f"++ {c}") for c in newcols]
maindf = pd.concat([maindf, h[newcols]], axis=1)
maindf

NEW VARIABLES FROM FLUX PROCESSING CHAIN:
++ FLAG_L2_H_MISSING_TEST
++ FLAG_L2_H_SSITC_TEST
++ FLAG_L2_H_COMPLETENESS_TEST
++ FLAG_L2_H_SCF_TEST
++ FLAG_L2_H_T_SONIC_VM97_SPIKE_HF_TEST
++ FLAG_L2_H_T_SONIC_VM97_AMPLITUDE_RESOLUTION_HF_TEST
++ FLAG_L2_H_T_SONIC_VM97_DROPOUT_TEST
++ SUM_L2_H_HARDFLAGS
++ SUM_L2_H_SOFTFLAGS
++ SUM_L2_H_FLAGS
++ FLAG_L2_H_QCF
++ H_L2_QCF
++ H_L2_QCF0
++ SH_SINGLE_gfRMED_L3.1
++ FLAG_SH_SINGLE_gfRMED_L3.1_ISFILLED
++ H_L3.1
++ H_L3.1_QCF
++ H_L3.1_QCF0
++ FLAG_L3.2_H_L3.1_QCF_OUTLIER_ABSLIM_TEST
++ FLAG_L3.2_H_L3.1_QCF_OUTLIER_HQROLL
++ FLAG_L3.2_H_L3.1_QCF_OUTLIER_HQROLL_TEST
++ SUM_L3.2_H_L3.1_HARDFLAGS
++ SUM_L3.2_H_L3.1_SOFTFLAGS
++ SUM_L3.2_H_L3.1_FLAGS
++ FLAG_L3.2_H_L3.1_QCF
++ H_L3.1_L3.2_QCF
++ H_L3.1_L3.2_QCF0

                      AIR_CP  AIR_DENSITY    AIR_MV  AIR_RHO_CP  AOA_METHOD  AXES_ROTATION_METHOD  BADM_HEIGHTC  BADM_INSTPAIR_EASTWARD_SEP_GA_CH4  BADM_INSTPAIR_EASTWARD_SEP_GA_CO2  BADM_INSTPAIR_EASTWARD_SEP_GA_H2O  BADM_INSTPAIR_EASTWARD_SEP_GA_N2O  BADM_INSTPAIR_HEIGHT_SEP_GA_CH4  BADM_INSTPAIR_HEIGHT_SEP_GA_CO2  BADM_INSTPAIR_HEIGHT_SEP_GA_H2O  BADM_INSTPAIR_HEIGHT_SEP_GA_N2O  ...  H_L2_QCF0  SH_SINGLE_gfRMED_L3.1  FLAG_SH_SINGLE_gfRMED_L3.1_ISFILLED     H_L3.1  H_L3.1_QCF  H_L3.1_QCF0  FLAG_L3.2_H_L3.1_QCF_OUTLIER_ABSLIM_TEST  FLAG_L3.2_H_L3.1_QCF_OUTLIER_HQROLL  FLAG_L3.2_H_L3.1_QCF_OUTLIER_HQROLL_TEST  SUM_L3.2_H_L3.1_HARDFLAGS  SUM_L3.2_H_L3.1_SOFTFLAGS  SUM_L3.2_H_L3.1_FLAGS  FLAG_L3.2_H_L3.1_QCF  H_L3.1_L3.2_QCF  H_L3.1_L3.2_QCF0
TIMESTAMP_MIDDLE                                                                                                                                                                                                                                                                                                                                                                                 ...
2023-11-07 15:45:00  1009.65      1.18057  0.024459     1191.96         0.0                   1.0           0.5                               -4.5                                NaN                                NaN                               -4.5                             -3.0                              NaN                              NaN                             -3.0  ...        NaN              -0.179467                                  1.0  -0.352882         NaN          NaN                                       0.0                                False                                       0.0                        6.0                        0.0                    6.0                   2.0              NaN               NaN
2023-11-07 16:15:00  1009.74      1.18107  0.024448     1192.57         0.0                   1.0           0.5                               -4.5                                NaN                                NaN                               -4.5                             -3.0                              NaN                              NaN                             -3.0  ...        NaN              -0.089664                                  0.0  -5.434164         NaN          NaN                                       0.0                                False                                       0.0                        2.0                        0.0                    2.0                   2.0              NaN               NaN
2023-11-07 16:45:00  1009.93      1.18176  0.024430     1193.50         0.0                   1.0           0.5                               -4.5                                NaN                                NaN                               -4.5                             -3.0                              NaN                              NaN                             -3.0  ...        NaN              -0.179467                                  0.0  -1.975767   -1.975767          NaN                                       0.0                                False                                       0.0                        0.0                        1.0                    1.0                   1.0        -1.975767               NaN
2023-11-07 17:15:00  1009.97      1.18428  0.024377     1196.09         0.0                   1.0           0.5                               -4.5                                NaN                                NaN                               -4.5                             -3.0                              NaN                              NaN                             -3.0  ...   -10.9194              -0.764389                                  0.0 -11.683789  -11.683789   -11.683789                                       0.0                                False                                       0.0                        0.0                        0.0                    0.0                   0.0       -11.683789        -11.683789
2023-11-07 17:45:00  1010.06      1.18448  0.024372     1196.40         0.0                   1.0           0.5                               -4.5                                NaN                                NaN                               -4.5                             -3.0                              NaN                              NaN                             -3.0  ...   -10.8741               0.044976                                  0.0 -10.829124  -10.829124   -10.829124                                       0.0                                False                                       0.0                        0.0                        0.0                    0.0                   0.0       -10.829124        -10.829124
...                      ...          ...       ...         ...         ...                   ...           ...                                ...                                ...                                ...                                ...                              ...                              ...                              ...                              ...  ...        ...                    ...                                  ...        ...         ...          ...                                       ...                                  ...                                       ...                        ...                        ...                    ...                   ...              ...               ...
2025-06-04 22:45:00  1014.01      1.14117  0.025232     1157.16         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...   -39.1846               0.187053                                  0.0 -38.997547  -38.997547   -38.997547                                       0.0                                False                                       0.0                        0.0                        0.0                    0.0                   0.0       -38.997547        -38.997547
2025-06-04 23:15:00  1014.04      1.14156  0.025222     1157.59         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...   -39.7842              -0.065275                                  0.0 -39.849475  -39.849475   -39.849475                                       0.0                                False                                       0.0                        0.0                        0.0                    0.0                   0.0       -39.849475        -39.849475
2025-06-04 23:45:00  1013.47      1.14369  0.025185     1159.10         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...   -53.1522              -0.361662                                  0.0 -53.513862  -53.513862   -53.513862                                       0.0                                False                                       0.0                        0.0                        0.0                    0.0                   0.0       -53.513862        -53.513862
2025-06-05 00:15:00  1013.36      1.14191  0.025226     1157.17         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...   -62.9257               0.565512                                  0.0 -62.360188  -62.360188   -62.360188                                       0.0                                False                                       0.0                        0.0                        0.0                    0.0                   0.0       -62.360188        -62.360188
2025-06-05 00:45:00  1013.39      1.14237  0.025216     1157.67         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...   -47.7724              -0.174080                                  0.0 -47.946480  -47.946480   -47.946480                                       0.0                                False                                       0.0                        0.0                        0.0                    0.0                   0.0       -47.946480        -47.946480

[27619 rows x 511 columns]

## Add results for N2O

In [8]:
newcols = [c for c in n2o.columns if c not in maindf]
print("NEW VARIABLES FROM FLUX PROCESSING CHAIN:")
[print(f"++ {c}") for c in newcols]
maindf = pd.concat([maindf, n2o[newcols]], axis=1)
maindf

NEW VARIABLES FROM FLUX PROCESSING CHAIN:
++ FLAG_L2_FN2O_MISSING_TEST
++ FLAG_L2_FN2O_SSITC_TEST
++ FLAG_L2_FN2O_COMPLETENESS_TEST
++ FLAG_L2_FN2O_SCF_TEST
++ FLAG_L2_FN2O_N2O_VM97_SPIKE_HF_TEST
++ FLAG_L2_FN2O_N2O_VM97_AMPLITUDE_RESOLUTION_HF_TEST
++ FLAG_L2_FN2O_N2O_VM97_DROPOUT_TEST
++ SUM_L2_FN2O_HARDFLAGS
++ SUM_L2_FN2O_SOFTFLAGS
++ SUM_L2_FN2O_FLAGS
++ FLAG_L2_FN2O_QCF
++ FN2O_L2_QCF
++ FN2O_L2_QCF0
++ SN2O_SINGLE_gfRMED_L3.1
++ FLAG_SN2O_SINGLE_gfRMED_L3.1_ISFILLED
++ FN2O_L3.1
++ FN2O_L3.1_QCF
++ FN2O_L3.1_QCF0
++ FLAG_L3.2_FN2O_L3.1_QCF_OUTLIER_ABSLIM_TEST
++ FLAG_L3.2_FN2O_L3.1_QCF_OUTLIER_HQROLL
++ FLAG_L3.2_FN2O_L3.1_QCF_OUTLIER_HQROLL_TEST
++ FLAG_L3.2_FN2O_L3.1_QCF_OUTLIER_HAMPEL_TEST
++ FLAG_L3.2_FN2O_L3.1_QCF_OUTLIER_ZSCOREROLLING_TEST
++ SUM_L3.2_FN2O_L3.1_HARDFLAGS
++ SUM_L3.2_FN2O_L3.1_SOFTFLAGS
++ SUM_L3.2_FN2O_L3.1_FLAGS
++ FLAG_L3.2_FN2O_L3.1_QCF
++ FN2O_L3.1_L3.2_QCF
++ FN2O_L3.1_L3.2_QCF0

                      AIR_CP  AIR_DENSITY    AIR_MV  AIR_RHO_CP  AOA_METHOD  AXES_ROTATION_METHOD  BADM_HEIGHTC  BADM_INSTPAIR_EASTWARD_SEP_GA_CH4  BADM_INSTPAIR_EASTWARD_SEP_GA_CO2  BADM_INSTPAIR_EASTWARD_SEP_GA_H2O  BADM_INSTPAIR_EASTWARD_SEP_GA_N2O  BADM_INSTPAIR_HEIGHT_SEP_GA_CH4  BADM_INSTPAIR_HEIGHT_SEP_GA_CO2  BADM_INSTPAIR_HEIGHT_SEP_GA_H2O  BADM_INSTPAIR_HEIGHT_SEP_GA_N2O  ...  FLAG_SN2O_SINGLE_gfRMED_L3.1_ISFILLED  FN2O_L3.1  FN2O_L3.1_QCF  FN2O_L3.1_QCF0  FLAG_L3.2_FN2O_L3.1_QCF_OUTLIER_ABSLIM_TEST  FLAG_L3.2_FN2O_L3.1_QCF_OUTLIER_HQROLL  FLAG_L3.2_FN2O_L3.1_QCF_OUTLIER_HQROLL_TEST  FLAG_L3.2_FN2O_L3.1_QCF_OUTLIER_HAMPEL_TEST  FLAG_L3.2_FN2O_L3.1_QCF_OUTLIER_ZSCOREROLLING_TEST  SUM_L3.2_FN2O_L3.1_HARDFLAGS  SUM_L3.2_FN2O_L3.1_SOFTFLAGS  SUM_L3.2_FN2O_L3.1_FLAGS  FLAG_L3.2_FN2O_L3.1_QCF  FN2O_L3.1_L3.2_QCF  FN2O_L3.1_L3.2_QCF0
TIMESTAMP_MIDDLE                                                                                                                                                                                                                                                                                                                                                                                 ...
2023-11-07 15:45:00  1009.65      1.18057  0.024459     1191.96         0.0                   1.0           0.5                               -4.5                                NaN                                NaN                               -4.5                             -3.0                              NaN                              NaN                             -3.0  ...                                    1.0  -0.065984            NaN             NaN                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            4.0                           0.0                       4.0                      2.0                 NaN                  NaN
2023-11-07 16:15:00  1009.74      1.18107  0.024448     1192.57         0.0                   1.0           0.5                               -4.5                                NaN                                NaN                               -4.5                             -3.0                              NaN                              NaN                             -3.0  ...                                    0.0   0.324973       0.324973        0.324973                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            0.0                           0.0                       0.0                      0.0            0.324973             0.324973
2023-11-07 16:45:00  1009.93      1.18176  0.024430     1193.50         0.0                   1.0           0.5                               -4.5                                NaN                                NaN                               -4.5                             -3.0                              NaN                              NaN                             -3.0  ...                                    0.0   0.053551       0.053551        0.053551                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            0.0                           0.0                       0.0                      0.0            0.053551             0.053551
2023-11-07 17:15:00  1009.97      1.18428  0.024377     1196.09         0.0                   1.0           0.5                               -4.5                                NaN                                NaN                               -4.5                             -3.0                              NaN                              NaN                             -3.0  ...                                    0.0   0.339963       0.339963        0.339963                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            0.0                           0.0                       0.0                      0.0            0.339963             0.339963
2023-11-07 17:45:00  1010.06      1.18448  0.024372     1196.40         0.0                   1.0           0.5                               -4.5                                NaN                                NaN                               -4.5                             -3.0                              NaN                              NaN                             -3.0  ...                                    0.0  -0.983566      -0.983566       -0.983566                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            0.0                           0.0                       0.0                      0.0           -0.983566            -0.983566
...                      ...          ...       ...         ...         ...                   ...           ...                                ...                                ...                                ...                                ...                              ...                              ...                              ...                              ...  ...                                    ...        ...            ...             ...                                          ...                                     ...                                          ...                                          ...                                                ...                            ...                           ...                       ...                      ...                 ...                  ...
2025-06-04 22:45:00  1014.01      1.14117  0.025232     1157.16         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                                    0.0  -0.069384      -0.069384       -0.069384                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            0.0                           0.0                       0.0                      0.0           -0.069384            -0.069384
2025-06-04 23:15:00  1014.04      1.14156  0.025222     1157.59         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                                    0.0  -0.288296      -0.288296       -0.288296                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            0.0                           0.0                       0.0                      0.0           -0.288296            -0.288296
2025-06-04 23:45:00  1013.47      1.14369  0.025185     1159.10         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                                    0.0   0.220511       0.220511        0.220511                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            0.0                           0.0                       0.0                      0.0            0.220511             0.220511
2025-06-05 00:15:00  1013.36      1.14191  0.025226     1157.17         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                                    0.0  -0.021765      -0.021765             NaN                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            0.0                           1.0                       1.0                      1.0           -0.021765                  NaN
2025-06-05 00:45:00  1013.39      1.14237  0.025216     1157.67         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                                    0.0   0.190386       0.190386        0.190386                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            0.0                           0.0                       0.0                      0.0            0.190386             0.190386

[27619 rows x 540 columns]

## Add results for CH4

In [9]:
newcols = [c for c in ch4.columns if c not in maindf]
print("NEW VARIABLES FROM FLUX PROCESSING CHAIN:")
[print(f"++ {c}") for c in newcols]
maindf = pd.concat([maindf, ch4[newcols]], axis=1)
maindf

NEW VARIABLES FROM FLUX PROCESSING CHAIN:
++ FLAG_L2_FCH4_MISSING_TEST
++ FLAG_L2_FCH4_SSITC_TEST
++ FLAG_L2_FCH4_COMPLETENESS_TEST
++ FLAG_L2_FCH4_SCF_TEST
++ FLAG_L2_FCH4_CH4_VM97_SPIKE_HF_TEST
++ FLAG_L2_FCH4_CH4_VM97_AMPLITUDE_RESOLUTION_HF_TEST
++ FLAG_L2_FCH4_CH4_VM97_DROPOUT_TEST
++ SUM_L2_FCH4_HARDFLAGS
++ SUM_L2_FCH4_SOFTFLAGS
++ SUM_L2_FCH4_FLAGS
++ FLAG_L2_FCH4_QCF
++ FCH4_L2_QCF
++ FCH4_L2_QCF0
++ SCH4_SINGLE_gfRMED_L3.1
++ FLAG_SCH4_SINGLE_gfRMED_L3.1_ISFILLED
++ FCH4_L3.1
++ FCH4_L3.1_QCF
++ FCH4_L3.1_QCF0
++ FLAG_L3.2_FCH4_L3.1_QCF_OUTLIER_ABSLIM_TEST
++ FLAG_L3.2_FCH4_L3.1_QCF_OUTLIER_HQROLL
++ FLAG_L3.2_FCH4_L3.1_QCF_OUTLIER_HQROLL_TEST
++ FLAG_L3.2_FCH4_L3.1_QCF_OUTLIER_HAMPEL_TEST
++ FLAG_L3.2_FCH4_L3.1_QCF_OUTLIER_ZSCOREROLLING_TEST
++ SUM_L3.2_FCH4_L3.1_HARDFLAGS
++ SUM_L3.2_FCH4_L3.1_SOFTFLAGS
++ SUM_L3.2_FCH4_L3.1_FLAGS
++ FLAG_L3.2_FCH4_L3.1_QCF
++ FCH4_L3.1_L3.2_QCF
++ FCH4_L3.1_L3.2_QCF0

                      AIR_CP  AIR_DENSITY    AIR_MV  AIR_RHO_CP  AOA_METHOD  AXES_ROTATION_METHOD  BADM_HEIGHTC  BADM_INSTPAIR_EASTWARD_SEP_GA_CH4  BADM_INSTPAIR_EASTWARD_SEP_GA_CO2  BADM_INSTPAIR_EASTWARD_SEP_GA_H2O  BADM_INSTPAIR_EASTWARD_SEP_GA_N2O  BADM_INSTPAIR_HEIGHT_SEP_GA_CH4  BADM_INSTPAIR_HEIGHT_SEP_GA_CO2  BADM_INSTPAIR_HEIGHT_SEP_GA_H2O  BADM_INSTPAIR_HEIGHT_SEP_GA_N2O  ...  FLAG_SCH4_SINGLE_gfRMED_L3.1_ISFILLED  FCH4_L3.1  FCH4_L3.1_QCF  FCH4_L3.1_QCF0  FLAG_L3.2_FCH4_L3.1_QCF_OUTLIER_ABSLIM_TEST  FLAG_L3.2_FCH4_L3.1_QCF_OUTLIER_HQROLL  FLAG_L3.2_FCH4_L3.1_QCF_OUTLIER_HQROLL_TEST  FLAG_L3.2_FCH4_L3.1_QCF_OUTLIER_HAMPEL_TEST  FLAG_L3.2_FCH4_L3.1_QCF_OUTLIER_ZSCOREROLLING_TEST  SUM_L3.2_FCH4_L3.1_HARDFLAGS  SUM_L3.2_FCH4_L3.1_SOFTFLAGS  SUM_L3.2_FCH4_L3.1_FLAGS  FLAG_L3.2_FCH4_L3.1_QCF  FCH4_L3.1_L3.2_QCF  FCH4_L3.1_L3.2_QCF0
TIMESTAMP_MIDDLE                                                                                                                                                                                                                                                                                                                                                                                 ...
2023-11-07 15:45:00  1009.65      1.18057  0.024459     1191.96         0.0                   1.0           0.5                               -4.5                                NaN                                NaN                               -4.5                             -3.0                              NaN                              NaN                             -3.0  ...                                    1.0 -18.790539            NaN             NaN                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            2.0                           0.0                       2.0                      2.0                 NaN                  NaN
2023-11-07 16:15:00  1009.74      1.18107  0.024448     1192.57         0.0                   1.0           0.5                               -4.5                                NaN                                NaN                               -4.5                             -3.0                              NaN                              NaN                             -3.0  ...                                    0.0  -4.360399      -4.360399             NaN                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            0.0                           1.0                       1.0                      1.0           -4.360399                  NaN
2023-11-07 16:45:00  1009.93      1.18176  0.024430     1193.50         0.0                   1.0           0.5                               -4.5                                NaN                                NaN                               -4.5                             -3.0                              NaN                              NaN                             -3.0  ...                                    0.0   6.843150            NaN             NaN                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            2.0                           0.0                       2.0                      2.0                 NaN                  NaN
2023-11-07 17:15:00  1009.97      1.18428  0.024377     1196.09         0.0                   1.0           0.5                               -4.5                                NaN                                NaN                               -4.5                             -3.0                              NaN                              NaN                             -3.0  ...                                    0.0   2.488800       2.488800        2.488800                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            0.0                           0.0                       0.0                      0.0            2.488800             2.488800
2023-11-07 17:45:00  1010.06      1.18448  0.024372     1196.40         0.0                   1.0           0.5                               -4.5                                NaN                                NaN                               -4.5                             -3.0                              NaN                              NaN                             -3.0  ...                                    0.0  -9.177059      -9.177059       -9.177059                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            0.0                           0.0                       0.0                      0.0           -9.177059            -9.177059
...                      ...          ...       ...         ...         ...                   ...           ...                                ...                                ...                                ...                                ...                              ...                              ...                              ...                              ...  ...                                    ...        ...            ...             ...                                          ...                                     ...                                          ...                                          ...                                                ...                            ...                           ...                       ...                      ...                 ...                  ...
2025-06-04 22:45:00  1014.01      1.14117  0.025232     1157.16         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                                    0.0   2.160966       2.160966        2.160966                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            0.0                           0.0                       0.0                      0.0            2.160966             2.160966
2025-06-04 23:15:00  1014.04      1.14156  0.025222     1157.59         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                                    0.0  -1.904577      -1.904577             NaN                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            0.0                           1.0                       1.0                      1.0           -1.904577                  NaN
2025-06-04 23:45:00  1013.47      1.14369  0.025185     1159.10         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                                    0.0  -1.679224            NaN             NaN                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            2.0                           0.0                       2.0                      2.0                 NaN                  NaN
2025-06-05 00:15:00  1013.36      1.14191  0.025226     1157.17         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                                    0.0   4.656026       4.656026             NaN                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            0.0                           2.0                       2.0                      1.0            4.656026                  NaN
2025-06-05 00:45:00  1013.39      1.14237  0.025216     1157.67         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                                    0.0   1.726895            NaN             NaN                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            2.0                           1.0                       3.0                      2.0                 NaN                  NaN

[27619 rows x 569 columns]

# Export

## Export all data

In [10]:
filename = "46.1_FLUXES_L3.2_NEE_LE_H_FN2O_FCH4"
maindf.to_csv(f"{filename}.csv", index=True)
save_parquet(data=maindf, filename=filename)

Saved file 46.1_FLUXES_L3.2_NEE_LE_H_FN2O_FCH4.parquet (4.059 seconds).

'46.1_FLUXES_L3.2_NEE_LE_H_FN2O_FCH4.parquet'

## Export subset for REddyProc

In [11]:
from diive.core.times.times import insert_timestamp
export_REddyProc = maindf.copy()

In [12]:
newcols = [c for c in meteo.columns if c not in export_REddyProc]
export_REddyProc = pd.concat([export_REddyProc, meteo[newcols]], axis=1)

In [ ]:
exportcols = ['NEE_L3.1_L3.2_QCF', 'LE_L3.1_L3.2_QCF', 'H_L3.1_L3.2_QCF',
              'USTAR',
              'sw_in', 'ta', 'vpd']
export_REddyProc = export_REddyProc[exportcols].copy()
locs = (export_REddyProc.index.year >= 2023) & (export_REddyProc.index.year <= 2025)
export_REddyProc = export_REddyProc[locs].copy()
export_REddyProc = insert_timestamp(data=export_REddyProc, convention="end", set_as_index=True)
export_REddyProc

                     NEE_L3.1_L3.2_QCF  LE_L3.1_L3.2_QCF  H_L3.1_L3.2_QCF  FN2O_L3.1_L3.2_QCF  FCH4_L3.1_L3.2_QCF  USTAR  sw_in         ta       vpd
TIMESTAMP_END
2023-11-01 00:00:00                NaN               NaN              NaN                 NaN                 NaN    NaN    0.0   8.000000  0.216913
2023-11-01 00:30:00                NaN               NaN              NaN                 NaN                 NaN    NaN    0.0   8.633333  0.272054
2023-11-01 01:00:00                NaN               NaN              NaN                 NaN                 NaN    NaN    0.0   8.266667  0.257705
2023-11-01 01:30:00                NaN               NaN              NaN                 NaN                 NaN    NaN    0.0   6.966667  0.171078
2023-11-01 02:00:00                NaN               NaN              NaN                 NaN                 NaN    NaN    0.0   5.666667  0.104550
...                                ...               ...              ...                 ...                 ...    ...    ...        ...       ...
2025-06-05 22:00:00                NaN               NaN              NaN                 NaN                 NaN    NaN    0.0  15.833333  0.285270
2025-06-05 22:30:00                NaN               NaN              NaN                 NaN                 NaN    NaN    0.0  15.733333  0.289417
2025-06-05 23:00:00                NaN               NaN              NaN                 NaN                 NaN    NaN    0.0  16.200000  0.404542
2025-06-05 23:30:00                NaN               NaN              NaN                 NaN                 NaN    NaN    0.0  15.666667  0.316704
2025-06-06 00:00:00                NaN               NaN              NaN                 NaN                 NaN    NaN    0.0  15.500000  0.298935

[27985 rows x 9 columns]

In [14]:
filename = "46.2_FluxProcessingChain_L3.2_subset-forREddyProc"
export_REddyProc.to_csv(f"{filename}.csv", index=True)
save_parquet(data=export_REddyProc, filename=filename)

Saved file 46.2_FluxProcessingChain_L3.2_subset-forREddyProc.parquet (0.150 seconds).

'46.2_FluxProcessingChain_L3.2_subset-forREddyProc.parquet'

</br>

---

# **End of notebook**

---

Congratulations, you reached the end of this notebook! Before you go let's store your finish time.

In [15]:
from datetime import datetime
dt_string = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
print(f"Finished. {dt_string}")

Finished. 2025-09-17 10:24:05