# Imports

In [1]:
from pathlib import Path
import pandas as pd
from diive.core.io.files import save_parquet, load_parquet
import matplotlib.pyplot as plt

# Load main data

In [2]:
SOURCEDIR = r"../50_MERGE_DATA_FLUXES"
FILENAME = r"51.1_FLUXES_METEO_MGMT_L4.1_NEE_LE_H_FN2O_FCH4.parquet"
FILEPATH = Path(SOURCEDIR) / FILENAME
maindf = load_parquet(filepath=FILEPATH)
maindf

Loaded .parquet file ..\50_MERGE_DATA_FLUXES\51.1_FLUXES_METEO_MGMT_L4.1_NEE_LE_H_FN2O_FCH4.parquet (0.262 seconds).
    --> Detected time resolution of <30 * Minutes> / 30min

                      AIR_CP  AIR_DENSITY    AIR_MV  AIR_RHO_CP  AOA_METHOD  AXES_ROTATION_METHOD  BADM_HEIGHTC  BADM_INSTPAIR_EASTWARD_SEP_GA_CH4  BADM_INSTPAIR_EASTWARD_SEP_GA_CO2  BADM_INSTPAIR_EASTWARD_SEP_GA_H2O  BADM_INSTPAIR_EASTWARD_SEP_GA_N2O  BADM_INSTPAIR_HEIGHT_SEP_GA_CH4  BADM_INSTPAIR_HEIGHT_SEP_GA_CO2  BADM_INSTPAIR_HEIGHT_SEP_GA_H2O  BADM_INSTPAIR_HEIGHT_SEP_GA_N2O  ...  FCH4_L3.1_L3.3_CUT_50_QCF  FCH4_L3.1_L3.3_CUT_50_QCF0  FLAG_L3.3_CUT_84_FCH4_L3.1_USTAR_TEST  SUM_L3.3_CUT_84_FCH4_L3.1_HARDFLAGS  SUM_L3.3_CUT_84_FCH4_L3.1_SOFTFLAGS  SUM_L3.3_CUT_84_FCH4_L3.1_FLAGS  FLAG_L3.3_CUT_84_FCH4_L3.1_QCF  FCH4_L3.1_L3.3_CUT_84_QCF  FCH4_L3.1_L3.3_CUT_84_QCF0  FCH4_L3.1_L3.3_CUT_16_QCF_gfRF  FLAG_FCH4_L3.1_L3.3_CUT_16_QCF_gfRF_ISFILLED  FCH4_L3.1_L3.3_CUT_50_QCF_gfRF  FLAG_FCH4_L3.1_L3.3_CUT_50_QCF_gfRF_ISFILLED  FCH4_L3.1_L3.3_CUT_84_QCF_gfRF  FLAG_FCH4_L3.1_L3.3_CUT_84_QCF_gfRF_ISFILLED
TIMESTAMP_MIDDLE                                                                                                                                                                                                                                                                                                                                                                                 ...
2021-01-01 00:15:00  1008.65      1.20907  0.023898     1219.53         0.0                   1.0           0.5                                NaN                               -2.5                               -2.5                                NaN                              NaN                            -17.0                            -17.0                              NaN  ...                        NaN                         NaN                                    NaN                                  NaN                                  NaN                              NaN                             NaN                        NaN                         NaN                             NaN                                           NaN                             NaN                                           NaN                             NaN                                           NaN
2021-01-01 00:45:00  1008.64      1.20915  0.023896     1219.60         0.0                   1.0           0.5                                NaN                               -2.5                               -2.5                                NaN                              NaN                            -17.0                            -17.0                              NaN  ...                        NaN                         NaN                                    NaN                                  NaN                                  NaN                              NaN                             NaN                        NaN                         NaN                             NaN                                           NaN                             NaN                                           NaN                             NaN                                           NaN
2021-01-01 01:15:00  1008.64      1.20925  0.023894     1219.70         0.0                   1.0           0.5                                NaN                               -2.5                               -2.5                                NaN                              NaN                            -17.0                            -17.0                              NaN  ...                        NaN                         NaN                                    NaN                                  NaN                                  NaN                              NaN                             NaN                        NaN                         NaN                             NaN                                           NaN                             NaN                                           NaN                             NaN                                           NaN
2021-01-01 01:45:00  1008.65      1.20925  0.023894     1219.71         0.0                   1.0           0.5                                NaN                               -2.5                               -2.5                                NaN                              NaN                            -17.0                            -17.0                              NaN  ...                        NaN                         NaN                                    NaN                                  NaN                                  NaN                              NaN                             NaN                        NaN                         NaN                             NaN                                           NaN                             NaN                                           NaN                             NaN                                           NaN
2021-01-01 02:15:00  1008.65      1.20935  0.023892     1219.81         0.0                   1.0           0.5                                NaN                               -2.5                               -2.5                                NaN                              NaN                            -17.0                            -17.0                              NaN  ...                        NaN                         NaN                                    NaN                                  NaN                                  NaN                              NaN                             NaN                        NaN                         NaN                             NaN                                           NaN                             NaN                                           NaN                             NaN                                           NaN
...                      ...          ...       ...         ...         ...                   ...           ...                                ...                                ...                                ...                                ...                              ...                              ...                              ...                              ...  ...                        ...                         ...                                    ...                                  ...                                  ...                              ...                             ...                        ...                         ...                             ...                                           ...                             ...                                           ...                             ...                                           ...
2023-12-31 21:45:00  1008.89      1.21242  0.023828     1223.20         0.0                   1.0           0.5                                NaN                               -2.5                               -2.5                                NaN                              NaN                            -16.0                            -16.0                              NaN  ...                        NaN                         NaN                                    NaN                                  NaN                                  NaN                              NaN                             NaN                        NaN                         NaN                             NaN                                           NaN                             NaN                                           NaN                             NaN                                           NaN
2023-12-31 22:15:00  1008.98      1.21206  0.023834     1222.94         0.0                   1.0           0.5                                NaN                               -2.5                               -2.5                                NaN                              NaN                            -16.0                            -16.0                              NaN  ...                        NaN                         NaN                                    NaN                                  NaN                                  NaN                              NaN                             NaN                        NaN                         NaN                             NaN                                           NaN                             NaN                                           NaN                             NaN                                           NaN
2023-12-31 22:45:00  1009.08      1.21061  0.023861     1221.60         0.0                   1.0           0.5                                NaN                               -2.5                               -2.5                                NaN                              NaN                            -16.0                            -16.0                              NaN  ...                        NaN                         NaN                                    NaN                                  NaN                                  NaN                              NaN                             NaN                        NaN                         NaN                             NaN                                           NaN                             NaN                                           NaN                             NaN                                           NaN
2023-12-31 23:15:00  1009.24      1.20881  0.023894     1219.98         0.0                   1.0           0.5                                NaN                               -2.5                               -2.5                                NaN                              NaN                            -16.0                            -16.0                              NaN  ...                        NaN                         NaN                                    NaN                                  NaN                                  NaN                              NaN                             NaN                        NaN                         NaN                             NaN                                           NaN                             NaN                                           NaN                             NaN                                           NaN
2023-12-31 23:45:00  1009.44      1.20600  0.023946     1217.38         0.0                   1.0           0.5                                NaN                               -2.5                               -2.5                                NaN                              NaN                            -16.0                            -16.0                              NaN  ...                        NaN                         NaN                                    NaN                                  NaN                                  NaN                              NaN                             NaN                        NaN                         NaN                             NaN                                           NaN                             NaN                                           NaN                             NaN                                           NaN

[52560 rows x 717 columns]

# Load REddyProc output

In [3]:
SOURCEDIR = r"../60_MDS_REDDYPROC"
FILENAME = r"61.1_NEE_LE_REddyProcGapfilledPartitioned.csv"
FILEPATH = Path(SOURCEDIR) / FILENAME
reddy = pd.read_csv(FILEPATH)

# Convert timestamp to datetime and change from end to middle
reddy['TIMESTAMP_MIDDLE'] = pd.to_datetime(reddy['TIMESTAMP_END'], format='%Y-%m-%dT%H:%M:%SZ', errors='coerce') - pd.Timedelta(minutes=15)
# Drop the timestamp end
reddy.drop(columns='TIMESTAMP_END', inplace=True)
# Set the timestamp as index
reddy.set_index('TIMESTAMP_MIDDLE', inplace=True)

# Add a string to identify the reddyproc columns later
reddy.columns = [f'{c}_reddyproc' for c in reddy.columns]

reddy

                     NEE_U16_f_reddyproc  Reco_U16_reddyproc  GPP_U16_f_reddyproc  NEE_U50_f_reddyproc  Reco_U50_reddyproc  GPP_U50_f_reddyproc  NEE_U84_f_reddyproc  Reco_U84_reddyproc  GPP_U84_f_reddyproc  LE_f_reddyproc  H_f_reddyproc  ET_f_reddyproc
TIMESTAMP_MIDDLE
2020-12-31 23:15:00             1.465083            1.471708             0.006625             1.531928            1.515735            -0.016194             1.584801            1.552012            -0.032789        1.313335       1.188433        0.029150
2020-12-31 23:45:00             1.465083            1.470454             0.005372             1.531928            1.514467            -0.017462             1.584801            1.550737            -0.034063        1.301519       2.905173        0.028888
2021-01-01 00:15:00             1.465083            1.470235             0.005152             1.531928            1.514245            -0.017684             1.584801            1.550514            -0.034287        0.055464      -3.557021        0.001231
2021-01-01 00:45:00             1.465083            1.471799             0.006717             1.531928            1.515828            -0.016101             1.584801            1.552106            -0.032695        0.348332      -3.557021        0.007731
2021-01-01 01:15:00             1.465083            1.473942             0.008859             1.531928            1.517995            -0.013933             1.584801            1.554285            -0.030515       -0.038865      -3.557021       -0.000863
...                                  ...                 ...                  ...                  ...                 ...                  ...                  ...                 ...                  ...             ...            ...             ...
2023-12-31 20:45:00             1.539855            1.543549             0.003694             1.488481            1.555006             0.066525             1.348048            1.565430             0.217381        3.008443     -13.856629        0.066834
2023-12-31 21:15:00             1.519647            1.578190             0.058543             1.519647            1.589284             0.069638             1.519647            1.599309             0.079662       -0.746566      -7.992735       -0.016590
2023-12-31 21:45:00             1.432823            1.615999             0.183175             1.370211            1.626682             0.256471             1.348048            1.636257             0.288208       -0.853410      -5.293847       -0.018971
2023-12-31 22:15:00             0.593252            1.674743             1.081492             0.593252            1.684758             1.091506             0.593252            1.693603             1.100351       -1.187178      -3.587753       -0.026404
2023-12-31 22:45:00             1.295956            1.747225             0.451269             1.295956            1.756364             0.460408             1.295956            1.764261             0.468305       -0.409499      -6.293662       -0.009113

[52560 rows x 12 columns]

# Merge

In [4]:
newcols = [c for c in reddy.columns if c not in maindf]
print("NEW VARIABLES FROM REDDYPROC:")
[print(f"+ {c}") for c in newcols]
maindf = pd.concat([maindf, reddy[newcols]], axis=1)
maindf

NEW VARIABLES FROM REDDYPROC:
+ NEE_U16_f_reddyproc
+ Reco_U16_reddyproc
+ GPP_U16_f_reddyproc
+ NEE_U50_f_reddyproc
+ Reco_U50_reddyproc
+ GPP_U50_f_reddyproc
+ NEE_U84_f_reddyproc
+ Reco_U84_reddyproc
+ GPP_U84_f_reddyproc
+ LE_f_reddyproc
+ H_f_reddyproc
+ ET_f_reddyproc

                      AIR_CP  AIR_DENSITY    AIR_MV  AIR_RHO_CP  AOA_METHOD  AXES_ROTATION_METHOD  BADM_HEIGHTC  BADM_INSTPAIR_EASTWARD_SEP_GA_CH4  BADM_INSTPAIR_EASTWARD_SEP_GA_CO2  BADM_INSTPAIR_EASTWARD_SEP_GA_H2O  BADM_INSTPAIR_EASTWARD_SEP_GA_N2O  BADM_INSTPAIR_HEIGHT_SEP_GA_CH4  BADM_INSTPAIR_HEIGHT_SEP_GA_CO2  BADM_INSTPAIR_HEIGHT_SEP_GA_H2O  BADM_INSTPAIR_HEIGHT_SEP_GA_N2O  ...  FLAG_FCH4_L3.1_L3.3_CUT_50_QCF_gfRF_ISFILLED  FCH4_L3.1_L3.3_CUT_84_QCF_gfRF  FLAG_FCH4_L3.1_L3.3_CUT_84_QCF_gfRF_ISFILLED  NEE_U16_f_reddyproc  Reco_U16_reddyproc  GPP_U16_f_reddyproc  NEE_U50_f_reddyproc  Reco_U50_reddyproc  GPP_U50_f_reddyproc  NEE_U84_f_reddyproc  Reco_U84_reddyproc  GPP_U84_f_reddyproc  LE_f_reddyproc  H_f_reddyproc  ET_f_reddyproc
TIMESTAMP_MIDDLE                                                                                                                                                                                                                                                                                                                                                                                 ...
2020-12-31 23:15:00      NaN          NaN       NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                                           NaN                             NaN                                           NaN             1.465083            1.471708             0.006625             1.531928            1.515735            -0.016194             1.584801            1.552012            -0.032789        1.313335       1.188433        0.029150
2020-12-31 23:45:00      NaN          NaN       NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                                           NaN                             NaN                                           NaN             1.465083            1.470454             0.005372             1.531928            1.514467            -0.017462             1.584801            1.550737            -0.034063        1.301519       2.905173        0.028888
2021-01-01 00:15:00  1008.65      1.20907  0.023898     1219.53         0.0                   1.0           0.5                                NaN                               -2.5                               -2.5                                NaN                              NaN                            -17.0                            -17.0                              NaN  ...                                           NaN                             NaN                                           NaN             1.465083            1.470235             0.005152             1.531928            1.514245            -0.017684             1.584801            1.550514            -0.034287        0.055464      -3.557021        0.001231
2021-01-01 00:45:00  1008.64      1.20915  0.023896     1219.60         0.0                   1.0           0.5                                NaN                               -2.5                               -2.5                                NaN                              NaN                            -17.0                            -17.0                              NaN  ...                                           NaN                             NaN                                           NaN             1.465083            1.471799             0.006717             1.531928            1.515828            -0.016101             1.584801            1.552106            -0.032695        0.348332      -3.557021        0.007731
2021-01-01 01:15:00  1008.64      1.20925  0.023894     1219.70         0.0                   1.0           0.5                                NaN                               -2.5                               -2.5                                NaN                              NaN                            -17.0                            -17.0                              NaN  ...                                           NaN                             NaN                                           NaN             1.465083            1.473942             0.008859             1.531928            1.517995            -0.013933             1.584801            1.554285            -0.030515       -0.038865      -3.557021       -0.000863
...                      ...          ...       ...         ...         ...                   ...           ...                                ...                                ...                                ...                                ...                              ...                              ...                              ...                              ...  ...                                           ...                             ...                                           ...                  ...                 ...                  ...                  ...                 ...                  ...                  ...                 ...                  ...             ...            ...             ...
2023-12-31 21:45:00  1008.89      1.21242  0.023828     1223.20         0.0                   1.0           0.5                                NaN                               -2.5                               -2.5                                NaN                              NaN                            -16.0                            -16.0                              NaN  ...                                           NaN                             NaN                                           NaN             1.432823            1.615999             0.183175             1.370211            1.626682             0.256471             1.348048            1.636257             0.288208       -0.853410      -5.293847       -0.018971
2023-12-31 22:15:00  1008.98      1.21206  0.023834     1222.94         0.0                   1.0           0.5                                NaN                               -2.5                               -2.5                                NaN                              NaN                            -16.0                            -16.0                              NaN  ...                                           NaN                             NaN                                           NaN             0.593252            1.674743             1.081492             0.593252            1.684758             1.091506             0.593252            1.693603             1.100351       -1.187178      -3.587753       -0.026404
2023-12-31 22:45:00  1009.08      1.21061  0.023861     1221.60         0.0                   1.0           0.5                                NaN                               -2.5                               -2.5                                NaN                              NaN                            -16.0                            -16.0                              NaN  ...                                           NaN                             NaN                                           NaN             1.295956            1.747225             0.451269             1.295956            1.756364             0.460408             1.295956            1.764261             0.468305       -0.409499      -6.293662       -0.009113
2023-12-31 23:15:00  1009.24      1.20881  0.023894     1219.98         0.0                   1.0           0.5                                NaN                               -2.5                               -2.5                                NaN                              NaN                            -16.0                            -16.0                              NaN  ...                                           NaN                             NaN                                           NaN                  NaN                 NaN                  NaN                  NaN                 NaN                  NaN                  NaN                 NaN                  NaN             NaN            NaN             NaN
2023-12-31 23:45:00  1009.44      1.20600  0.023946     1217.38         0.0                   1.0           0.5                                NaN                               -2.5                               -2.5                                NaN                              NaN                            -16.0                            -16.0                              NaN  ...                                           NaN                             NaN                                           NaN                  NaN                 NaN                  NaN                  NaN                 NaN                  NaN                  NaN                 NaN                  NaN             NaN            NaN             NaN

[52562 rows x 729 columns]

# Export

In [5]:
filename = "71.1_FLUXES_METEO_MGMT_L4.1_NEE_LE_H_FN2O_FCH4_REDDYPROC"
maindf.to_csv(f"{filename}.csv", index=True)
save_parquet(data=maindf, filename=filename)

Saved file 71.1_FLUXES_METEO_MGMT_L4.1_NEE_LE_H_FN2O_FCH4_REDDYPROC.parquet (2.402 seconds).

'71.1_FLUXES_METEO_MGMT_L4.1_NEE_LE_H_FN2O_FCH4_REDDYPROC.parquet'